name = "LakeJs"
version = "0.1.0"
defaultTargets = ["LakeJs"]
testDriver = "LakeJsTest"

[[require]]
name = "NonEmpty"
git = "https://github.com/srghma/lean-nonempty.git"
rev = "main"

[[require]]
name = "spec"
git = "https://github.com/srghma/lean-spec.git"
rev = "main"

[[lean_lib]]
name = "LakeJs"
roots = ["LakeJs.LeanEnumSchema"]

[[lean_exe]]
name = "LakeJsTest"
root = "LakeJsTest.Main"

