import LakeJs.FrontEndTy

/-!
# The scalar functions of the runtime, by the C symbol that names them

Lean's `@[extern "lean_uint32_add"]` says which function of the runtime a declaration is
implemented by, and the constructors of the terminal families of
`LakeJs.LeanInitPureExterns` carry exactly those symbols.  This table pairs them up: for
each such constructor, the helper of `LakeJs.Expr.Ops` that applies it and the types of
its arguments and of its result, as the front end's `STy`.

So a call of a declaration that has no Lean body becomes a call of the runtime whenever
the C symbol of its `@[extern]` attribute is a row here, and the types of the row are the
ones the catalogue gives it — nothing about the call is guessed at.

**This file is generated by `scripts/gen-prim-extern-table.py` from
`LakeJs/LeanInitPureExterns.lean`.  Do not edit it by hand.**
-/

namespace LakeJs.FrontEnd

/-- A function of the runtime between terminal types: the C symbol Lean's `@[extern]`
    attribute names, the helper of `LakeJs.Expr.Ops` that applies it, and its type. -/
structure PrimExtern where
  /-- The C symbol, which is also the name of the catalogue constructor. -/
  cname : String
  /-- The helper of `LakeJs.Expr.Ops` that builds the call. -/
  helper : String
  /-- The types of its arguments. -/
  argTys : List STy
  /-- The type of its result. -/
  ret : STy

/-- Every scalar function of the catalogue, by the C symbol that names it. -/
def primExternTable : List PrimExtern :=
  [ ⟨"acos"                          , "(prim1Op .acos)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"acosf"                         , "(prim1Op .acosf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"acosh"                         , "(prim1Op .acosh)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"acoshf"                        , "(prim1Op .acoshf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"asin"                          , "(prim1Op .asin)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"asinf"                         , "(prim1Op .asinf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"asinh"                         , "(prim1Op .asinh)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"asinhf"                        , "(prim1Op .asinhf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"atan"                          , "(prim1Op .atan)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"atan2"                         , "(prim2Op .atan2)", [(.scalar .float), (.scalar .float)], (.scalar .float)⟩
  , ⟨"atan2f"                        , "(prim2Op .atan2f)", [(.scalar .float32), (.scalar .float32)], (.scalar .float32)⟩
  , ⟨"atanf"                         , "(prim1Op .atanf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"atanh"                         , "(prim1Op .atanh)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"atanhf"                        , "(prim1Op .atanhf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"cbrt"                          , "(prim1Op .cbrt)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"cbrtf"                         , "(prim1Op .cbrtf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"ceil"                          , "(prim1Op .ceil)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"ceilf"                         , "(prim1Op .ceilf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"cos"                           , "(prim1Op .cos)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"cosf"                          , "(prim1Op .cosf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"cosh"                          , "(prim1Op .cosh)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"coshf"                         , "(prim1Op .coshf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"exp"                           , "(prim1Op .exp)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"exp2"                          , "(prim1Op .exp2)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"exp2f"                         , "(prim1Op .exp2f)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"expf"                          , "(prim1Op .expf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"fabs"                          , "(prim1Op .fabs)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"fabsf"                         , "(prim1Op .fabsf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"floor"                         , "(prim1Op .floor)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"floorf"                        , "(prim1Op .floorf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"lean_bool_to_int16"            , "(prim1Op .lean_bool_to_int16)", [.bool], (.scalar .int16)⟩
  , ⟨"lean_bool_to_int32"            , "(prim1Op .lean_bool_to_int32)", [.bool], (.scalar .int32)⟩
  , ⟨"lean_bool_to_int64"            , "(prim1Op .lean_bool_to_int64)", [.bool], (.scalar .int64)⟩
  , ⟨"lean_bool_to_int8"             , "(prim1Op .lean_bool_to_int8)", [.bool], (.scalar .int8)⟩
  , ⟨"lean_bool_to_isize"            , "(prim1Op .lean_bool_to_isize)", [.bool], (.scalar .int64)⟩
  , ⟨"lean_bool_to_uint16"           , "(prim1Op .lean_bool_to_uint16)", [.bool], (.scalar .uint16)⟩
  , ⟨"lean_bool_to_uint32"           , "(prim1Op .lean_bool_to_uint32)", [.bool], (.scalar .uint32)⟩
  , ⟨"lean_bool_to_uint64"           , "(prim1Op .lean_bool_to_uint64)", [.bool], (.scalar .uint64)⟩
  , ⟨"lean_bool_to_uint8"            , "(prim1Op .lean_bool_to_uint8)", [.bool], (.scalar .uint8)⟩
  , ⟨"lean_bool_to_usize"            , "(prim1Op .lean_bool_to_usize)", [.bool], (.scalar .uint64)⟩
  , ⟨"lean_char_of_nat_aux"          , "(prim1Op .lean_char_of_nat_aux)", [.nat], .char⟩
  , ⟨"lean_float32_add"              , "(prim2Op .lean_float32_add)", [(.scalar .float32), (.scalar .float32)], (.scalar .float32)⟩
  , ⟨"lean_float32_beq"              , "(prim2Op .lean_float32_beq)", [(.scalar .float32), (.scalar .float32)], .bool⟩
  , ⟨"lean_float32_decLe"            , "(prim2Op .lean_float32_decLe)", [(.scalar .float32), (.scalar .float32)], .bool⟩
  , ⟨"lean_float32_decLt"            , "(prim2Op .lean_float32_decLt)", [(.scalar .float32), (.scalar .float32)], .bool⟩
  , ⟨"lean_float32_div"              , "(prim2Op .lean_float32_div)", [(.scalar .float32), (.scalar .float32)], (.scalar .float32)⟩
  , ⟨"lean_float32_isfinite"         , "(prim1Op .lean_float32_isfinite)", [(.scalar .float32)], .bool⟩
  , ⟨"lean_float32_isinf"            , "(prim1Op .lean_float32_isinf)", [(.scalar .float32)], .bool⟩
  , ⟨"lean_float32_isnan"            , "(prim1Op .lean_float32_isnan)", [(.scalar .float32)], .bool⟩
  , ⟨"lean_float32_le"               , "(prim2Op .lean_float32_le)", [(.scalar .float32), (.scalar .float32)], .bool⟩
  , ⟨"lean_float32_lt"               , "(prim2Op .lean_float32_lt)", [(.scalar .float32), (.scalar .float32)], .bool⟩
  , ⟨"lean_float32_mul"              , "(prim2Op .lean_float32_mul)", [(.scalar .float32), (.scalar .float32)], (.scalar .float32)⟩
  , ⟨"lean_float32_negate"           , "(prim1Op .lean_float32_negate)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"lean_float32_of_bits"          , "(prim1Op .lean_float32_of_bits)", [(.scalar .uint32)], (.scalar .float32)⟩
  , ⟨"lean_float32_scaleb"           , "(prim2Op .lean_float32_scaleb)", [(.scalar .float32), (.scalar .int64)], (.scalar .float32)⟩
  , ⟨"lean_float32_sub"              , "(prim2Op .lean_float32_sub)", [(.scalar .float32), (.scalar .float32)], (.scalar .float32)⟩
  , ⟨"lean_float32_to_bits"          , "(prim1Op .lean_float32_to_bits)", [(.scalar .float32)], (.scalar .uint32)⟩
  , ⟨"lean_float32_to_float"         , "(prim1Op .lean_float32_to_float)", [(.scalar .float32)], (.scalar .float)⟩
  , ⟨"lean_float32_to_int16"         , "(prim1Op .lean_float32_to_int16)", [(.scalar .float32)], (.scalar .int16)⟩
  , ⟨"lean_float32_to_int32"         , "(prim1Op .lean_float32_to_int32)", [(.scalar .float32)], (.scalar .int32)⟩
  , ⟨"lean_float32_to_int64"         , "(prim1Op .lean_float32_to_int64)", [(.scalar .float32)], (.scalar .int64)⟩
  , ⟨"lean_float32_to_int8"          , "(prim1Op .lean_float32_to_int8)", [(.scalar .float32)], (.scalar .int8)⟩
  , ⟨"lean_float32_to_isize"         , "(prim1Op .lean_float32_to_isize)", [(.scalar .float32)], (.scalar .int64)⟩
  , ⟨"lean_float32_to_string"        , "(prim1Op .lean_float32_to_string)", [(.scalar .float32)], .string⟩
  , ⟨"lean_float32_to_uint16"        , "(prim1Op .lean_float32_to_uint16)", [(.scalar .float32)], (.scalar .uint16)⟩
  , ⟨"lean_float32_to_uint32"        , "(prim1Op .lean_float32_to_uint32)", [(.scalar .float32)], (.scalar .uint32)⟩
  , ⟨"lean_float32_to_uint64"        , "(prim1Op .lean_float32_to_uint64)", [(.scalar .float32)], (.scalar .uint64)⟩
  , ⟨"lean_float32_to_uint8"         , "(prim1Op .lean_float32_to_uint8)", [(.scalar .float32)], (.scalar .uint8)⟩
  , ⟨"lean_float32_to_usize"         , "(prim1Op .lean_float32_to_usize)", [(.scalar .float32)], (.scalar .uint64)⟩
  , ⟨"lean_float_add"                , "(prim2Op .lean_float_add)", [(.scalar .float), (.scalar .float)], (.scalar .float)⟩
  , ⟨"lean_float_beq"                , "(prim2Op .lean_float_beq)", [(.scalar .float), (.scalar .float)], .bool⟩
  , ⟨"lean_float_decLe"              , "(prim2Op .lean_float_decLe)", [(.scalar .float), (.scalar .float)], .bool⟩
  , ⟨"lean_float_decLt"              , "(prim2Op .lean_float_decLt)", [(.scalar .float), (.scalar .float)], .bool⟩
  , ⟨"lean_float_div"                , "(prim2Op .lean_float_div)", [(.scalar .float), (.scalar .float)], (.scalar .float)⟩
  , ⟨"lean_float_isfinite"           , "(prim1Op .lean_float_isfinite)", [(.scalar .float)], .bool⟩
  , ⟨"lean_float_isinf"              , "(prim1Op .lean_float_isinf)", [(.scalar .float)], .bool⟩
  , ⟨"lean_float_isnan"              , "(prim1Op .lean_float_isnan)", [(.scalar .float)], .bool⟩
  , ⟨"lean_float_le"                 , "(prim2Op .lean_float_le)", [(.scalar .float), (.scalar .float)], .bool⟩
  , ⟨"lean_float_lt"                 , "(prim2Op .lean_float_lt)", [(.scalar .float), (.scalar .float)], .bool⟩
  , ⟨"lean_float_mul"                , "(prim2Op .lean_float_mul)", [(.scalar .float), (.scalar .float)], (.scalar .float)⟩
  , ⟨"lean_float_negate"             , "(prim1Op .lean_float_negate)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"lean_float_of_bits"            , "(prim1Op .lean_float_of_bits)", [(.scalar .uint64)], (.scalar .float)⟩
  , ⟨"lean_float_scaleb"             , "(prim2Op .lean_float_scaleb)", [(.scalar .float), (.scalar .int64)], (.scalar .float)⟩
  , ⟨"lean_float_sub"                , "(prim2Op .lean_float_sub)", [(.scalar .float), (.scalar .float)], (.scalar .float)⟩
  , ⟨"lean_float_to_bits"            , "(prim1Op .lean_float_to_bits)", [(.scalar .float)], (.scalar .uint64)⟩
  , ⟨"lean_float_to_float32"         , "(prim1Op .lean_float_to_float32)", [(.scalar .float)], (.scalar .float32)⟩
  , ⟨"lean_float_to_int16"           , "(prim1Op .lean_float_to_int16)", [(.scalar .float)], (.scalar .int16)⟩
  , ⟨"lean_float_to_int32"           , "(prim1Op .lean_float_to_int32)", [(.scalar .float)], (.scalar .int32)⟩
  , ⟨"lean_float_to_int64"           , "(prim1Op .lean_float_to_int64)", [(.scalar .float)], (.scalar .int64)⟩
  , ⟨"lean_float_to_int8"            , "(prim1Op .lean_float_to_int8)", [(.scalar .float)], (.scalar .int8)⟩
  , ⟨"lean_float_to_isize"           , "(prim1Op .lean_float_to_isize)", [(.scalar .float)], (.scalar .int64)⟩
  , ⟨"lean_float_to_string"          , "(prim1Op .lean_float_to_string)", [(.scalar .float)], .string⟩
  , ⟨"lean_float_to_uint16"          , "(prim1Op .lean_float_to_uint16)", [(.scalar .float)], (.scalar .uint16)⟩
  , ⟨"lean_float_to_uint32"          , "(prim1Op .lean_float_to_uint32)", [(.scalar .float)], (.scalar .uint32)⟩
  , ⟨"lean_float_to_uint64"          , "(prim1Op .lean_float_to_uint64)", [(.scalar .float)], (.scalar .uint64)⟩
  , ⟨"lean_float_to_uint8"           , "(prim1Op .lean_float_to_uint8)", [(.scalar .float)], (.scalar .uint8)⟩
  , ⟨"lean_float_to_usize"           , "(prim1Op .lean_float_to_usize)", [(.scalar .float)], (.scalar .uint64)⟩
  , ⟨"lean_int16_abs"                , "(prim1Op .lean_int16_abs)", [(.scalar .int16)], (.scalar .int16)⟩
  , ⟨"lean_int16_add"                , "(prim2Op .lean_int16_add)", [(.scalar .int16), (.scalar .int16)], (.scalar .int16)⟩
  , ⟨"lean_int16_complement"         , "(prim1Op .lean_int16_complement)", [(.scalar .int16)], (.scalar .int16)⟩
  , ⟨"lean_int16_dec_eq"             , "(prim2Op .lean_int16_dec_eq)", [(.scalar .int16), (.scalar .int16)], .bool⟩
  , ⟨"lean_int16_dec_le"             , "(prim2Op .lean_int16_dec_le)", [(.scalar .int16), (.scalar .int16)], .bool⟩
  , ⟨"lean_int16_dec_lt"             , "(prim2Op .lean_int16_dec_lt)", [(.scalar .int16), (.scalar .int16)], .bool⟩
  , ⟨"lean_int16_div"                , "(prim2Op .lean_int16_div)", [(.scalar .int16), (.scalar .int16)], (.scalar .int16)⟩
  , ⟨"lean_int16_land"               , "(prim2Op .lean_int16_land)", [(.scalar .int16), (.scalar .int16)], (.scalar .int16)⟩
  , ⟨"lean_int16_lor"                , "(prim2Op .lean_int16_lor)", [(.scalar .int16), (.scalar .int16)], (.scalar .int16)⟩
  , ⟨"lean_int16_mod"                , "(prim2Op .lean_int16_mod)", [(.scalar .int16), (.scalar .int16)], (.scalar .int16)⟩
  , ⟨"lean_int16_mul"                , "(prim2Op .lean_int16_mul)", [(.scalar .int16), (.scalar .int16)], (.scalar .int16)⟩
  , ⟨"lean_int16_neg"                , "(prim1Op .lean_int16_neg)", [(.scalar .int16)], (.scalar .int16)⟩
  , ⟨"lean_int16_of_int"             , "(prim1Op .lean_int16_of_int)", [.int], (.scalar .int16)⟩
  , ⟨"lean_int16_of_nat"             , "(prim1Op .lean_int16_of_nat)", [.nat], (.scalar .int16)⟩
  , ⟨"lean_int16_shift_left"         , "(prim2Op .lean_int16_shift_left)", [(.scalar .int16), (.scalar .int16)], (.scalar .int16)⟩
  , ⟨"lean_int16_shift_right"        , "(prim2Op .lean_int16_shift_right)", [(.scalar .int16), (.scalar .int16)], (.scalar .int16)⟩
  , ⟨"lean_int16_sub"                , "(prim2Op .lean_int16_sub)", [(.scalar .int16), (.scalar .int16)], (.scalar .int16)⟩
  , ⟨"lean_int16_to_float"           , "(prim1Op .lean_int16_to_float)", [(.scalar .int16)], (.scalar .float)⟩
  , ⟨"lean_int16_to_float32"         , "(prim1Op .lean_int16_to_float32)", [(.scalar .int16)], (.scalar .float32)⟩
  , ⟨"lean_int16_to_int"             , "(prim1Op .lean_int16_to_int)", [(.scalar .int16)], .int⟩
  , ⟨"lean_int16_to_int32"           , "(prim1Op .lean_int16_to_int32)", [(.scalar .int16)], (.scalar .int32)⟩
  , ⟨"lean_int16_to_int64"           , "(prim1Op .lean_int16_to_int64)", [(.scalar .int16)], (.scalar .int64)⟩
  , ⟨"lean_int16_to_int8"            , "(prim1Op .lean_int16_to_int8)", [(.scalar .int16)], (.scalar .int8)⟩
  , ⟨"lean_int16_to_isize"           , "(prim1Op .lean_int16_to_isize)", [(.scalar .int16)], (.scalar .int64)⟩
  , ⟨"lean_int16_xor"                , "(prim2Op .lean_int16_xor)", [(.scalar .int16), (.scalar .int16)], (.scalar .int16)⟩
  , ⟨"lean_int32_abs"                , "(prim1Op .lean_int32_abs)", [(.scalar .int32)], (.scalar .int32)⟩
  , ⟨"lean_int32_add"                , "(prim2Op .lean_int32_add)", [(.scalar .int32), (.scalar .int32)], (.scalar .int32)⟩
  , ⟨"lean_int32_complement"         , "(prim1Op .lean_int32_complement)", [(.scalar .int32)], (.scalar .int32)⟩
  , ⟨"lean_int32_dec_eq"             , "(prim2Op .lean_int32_dec_eq)", [(.scalar .int32), (.scalar .int32)], .bool⟩
  , ⟨"lean_int32_dec_le"             , "(prim2Op .lean_int32_dec_le)", [(.scalar .int32), (.scalar .int32)], .bool⟩
  , ⟨"lean_int32_dec_lt"             , "(prim2Op .lean_int32_dec_lt)", [(.scalar .int32), (.scalar .int32)], .bool⟩
  , ⟨"lean_int32_div"                , "(prim2Op .lean_int32_div)", [(.scalar .int32), (.scalar .int32)], (.scalar .int32)⟩
  , ⟨"lean_int32_land"               , "(prim2Op .lean_int32_land)", [(.scalar .int32), (.scalar .int32)], (.scalar .int32)⟩
  , ⟨"lean_int32_lor"                , "(prim2Op .lean_int32_lor)", [(.scalar .int32), (.scalar .int32)], (.scalar .int32)⟩
  , ⟨"lean_int32_mod"                , "(prim2Op .lean_int32_mod)", [(.scalar .int32), (.scalar .int32)], (.scalar .int32)⟩
  , ⟨"lean_int32_mul"                , "(prim2Op .lean_int32_mul)", [(.scalar .int32), (.scalar .int32)], (.scalar .int32)⟩
  , ⟨"lean_int32_neg"                , "(prim1Op .lean_int32_neg)", [(.scalar .int32)], (.scalar .int32)⟩
  , ⟨"lean_int32_of_int"             , "(prim1Op .lean_int32_of_int)", [.int], (.scalar .int32)⟩
  , ⟨"lean_int32_of_nat"             , "(prim1Op .lean_int32_of_nat)", [.nat], (.scalar .int32)⟩
  , ⟨"lean_int32_shift_left"         , "(prim2Op .lean_int32_shift_left)", [(.scalar .int32), (.scalar .int32)], (.scalar .int32)⟩
  , ⟨"lean_int32_shift_right"        , "(prim2Op .lean_int32_shift_right)", [(.scalar .int32), (.scalar .int32)], (.scalar .int32)⟩
  , ⟨"lean_int32_sub"                , "(prim2Op .lean_int32_sub)", [(.scalar .int32), (.scalar .int32)], (.scalar .int32)⟩
  , ⟨"lean_int32_to_float"           , "(prim1Op .lean_int32_to_float)", [(.scalar .int32)], (.scalar .float)⟩
  , ⟨"lean_int32_to_float32"         , "(prim1Op .lean_int32_to_float32)", [(.scalar .int32)], (.scalar .float32)⟩
  , ⟨"lean_int32_to_int"             , "(prim1Op .lean_int32_to_int)", [(.scalar .int32)], .int⟩
  , ⟨"lean_int32_to_int16"           , "(prim1Op .lean_int32_to_int16)", [(.scalar .int32)], (.scalar .int16)⟩
  , ⟨"lean_int32_to_int64"           , "(prim1Op .lean_int32_to_int64)", [(.scalar .int32)], (.scalar .int64)⟩
  , ⟨"lean_int32_to_int8"            , "(prim1Op .lean_int32_to_int8)", [(.scalar .int32)], (.scalar .int8)⟩
  , ⟨"lean_int32_to_isize"           , "(prim1Op .lean_int32_to_isize)", [(.scalar .int32)], (.scalar .int64)⟩
  , ⟨"lean_int32_xor"                , "(prim2Op .lean_int32_xor)", [(.scalar .int32), (.scalar .int32)], (.scalar .int32)⟩
  , ⟨"lean_int64_abs"                , "(prim1Op .lean_int64_abs)", [(.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_int64_add"                , "(prim2Op .lean_int64_add)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_int64_complement"         , "(prim1Op .lean_int64_complement)", [(.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_int64_dec_eq"             , "(prim2Op .lean_int64_dec_eq)", [(.scalar .int64), (.scalar .int64)], .bool⟩
  , ⟨"lean_int64_dec_le"             , "(prim2Op .lean_int64_dec_le)", [(.scalar .int64), (.scalar .int64)], .bool⟩
  , ⟨"lean_int64_dec_lt"             , "(prim2Op .lean_int64_dec_lt)", [(.scalar .int64), (.scalar .int64)], .bool⟩
  , ⟨"lean_int64_div"                , "(prim2Op .lean_int64_div)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_int64_land"               , "(prim2Op .lean_int64_land)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_int64_lor"                , "(prim2Op .lean_int64_lor)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_int64_mod"                , "(prim2Op .lean_int64_mod)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_int64_mul"                , "(prim2Op .lean_int64_mul)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_int64_neg"                , "(prim1Op .lean_int64_neg)", [(.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_int64_of_int"             , "(prim1Op .lean_int64_of_int)", [.int], (.scalar .int64)⟩
  , ⟨"lean_int64_of_nat"             , "(prim1Op .lean_int64_of_nat)", [.nat], (.scalar .int64)⟩
  , ⟨"lean_int64_shift_left"         , "(prim2Op .lean_int64_shift_left)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_int64_shift_right"        , "(prim2Op .lean_int64_shift_right)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_int64_sub"                , "(prim2Op .lean_int64_sub)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_int64_to_float"           , "(prim1Op .lean_int64_to_float)", [(.scalar .int64)], (.scalar .float)⟩
  , ⟨"lean_int64_to_float32"         , "(prim1Op .lean_int64_to_float32)", [(.scalar .int64)], (.scalar .float32)⟩
  , ⟨"lean_int64_to_int16"           , "(prim1Op .lean_int64_to_int16)", [(.scalar .int64)], (.scalar .int16)⟩
  , ⟨"lean_int64_to_int32"           , "(prim1Op .lean_int64_to_int32)", [(.scalar .int64)], (.scalar .int32)⟩
  , ⟨"lean_int64_to_int8"            , "(prim1Op .lean_int64_to_int8)", [(.scalar .int64)], (.scalar .int8)⟩
  , ⟨"lean_int64_to_int_sint"        , "(prim1Op .lean_int64_to_int_sint)", [(.scalar .int64)], .int⟩
  , ⟨"lean_int64_to_isize"           , "(prim1Op .lean_int64_to_isize)", [(.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_int64_xor"                , "(prim2Op .lean_int64_xor)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_int8_abs"                 , "(prim1Op .lean_int8_abs)", [(.scalar .int8)], (.scalar .int8)⟩
  , ⟨"lean_int8_add"                 , "(prim2Op .lean_int8_add)", [(.scalar .int8), (.scalar .int8)], (.scalar .int8)⟩
  , ⟨"lean_int8_complement"          , "(prim1Op .lean_int8_complement)", [(.scalar .int8)], (.scalar .int8)⟩
  , ⟨"lean_int8_dec_eq"              , "(prim2Op .lean_int8_dec_eq)", [(.scalar .int8), (.scalar .int8)], .bool⟩
  , ⟨"lean_int8_dec_le"              , "(prim2Op .lean_int8_dec_le)", [(.scalar .int8), (.scalar .int8)], .bool⟩
  , ⟨"lean_int8_dec_lt"              , "(prim2Op .lean_int8_dec_lt)", [(.scalar .int8), (.scalar .int8)], .bool⟩
  , ⟨"lean_int8_div"                 , "(prim2Op .lean_int8_div)", [(.scalar .int8), (.scalar .int8)], (.scalar .int8)⟩
  , ⟨"lean_int8_land"                , "(prim2Op .lean_int8_land)", [(.scalar .int8), (.scalar .int8)], (.scalar .int8)⟩
  , ⟨"lean_int8_lor"                 , "(prim2Op .lean_int8_lor)", [(.scalar .int8), (.scalar .int8)], (.scalar .int8)⟩
  , ⟨"lean_int8_mod"                 , "(prim2Op .lean_int8_mod)", [(.scalar .int8), (.scalar .int8)], (.scalar .int8)⟩
  , ⟨"lean_int8_mul"                 , "(prim2Op .lean_int8_mul)", [(.scalar .int8), (.scalar .int8)], (.scalar .int8)⟩
  , ⟨"lean_int8_neg"                 , "(prim1Op .lean_int8_neg)", [(.scalar .int8)], (.scalar .int8)⟩
  , ⟨"lean_int8_of_int"              , "(prim1Op .lean_int8_of_int)", [.int], (.scalar .int8)⟩
  , ⟨"lean_int8_of_nat"              , "(prim1Op .lean_int8_of_nat)", [.nat], (.scalar .int8)⟩
  , ⟨"lean_int8_shift_left"          , "(prim2Op .lean_int8_shift_left)", [(.scalar .int8), (.scalar .int8)], (.scalar .int8)⟩
  , ⟨"lean_int8_shift_right"         , "(prim2Op .lean_int8_shift_right)", [(.scalar .int8), (.scalar .int8)], (.scalar .int8)⟩
  , ⟨"lean_int8_sub"                 , "(prim2Op .lean_int8_sub)", [(.scalar .int8), (.scalar .int8)], (.scalar .int8)⟩
  , ⟨"lean_int8_to_float"            , "(prim1Op .lean_int8_to_float)", [(.scalar .int8)], (.scalar .float)⟩
  , ⟨"lean_int8_to_float32"          , "(prim1Op .lean_int8_to_float32)", [(.scalar .int8)], (.scalar .float32)⟩
  , ⟨"lean_int8_to_int"              , "(prim1Op .lean_int8_to_int)", [(.scalar .int8)], .int⟩
  , ⟨"lean_int8_to_int16"            , "(prim1Op .lean_int8_to_int16)", [(.scalar .int8)], (.scalar .int16)⟩
  , ⟨"lean_int8_to_int32"            , "(prim1Op .lean_int8_to_int32)", [(.scalar .int8)], (.scalar .int32)⟩
  , ⟨"lean_int8_to_int64"            , "(prim1Op .lean_int8_to_int64)", [(.scalar .int8)], (.scalar .int64)⟩
  , ⟨"lean_int8_to_isize"            , "(prim1Op .lean_int8_to_isize)", [(.scalar .int8)], (.scalar .int64)⟩
  , ⟨"lean_int8_xor"                 , "(prim2Op .lean_int8_xor)", [(.scalar .int8), (.scalar .int8)], (.scalar .int8)⟩
  , ⟨"lean_int_add"                  , "(prim2Op .lean_int_add)", [.int, .int], .int⟩
  , ⟨"lean_int_dec_eq"               , "(prim2Op .lean_int_dec_eq)", [.int, .int], .bool⟩
  , ⟨"lean_int_dec_le"               , "(prim2Op .lean_int_dec_le)", [.int, .int], .bool⟩
  , ⟨"lean_int_dec_lt"               , "(prim2Op .lean_int_dec_lt)", [.int, .int], .bool⟩
  , ⟨"lean_int_dec_nonneg"           , "(prim1Op .lean_int_dec_nonneg)", [.int], .bool⟩
  , ⟨"lean_int_div"                  , "(prim2Op .lean_int_div)", [.int, .int], .int⟩
  , ⟨"lean_int_div_exact"            , "(prim2Op .lean_int_div_exact)", [.int, .int], .int⟩
  , ⟨"lean_int_ediv"                 , "(prim2Op .lean_int_ediv)", [.int, .int], .int⟩
  , ⟨"lean_int_emod"                 , "(prim2Op .lean_int_emod)", [.int, .int], .int⟩
  , ⟨"lean_int_mod"                  , "(prim2Op .lean_int_mod)", [.int, .int], .int⟩
  , ⟨"lean_int_mul"                  , "(prim2Op .lean_int_mul)", [.int, .int], .int⟩
  , ⟨"lean_int_neg"                  , "(prim1Op .lean_int_neg)", [.int], .int⟩
  , ⟨"lean_int_neg_succ_of_nat"      , "(prim1Op .lean_int_neg_succ_of_nat)", [.nat], .int⟩
  , ⟨"lean_int_sub"                  , "(prim2Op .lean_int_sub)", [.int, .int], .int⟩
  , ⟨"lean_int_to_nat"               , "(prim1Op .lean_int_to_nat)", [.int], .nat⟩
  , ⟨"lean_isize_abs"                , "(prim1Op .lean_isize_abs)", [(.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_isize_add"                , "(prim2Op .lean_isize_add)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_isize_complement"         , "(prim1Op .lean_isize_complement)", [(.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_isize_dec_eq"             , "(prim2Op .lean_isize_dec_eq)", [(.scalar .int64), (.scalar .int64)], .bool⟩
  , ⟨"lean_isize_dec_le"             , "(prim2Op .lean_isize_dec_le)", [(.scalar .int64), (.scalar .int64)], .bool⟩
  , ⟨"lean_isize_dec_lt"             , "(prim2Op .lean_isize_dec_lt)", [(.scalar .int64), (.scalar .int64)], .bool⟩
  , ⟨"lean_isize_div"                , "(prim2Op .lean_isize_div)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_isize_land"               , "(prim2Op .lean_isize_land)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_isize_lor"                , "(prim2Op .lean_isize_lor)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_isize_mod"                , "(prim2Op .lean_isize_mod)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_isize_mul"                , "(prim2Op .lean_isize_mul)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_isize_neg"                , "(prim1Op .lean_isize_neg)", [(.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_isize_of_int"             , "(prim1Op .lean_isize_of_int)", [.int], (.scalar .int64)⟩
  , ⟨"lean_isize_of_nat"             , "(prim1Op .lean_isize_of_nat)", [.nat], (.scalar .int64)⟩
  , ⟨"lean_isize_shift_left"         , "(prim2Op .lean_isize_shift_left)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_isize_shift_right"        , "(prim2Op .lean_isize_shift_right)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_isize_sub"                , "(prim2Op .lean_isize_sub)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_isize_to_float"           , "(prim1Op .lean_isize_to_float)", [(.scalar .int64)], (.scalar .float)⟩
  , ⟨"lean_isize_to_float32"         , "(prim1Op .lean_isize_to_float32)", [(.scalar .int64)], (.scalar .float32)⟩
  , ⟨"lean_isize_to_int"             , "(prim1Op .lean_isize_to_int)", [(.scalar .int64)], .int⟩
  , ⟨"lean_isize_to_int16"           , "(prim1Op .lean_isize_to_int16)", [(.scalar .int64)], (.scalar .int16)⟩
  , ⟨"lean_isize_to_int32"           , "(prim1Op .lean_isize_to_int32)", [(.scalar .int64)], (.scalar .int32)⟩
  , ⟨"lean_isize_to_int64"           , "(prim1Op .lean_isize_to_int64)", [(.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_isize_to_int8"            , "(prim1Op .lean_isize_to_int8)", [(.scalar .int64)], (.scalar .int8)⟩
  , ⟨"lean_isize_xor"                , "(prim2Op .lean_isize_xor)", [(.scalar .int64), (.scalar .int64)], (.scalar .int64)⟩
  , ⟨"lean_nat_abs"                  , "(prim1Op .lean_nat_abs)", [.int], .nat⟩
  , ⟨"lean_nat_add"                  , "(prim2Op .lean_nat_add)", [.nat, .nat], .nat⟩
  , ⟨"lean_nat_beq"                  , "(prim2Op .lean_nat_beq)", [.nat, .nat], .bool⟩
  , ⟨"lean_nat_ble"                  , "(prim2Op .lean_nat_ble)", [.nat, .nat], .bool⟩
  , ⟨"lean_nat_dec_eq"               , "(prim2Op .lean_nat_dec_eq)", [.nat, .nat], .bool⟩
  , ⟨"lean_nat_dec_le"               , "(prim2Op .lean_nat_dec_le)", [.nat, .nat], .bool⟩
  , ⟨"lean_nat_dec_lt"               , "(prim2Op .lean_nat_dec_lt)", [.nat, .nat], .bool⟩
  , ⟨"lean_nat_div"                  , "(prim2Op .lean_nat_div)", [.nat, .nat], .nat⟩
  , ⟨"lean_nat_div_exact"            , "(prim2Op .lean_nat_div_exact)", [.nat, .nat], .nat⟩
  , ⟨"lean_nat_land"                 , "(prim2Op .lean_nat_land)", [.nat, .nat], .nat⟩
  , ⟨"lean_nat_log2"                 , "(prim1Op .lean_nat_log2)", [.nat], .nat⟩
  , ⟨"lean_nat_lor"                  , "(prim2Op .lean_nat_lor)", [.nat, .nat], .nat⟩
  , ⟨"lean_nat_lxor"                 , "(prim2Op .lean_nat_lxor)", [.nat, .nat], .nat⟩
  , ⟨"lean_nat_mod"                  , "(prim2Op .lean_nat_mod)", [.nat, .nat], .nat⟩
  , ⟨"lean_nat_mod_core"             , "(prim2Op .lean_nat_mod_core)", [.nat, .nat], .nat⟩
  , ⟨"lean_nat_mul"                  , "(prim2Op .lean_nat_mul)", [.nat, .nat], .nat⟩
  , ⟨"lean_nat_pow"                  , "(prim2Op .lean_nat_pow)", [.nat, .nat], .nat⟩
  , ⟨"lean_nat_pred"                 , "(prim1Op .lean_nat_pred)", [.nat], .nat⟩
  , ⟨"lean_nat_shiftl"               , "(prim2Op .lean_nat_shiftl)", [.nat, .nat], .nat⟩
  , ⟨"lean_nat_shiftr"               , "(prim2Op .lean_nat_shiftr)", [.nat, .nat], .nat⟩
  , ⟨"lean_nat_sub"                  , "(prim2Op .lean_nat_sub)", [.nat, .nat], .nat⟩
  , ⟨"lean_nat_to_int"               , "(prim1Op .lean_nat_to_int)", [.nat], .int⟩
  , ⟨"lean_strict_and"               , "(prim2Op .lean_strict_and)", [.bool, .bool], .bool⟩
  , ⟨"lean_strict_or"                , "(prim2Op .lean_strict_or)", [.bool, .bool], .bool⟩
  , ⟨"lean_string_append"            , "(prim2Op .lean_string_append)", [.string, .string], .string⟩
  , ⟨"lean_string_append_defs"       , "(prim2Op .lean_string_append_defs)", [.string, .string], .string⟩
  , ⟨"lean_string_capitalize"        , "(prim1Op .lean_string_capitalize)", [.string], .string⟩
  , ⟨"lean_string_contains"          , "(prim2Op .lean_string_contains)", [.string, .char], .bool⟩
  , ⟨"lean_string_dec_eq"            , "(prim2Op .lean_string_dec_eq)", [.string, .string], .bool⟩
  , ⟨"lean_string_dec_lt"            , "(prim2Op .lean_string_dec_lt)", [.string, .string], .bool⟩
  , ⟨"lean_string_decode_char"       , "(prim2Op .lean_string_decode_char)", [.string, .nat], .char⟩
  , ⟨"lean_string_drop"              , "(prim2Op .lean_string_drop)", [.string, .nat], .string⟩
  , ⟨"lean_string_dropright"         , "(prim2Op .lean_string_dropright)", [.string, .nat], .string⟩
  , ⟨"lean_string_front"             , "(prim1Op .lean_string_front)", [.string], .char⟩
  , ⟨"lean_string_get_byte_fast"     , "(prim2Op .lean_string_get_byte_fast)", [.string, .nat], (.scalar .uint8)⟩
  , ⟨"lean_string_hash"              , "(prim1Op .lean_string_hash)", [.string], (.scalar .uint64)⟩
  , ⟨"lean_string_isempty"           , "(prim1Op .lean_string_isempty)", [.string], .bool⟩
  , ⟨"lean_string_isprefixof"        , "(prim2Op .lean_string_isprefixof)", [.string, .string], .bool⟩
  , ⟨"lean_string_length"            , "(prim1Op .lean_string_length)", [.string], .nat⟩
  , ⟨"lean_string_length_def"        , "(prim1Op .lean_string_length_def)", [.string], .nat⟩
  , ⟨"lean_string_memcmp"            , "(prim5Op .lean_string_memcmp)", [.string, .string, .nat, .nat, .nat], .bool⟩
  , ⟨"lean_string_of_usize"          , "(prim1Op .lean_string_of_usize)", [(.scalar .uint64)], .string⟩
  , ⟨"lean_string_pos_raw_set"       , "(prim3Op .lean_string_pos_raw_set)", [.string, .nat, .char], .string⟩
  , ⟨"lean_string_pos_set"           , "(prim3Op .lean_string_pos_set)", [.string, .nat, .char], .string⟩
  , ⟨"lean_string_push"              , "(prim2Op .lean_string_push)", [.string, .char], .string⟩
  , ⟨"lean_string_pushn"             , "(prim3Op .lean_string_pushn)", [.string, .char, .nat], .string⟩
  , ⟨"lean_string_set"               , "(prim3Op .lean_string_set)", [.string, .nat, .char], .string⟩
  , ⟨"lean_string_trim"              , "(prim1Op .lean_string_trim)", [.string], .string⟩
  , ⟨"lean_string_uget_byte_fast"    , "(prim2Op .lean_string_uget_byte_fast)", [.string, (.scalar .uint64)], (.scalar .uint8)⟩
  , ⟨"lean_string_utf8_byte_size"    , "(prim1Op .lean_string_utf8_byte_size)", [.string], .nat⟩
  , ⟨"lean_string_utf8_extract"      , "(prim3Op .lean_string_utf8_extract)", [.string, .nat, .nat], .string⟩
  , ⟨"lean_string_utf8_extract_basic", "(prim3Op .lean_string_utf8_extract_basic)", [.string, .nat, .nat], .string⟩
  , ⟨"lean_string_utf8_extract_fast" , "(prim3Op .lean_string_utf8_extract_fast)", [.string, .nat, .nat], .string⟩
  , ⟨"lean_uint16_add"               , "(prim2Op .lean_uint16_add)", [(.scalar .uint16), (.scalar .uint16)], (.scalar .uint16)⟩
  , ⟨"lean_uint16_complement"        , "(prim1Op .lean_uint16_complement)", [(.scalar .uint16)], (.scalar .uint16)⟩
  , ⟨"lean_uint16_dec_eq"            , "(prim2Op .lean_uint16_dec_eq)", [(.scalar .uint16), (.scalar .uint16)], .bool⟩
  , ⟨"lean_uint16_dec_le"            , "(prim2Op .lean_uint16_dec_le)", [(.scalar .uint16), (.scalar .uint16)], .bool⟩
  , ⟨"lean_uint16_dec_lt"            , "(prim2Op .lean_uint16_dec_lt)", [(.scalar .uint16), (.scalar .uint16)], .bool⟩
  , ⟨"lean_uint16_div"               , "(prim2Op .lean_uint16_div)", [(.scalar .uint16), (.scalar .uint16)], (.scalar .uint16)⟩
  , ⟨"lean_uint16_land"              , "(prim2Op .lean_uint16_land)", [(.scalar .uint16), (.scalar .uint16)], (.scalar .uint16)⟩
  , ⟨"lean_uint16_log2"              , "(prim1Op .lean_uint16_log2)", [(.scalar .uint16)], (.scalar .uint16)⟩
  , ⟨"lean_uint16_lor"               , "(prim2Op .lean_uint16_lor)", [(.scalar .uint16), (.scalar .uint16)], (.scalar .uint16)⟩
  , ⟨"lean_uint16_mod"               , "(prim2Op .lean_uint16_mod)", [(.scalar .uint16), (.scalar .uint16)], (.scalar .uint16)⟩
  , ⟨"lean_uint16_mul"               , "(prim2Op .lean_uint16_mul)", [(.scalar .uint16), (.scalar .uint16)], (.scalar .uint16)⟩
  , ⟨"lean_uint16_neg"               , "(prim1Op .lean_uint16_neg)", [(.scalar .uint16)], (.scalar .uint16)⟩
  , ⟨"lean_uint16_of_nat"            , "(prim1Op .lean_uint16_of_nat)", [.nat], (.scalar .uint16)⟩
  , ⟨"lean_uint16_of_nat_lt"         , "(prim1Op .lean_uint16_of_nat_lt)", [.nat], (.scalar .uint16)⟩
  , ⟨"lean_uint16_shift_left"        , "(prim2Op .lean_uint16_shift_left)", [(.scalar .uint16), (.scalar .uint16)], (.scalar .uint16)⟩
  , ⟨"lean_uint16_shift_right"       , "(prim2Op .lean_uint16_shift_right)", [(.scalar .uint16), (.scalar .uint16)], (.scalar .uint16)⟩
  , ⟨"lean_uint16_sub"               , "(prim2Op .lean_uint16_sub)", [(.scalar .uint16), (.scalar .uint16)], (.scalar .uint16)⟩
  , ⟨"lean_uint16_to_float"          , "(prim1Op .lean_uint16_to_float)", [(.scalar .uint16)], (.scalar .float)⟩
  , ⟨"lean_uint16_to_float32"        , "(prim1Op .lean_uint16_to_float32)", [(.scalar .uint16)], (.scalar .float32)⟩
  , ⟨"lean_uint16_to_nat"            , "(prim1Op .lean_uint16_to_nat)", [(.scalar .uint16)], .nat⟩
  , ⟨"lean_uint16_to_uint32"         , "(prim1Op .lean_uint16_to_uint32)", [(.scalar .uint16)], (.scalar .uint32)⟩
  , ⟨"lean_uint16_to_uint64"         , "(prim1Op .lean_uint16_to_uint64)", [(.scalar .uint16)], (.scalar .uint64)⟩
  , ⟨"lean_uint16_to_uint8"          , "(prim1Op .lean_uint16_to_uint8)", [(.scalar .uint16)], (.scalar .uint8)⟩
  , ⟨"lean_uint16_to_usize"          , "(prim1Op .lean_uint16_to_usize)", [(.scalar .uint16)], (.scalar .uint64)⟩
  , ⟨"lean_uint16_xor"               , "(prim2Op .lean_uint16_xor)", [(.scalar .uint16), (.scalar .uint16)], (.scalar .uint16)⟩
  , ⟨"lean_uint32_add"               , "(prim2Op .lean_uint32_add)", [(.scalar .uint32), (.scalar .uint32)], (.scalar .uint32)⟩
  , ⟨"lean_uint32_complement"        , "(prim1Op .lean_uint32_complement)", [(.scalar .uint32)], (.scalar .uint32)⟩
  , ⟨"lean_uint32_dec_eq"            , "(prim2Op .lean_uint32_dec_eq)", [(.scalar .uint32), (.scalar .uint32)], .bool⟩
  , ⟨"lean_uint32_dec_le"            , "(prim2Op .lean_uint32_dec_le)", [(.scalar .uint32), (.scalar .uint32)], .bool⟩
  , ⟨"lean_uint32_dec_lt"            , "(prim2Op .lean_uint32_dec_lt)", [(.scalar .uint32), (.scalar .uint32)], .bool⟩
  , ⟨"lean_uint32_div"               , "(prim2Op .lean_uint32_div)", [(.scalar .uint32), (.scalar .uint32)], (.scalar .uint32)⟩
  , ⟨"lean_uint32_land"              , "(prim2Op .lean_uint32_land)", [(.scalar .uint32), (.scalar .uint32)], (.scalar .uint32)⟩
  , ⟨"lean_uint32_log2"              , "(prim1Op .lean_uint32_log2)", [(.scalar .uint32)], (.scalar .uint32)⟩
  , ⟨"lean_uint32_lor"               , "(prim2Op .lean_uint32_lor)", [(.scalar .uint32), (.scalar .uint32)], (.scalar .uint32)⟩
  , ⟨"lean_uint32_mod"               , "(prim2Op .lean_uint32_mod)", [(.scalar .uint32), (.scalar .uint32)], (.scalar .uint32)⟩
  , ⟨"lean_uint32_mul"               , "(prim2Op .lean_uint32_mul)", [(.scalar .uint32), (.scalar .uint32)], (.scalar .uint32)⟩
  , ⟨"lean_uint32_neg"               , "(prim1Op .lean_uint32_neg)", [(.scalar .uint32)], (.scalar .uint32)⟩
  , ⟨"lean_uint32_of_nat"            , "(prim1Op .lean_uint32_of_nat)", [.nat], (.scalar .uint32)⟩
  , ⟨"lean_uint32_of_nat_lt"         , "(prim1Op .lean_uint32_of_nat_lt)", [.nat], (.scalar .uint32)⟩
  , ⟨"lean_uint32_shift_left"        , "(prim2Op .lean_uint32_shift_left)", [(.scalar .uint32), (.scalar .uint32)], (.scalar .uint32)⟩
  , ⟨"lean_uint32_shift_right"       , "(prim2Op .lean_uint32_shift_right)", [(.scalar .uint32), (.scalar .uint32)], (.scalar .uint32)⟩
  , ⟨"lean_uint32_sub"               , "(prim2Op .lean_uint32_sub)", [(.scalar .uint32), (.scalar .uint32)], (.scalar .uint32)⟩
  , ⟨"lean_uint32_to_float"          , "(prim1Op .lean_uint32_to_float)", [(.scalar .uint32)], (.scalar .float)⟩
  , ⟨"lean_uint32_to_float32"        , "(prim1Op .lean_uint32_to_float32)", [(.scalar .uint32)], (.scalar .float32)⟩
  , ⟨"lean_uint32_to_nat"            , "(prim1Op .lean_uint32_to_nat)", [(.scalar .uint32)], .nat⟩
  , ⟨"lean_uint32_to_uint16"         , "(prim1Op .lean_uint32_to_uint16)", [(.scalar .uint32)], (.scalar .uint16)⟩
  , ⟨"lean_uint32_to_uint64"         , "(prim1Op .lean_uint32_to_uint64)", [(.scalar .uint32)], (.scalar .uint64)⟩
  , ⟨"lean_uint32_to_uint8"          , "(prim1Op .lean_uint32_to_uint8)", [(.scalar .uint32)], (.scalar .uint8)⟩
  , ⟨"lean_uint32_to_usize"          , "(prim1Op .lean_uint32_to_usize)", [(.scalar .uint32)], (.scalar .uint64)⟩
  , ⟨"lean_uint32_xor"               , "(prim2Op .lean_uint32_xor)", [(.scalar .uint32), (.scalar .uint32)], (.scalar .uint32)⟩
  , ⟨"lean_uint64_add"               , "(prim2Op .lean_uint64_add)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_uint64_complement"        , "(prim1Op .lean_uint64_complement)", [(.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_uint64_dec_eq"            , "(prim2Op .lean_uint64_dec_eq)", [(.scalar .uint64), (.scalar .uint64)], .bool⟩
  , ⟨"lean_uint64_dec_le"            , "(prim2Op .lean_uint64_dec_le)", [(.scalar .uint64), (.scalar .uint64)], .bool⟩
  , ⟨"lean_uint64_dec_lt"            , "(prim2Op .lean_uint64_dec_lt)", [(.scalar .uint64), (.scalar .uint64)], .bool⟩
  , ⟨"lean_uint64_div"               , "(prim2Op .lean_uint64_div)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_uint64_land"              , "(prim2Op .lean_uint64_land)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_uint64_log2"              , "(prim1Op .lean_uint64_log2)", [(.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_uint64_lor"               , "(prim2Op .lean_uint64_lor)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_uint64_mix_hash"          , "(prim2Op .lean_uint64_mix_hash)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_uint64_mod"               , "(prim2Op .lean_uint64_mod)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_uint64_mul"               , "(prim2Op .lean_uint64_mul)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_uint64_neg"               , "(prim1Op .lean_uint64_neg)", [(.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_uint64_of_nat"            , "(prim1Op .lean_uint64_of_nat)", [.nat], (.scalar .uint64)⟩
  , ⟨"lean_uint64_of_nat_lt"         , "(prim1Op .lean_uint64_of_nat_lt)", [.nat], (.scalar .uint64)⟩
  , ⟨"lean_uint64_shift_left"        , "(prim2Op .lean_uint64_shift_left)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_uint64_shift_right"       , "(prim2Op .lean_uint64_shift_right)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_uint64_sub"               , "(prim2Op .lean_uint64_sub)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_uint64_to_float"          , "(prim1Op .lean_uint64_to_float)", [(.scalar .uint64)], (.scalar .float)⟩
  , ⟨"lean_uint64_to_float32"        , "(prim1Op .lean_uint64_to_float32)", [(.scalar .uint64)], (.scalar .float32)⟩
  , ⟨"lean_uint64_to_nat"            , "(prim1Op .lean_uint64_to_nat)", [(.scalar .uint64)], .nat⟩
  , ⟨"lean_uint64_to_uint16"         , "(prim1Op .lean_uint64_to_uint16)", [(.scalar .uint64)], (.scalar .uint16)⟩
  , ⟨"lean_uint64_to_uint32"         , "(prim1Op .lean_uint64_to_uint32)", [(.scalar .uint64)], (.scalar .uint32)⟩
  , ⟨"lean_uint64_to_uint8"          , "(prim1Op .lean_uint64_to_uint8)", [(.scalar .uint64)], (.scalar .uint8)⟩
  , ⟨"lean_uint64_to_usize"          , "(prim1Op .lean_uint64_to_usize)", [(.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_uint64_xor"               , "(prim2Op .lean_uint64_xor)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_uint8_add"                , "(prim2Op .lean_uint8_add)", [(.scalar .uint8), (.scalar .uint8)], (.scalar .uint8)⟩
  , ⟨"lean_uint8_complement"         , "(prim1Op .lean_uint8_complement)", [(.scalar .uint8)], (.scalar .uint8)⟩
  , ⟨"lean_uint8_dec_eq"             , "(prim2Op .lean_uint8_dec_eq)", [(.scalar .uint8), (.scalar .uint8)], .bool⟩
  , ⟨"lean_uint8_dec_le"             , "(prim2Op .lean_uint8_dec_le)", [(.scalar .uint8), (.scalar .uint8)], .bool⟩
  , ⟨"lean_uint8_dec_lt"             , "(prim2Op .lean_uint8_dec_lt)", [(.scalar .uint8), (.scalar .uint8)], .bool⟩
  , ⟨"lean_uint8_div"                , "(prim2Op .lean_uint8_div)", [(.scalar .uint8), (.scalar .uint8)], (.scalar .uint8)⟩
  , ⟨"lean_uint8_land"               , "(prim2Op .lean_uint8_land)", [(.scalar .uint8), (.scalar .uint8)], (.scalar .uint8)⟩
  , ⟨"lean_uint8_log2"               , "(prim1Op .lean_uint8_log2)", [(.scalar .uint8)], (.scalar .uint8)⟩
  , ⟨"lean_uint8_lor"                , "(prim2Op .lean_uint8_lor)", [(.scalar .uint8), (.scalar .uint8)], (.scalar .uint8)⟩
  , ⟨"lean_uint8_mod"                , "(prim2Op .lean_uint8_mod)", [(.scalar .uint8), (.scalar .uint8)], (.scalar .uint8)⟩
  , ⟨"lean_uint8_mul"                , "(prim2Op .lean_uint8_mul)", [(.scalar .uint8), (.scalar .uint8)], (.scalar .uint8)⟩
  , ⟨"lean_uint8_neg"                , "(prim1Op .lean_uint8_neg)", [(.scalar .uint8)], (.scalar .uint8)⟩
  , ⟨"lean_uint8_of_nat"             , "(prim1Op .lean_uint8_of_nat)", [.nat], (.scalar .uint8)⟩
  , ⟨"lean_uint8_of_nat_lt"          , "(prim1Op .lean_uint8_of_nat_lt)", [.nat], (.scalar .uint8)⟩
  , ⟨"lean_uint8_shift_left"         , "(prim2Op .lean_uint8_shift_left)", [(.scalar .uint8), (.scalar .uint8)], (.scalar .uint8)⟩
  , ⟨"lean_uint8_shift_right"        , "(prim2Op .lean_uint8_shift_right)", [(.scalar .uint8), (.scalar .uint8)], (.scalar .uint8)⟩
  , ⟨"lean_uint8_sub"                , "(prim2Op .lean_uint8_sub)", [(.scalar .uint8), (.scalar .uint8)], (.scalar .uint8)⟩
  , ⟨"lean_uint8_to_float"           , "(prim1Op .lean_uint8_to_float)", [(.scalar .uint8)], (.scalar .float)⟩
  , ⟨"lean_uint8_to_float32"         , "(prim1Op .lean_uint8_to_float32)", [(.scalar .uint8)], (.scalar .float32)⟩
  , ⟨"lean_uint8_to_nat"             , "(prim1Op .lean_uint8_to_nat)", [(.scalar .uint8)], .nat⟩
  , ⟨"lean_uint8_to_uint16"          , "(prim1Op .lean_uint8_to_uint16)", [(.scalar .uint8)], (.scalar .uint16)⟩
  , ⟨"lean_uint8_to_uint32"          , "(prim1Op .lean_uint8_to_uint32)", [(.scalar .uint8)], (.scalar .uint32)⟩
  , ⟨"lean_uint8_to_uint64"          , "(prim1Op .lean_uint8_to_uint64)", [(.scalar .uint8)], (.scalar .uint64)⟩
  , ⟨"lean_uint8_to_usize"           , "(prim1Op .lean_uint8_to_usize)", [(.scalar .uint8)], (.scalar .uint64)⟩
  , ⟨"lean_uint8_xor"                , "(prim2Op .lean_uint8_xor)", [(.scalar .uint8), (.scalar .uint8)], (.scalar .uint8)⟩
  , ⟨"lean_usize_add"                , "(prim2Op .lean_usize_add)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_usize_complement"         , "(prim1Op .lean_usize_complement)", [(.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_usize_dec_eq"             , "(prim2Op .lean_usize_dec_eq)", [(.scalar .uint64), (.scalar .uint64)], .bool⟩
  , ⟨"lean_usize_dec_le"             , "(prim2Op .lean_usize_dec_le)", [(.scalar .uint64), (.scalar .uint64)], .bool⟩
  , ⟨"lean_usize_dec_lt"             , "(prim2Op .lean_usize_dec_lt)", [(.scalar .uint64), (.scalar .uint64)], .bool⟩
  , ⟨"lean_usize_div"                , "(prim2Op .lean_usize_div)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_usize_land"               , "(prim2Op .lean_usize_land)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_usize_log2"               , "(prim1Op .lean_usize_log2)", [(.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_usize_lor"                , "(prim2Op .lean_usize_lor)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_usize_mod"                , "(prim2Op .lean_usize_mod)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_usize_mul"                , "(prim2Op .lean_usize_mul)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_usize_neg"                , "(prim1Op .lean_usize_neg)", [(.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_usize_of_nat"             , "(prim1Op .lean_usize_of_nat)", [.nat], (.scalar .uint64)⟩
  , ⟨"lean_usize_of_nat32"           , "(prim1Op .lean_usize_of_nat32)", [.nat], (.scalar .uint64)⟩
  , ⟨"lean_usize_of_nat_lt"          , "(prim1Op .lean_usize_of_nat_lt)", [.nat], (.scalar .uint64)⟩
  , ⟨"lean_usize_shift_left"         , "(prim2Op .lean_usize_shift_left)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_usize_shift_right"        , "(prim2Op .lean_usize_shift_right)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_usize_sub"                , "(prim2Op .lean_usize_sub)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_usize_to_float"           , "(prim1Op .lean_usize_to_float)", [(.scalar .uint64)], (.scalar .float)⟩
  , ⟨"lean_usize_to_float32"         , "(prim1Op .lean_usize_to_float32)", [(.scalar .uint64)], (.scalar .float32)⟩
  , ⟨"lean_usize_to_nat"             , "(prim1Op .lean_usize_to_nat)", [(.scalar .uint64)], .nat⟩
  , ⟨"lean_usize_to_uint16"          , "(prim1Op .lean_usize_to_uint16)", [(.scalar .uint64)], (.scalar .uint16)⟩
  , ⟨"lean_usize_to_uint32"          , "(prim1Op .lean_usize_to_uint32)", [(.scalar .uint64)], (.scalar .uint32)⟩
  , ⟨"lean_usize_to_uint64"          , "(prim1Op .lean_usize_to_uint64)", [(.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"lean_usize_to_uint8"           , "(prim1Op .lean_usize_to_uint8)", [(.scalar .uint64)], (.scalar .uint8)⟩
  , ⟨"lean_usize_xor"                , "(prim2Op .lean_usize_xor)", [(.scalar .uint64), (.scalar .uint64)], (.scalar .uint64)⟩
  , ⟨"log"                           , "(prim1Op .log)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"log10"                         , "(prim1Op .log10)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"log10f"                        , "(prim1Op .log10f)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"log2"                          , "(prim1Op .log2)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"log2f"                         , "(prim1Op .log2f)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"logf"                          , "(prim1Op .logf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"pow"                           , "(prim2Op .pow)", [(.scalar .float), (.scalar .float)], (.scalar .float)⟩
  , ⟨"powf"                          , "(prim2Op .powf)", [(.scalar .float32), (.scalar .float32)], (.scalar .float32)⟩
  , ⟨"round"                         , "(prim1Op .round)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"roundf"                        , "(prim1Op .roundf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"sin"                           , "(prim1Op .sin)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"sinf"                          , "(prim1Op .sinf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"sinh"                          , "(prim1Op .sinh)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"sinhf"                         , "(prim1Op .sinhf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"sqrt"                          , "(prim1Op .sqrt)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"sqrtf"                         , "(prim1Op .sqrtf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"tan"                           , "(prim1Op .tan)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"tanf"                          , "(prim1Op .tanf)", [(.scalar .float32)], (.scalar .float32)⟩
  , ⟨"tanh"                          , "(prim1Op .tanh)", [(.scalar .float)], (.scalar .float)⟩
  , ⟨"tanhf"                         , "(prim1Op .tanhf)", [(.scalar .float32)], (.scalar .float32)⟩
  ]

/-- The row of the runtime function a C symbol names, if the catalogue has one whose
    types are types of the front end. -/
def primExternOf? (cname : String) : Option PrimExtern :=
  primExternTable.find? (·.cname == cname)

end LakeJs.FrontEnd
