-- Generated by `scripts/gen-primop-expectations.py`; do not edit by hand.
--
-- Prints, as JSON, what every export of `SnapshotsPBOPure/PrimOpIntBit01Configurable.lean` answers in
-- Lean: a constant as it stands, a function at the arguments the generator lists.  The
-- Node suites of the generated JavaScript read the result and check the module against
-- it — a configurable module has two of them (`-num.js` and `-bigint.js`) and a
-- non-configurable module one — so the expected answers are Lean's own and no answer is
-- written down by hand.
--
--     scripts/regen-primop-expectations.sh
import SnapshotsPBOPure.PrimOpIntBit01Configurable

/-- How an answer is written down: the same rendering the Node suites compute from the
    JavaScript value, so that the two can be compared as strings. -/
class Render (α : Type) where
  render : α → String

export Render (render)

instance : Render Nat := ⟨toString⟩
instance : Render UInt8 := ⟨fun a => toString a.toNat⟩
instance : Render UInt16 := ⟨fun a => toString a.toNat⟩
instance : Render UInt32 := ⟨fun a => toString a.toNat⟩
instance : Render Int8 := ⟨fun a => toString a.toInt⟩
instance : Render Int16 := ⟨fun a => toString a.toInt⟩
instance : Render Int32 := ⟨fun a => toString a.toInt⟩
instance : Render Int := ⟨toString⟩
instance : Render Bool := ⟨toString⟩
instance : Render UInt64 := ⟨fun a => toString a.toNat⟩
instance : Render USize := ⟨fun a => toString a.toNat⟩
instance : Render Int64 := ⟨fun a => toString a.toInt⟩
instance : Render ISize := ⟨fun a => toString a.toInt⟩
instance [Render α] : Render (Array α) :=
  ⟨fun xs => "[" ++ String.intercalate "," (xs.toList.map render) ++ "]"⟩

private def quote (s : String) : String := "\"" ++ s ++ "\""

/-- One call of an exported function, and what Lean answers. -/
private structure Call where
  fn : String
  args : List String
  expected : String

/-- One exported constant, and what Lean answers. -/
private structure Value where
  name : String
  expected : String

private def Call.toJson (c : Call) : String :=
  "{\"fn\": " ++ quote c.fn ++ ", \"args\": [" ++
    String.intercalate ", " (c.args.map quote) ++ "], \"expected\": " ++
    quote c.expected ++ "}"

private def Value.toJson (v : Value) : String :=
  "{\"name\": " ++ quote v.name ++ ", \"expected\": " ++ quote v.expected ++ "}"

private def calls : List Call :=
[
  ⟨"TestUInt64_land", ["1", "1"], render (TestUInt64.land (1) (1))⟩,
  ⟨"TestUInt64_land", ["7", "3"], render (TestUInt64.land (7) (3))⟩,
  ⟨"TestUInt64_land", ["255", "16"], render (TestUInt64.land (255) (16))⟩,
  ⟨"TestUInt64_land", ["5", "0"], render (TestUInt64.land (5) (0))⟩,
  ⟨"TestUInt64_land", ["1023", "2"], render (TestUInt64.land (1023) (2))⟩,
  ⟨"TestUInt64_lor", ["1", "1"], render (TestUInt64.lor (1) (1))⟩,
  ⟨"TestUInt64_lor", ["7", "3"], render (TestUInt64.lor (7) (3))⟩,
  ⟨"TestUInt64_lor", ["255", "16"], render (TestUInt64.lor (255) (16))⟩,
  ⟨"TestUInt64_lor", ["5", "0"], render (TestUInt64.lor (5) (0))⟩,
  ⟨"TestUInt64_lor", ["1023", "2"], render (TestUInt64.lor (1023) (2))⟩,
  ⟨"TestUInt64_shiftLeft", ["1", "1"], render (TestUInt64.shiftLeft (1) (1))⟩,
  ⟨"TestUInt64_shiftLeft", ["7", "3"], render (TestUInt64.shiftLeft (7) (3))⟩,
  ⟨"TestUInt64_shiftLeft", ["255", "16"], render (TestUInt64.shiftLeft (255) (16))⟩,
  ⟨"TestUInt64_shiftLeft", ["5", "0"], render (TestUInt64.shiftLeft (5) (0))⟩,
  ⟨"TestUInt64_shiftLeft", ["1023", "2"], render (TestUInt64.shiftLeft (1023) (2))⟩,
  ⟨"TestUInt64_shiftRight", ["1", "1"], render (TestUInt64.shiftRight (1) (1))⟩,
  ⟨"TestUInt64_shiftRight", ["7", "3"], render (TestUInt64.shiftRight (7) (3))⟩,
  ⟨"TestUInt64_shiftRight", ["255", "16"], render (TestUInt64.shiftRight (255) (16))⟩,
  ⟨"TestUInt64_shiftRight", ["5", "0"], render (TestUInt64.shiftRight (5) (0))⟩,
  ⟨"TestUInt64_shiftRight", ["1023", "2"], render (TestUInt64.shiftRight (1023) (2))⟩,
  ⟨"TestUInt64_xor", ["1", "1"], render (TestUInt64.xor (1) (1))⟩,
  ⟨"TestUInt64_xor", ["7", "3"], render (TestUInt64.xor (7) (3))⟩,
  ⟨"TestUInt64_xor", ["255", "16"], render (TestUInt64.xor (255) (16))⟩,
  ⟨"TestUInt64_xor", ["5", "0"], render (TestUInt64.xor (5) (0))⟩,
  ⟨"TestUInt64_xor", ["1023", "2"], render (TestUInt64.xor (1023) (2))⟩,
  ⟨"TestUInt64_complement", ["1"], render (TestUInt64.complement (1))⟩,
  ⟨"TestUInt64_complement", ["255"], render (TestUInt64.complement (255))⟩,
  ⟨"TestUInt64_complement", ["0"], render (TestUInt64.complement (0))⟩,
  ⟨"TestUSize_land", ["1", "1"], render (TestUSize.land (1) (1))⟩,
  ⟨"TestUSize_land", ["7", "3"], render (TestUSize.land (7) (3))⟩,
  ⟨"TestUSize_land", ["255", "16"], render (TestUSize.land (255) (16))⟩,
  ⟨"TestUSize_land", ["5", "0"], render (TestUSize.land (5) (0))⟩,
  ⟨"TestUSize_land", ["1023", "2"], render (TestUSize.land (1023) (2))⟩,
  ⟨"TestUSize_lor", ["1", "1"], render (TestUSize.lor (1) (1))⟩,
  ⟨"TestUSize_lor", ["7", "3"], render (TestUSize.lor (7) (3))⟩,
  ⟨"TestUSize_lor", ["255", "16"], render (TestUSize.lor (255) (16))⟩,
  ⟨"TestUSize_lor", ["5", "0"], render (TestUSize.lor (5) (0))⟩,
  ⟨"TestUSize_lor", ["1023", "2"], render (TestUSize.lor (1023) (2))⟩,
  ⟨"TestUSize_shiftLeft", ["1", "1"], render (TestUSize.shiftLeft (1) (1))⟩,
  ⟨"TestUSize_shiftLeft", ["7", "3"], render (TestUSize.shiftLeft (7) (3))⟩,
  ⟨"TestUSize_shiftLeft", ["255", "16"], render (TestUSize.shiftLeft (255) (16))⟩,
  ⟨"TestUSize_shiftLeft", ["5", "0"], render (TestUSize.shiftLeft (5) (0))⟩,
  ⟨"TestUSize_shiftLeft", ["1023", "2"], render (TestUSize.shiftLeft (1023) (2))⟩,
  ⟨"TestUSize_shiftRight", ["1", "1"], render (TestUSize.shiftRight (1) (1))⟩,
  ⟨"TestUSize_shiftRight", ["7", "3"], render (TestUSize.shiftRight (7) (3))⟩,
  ⟨"TestUSize_shiftRight", ["255", "16"], render (TestUSize.shiftRight (255) (16))⟩,
  ⟨"TestUSize_shiftRight", ["5", "0"], render (TestUSize.shiftRight (5) (0))⟩,
  ⟨"TestUSize_shiftRight", ["1023", "2"], render (TestUSize.shiftRight (1023) (2))⟩,
  ⟨"TestUSize_xor", ["1", "1"], render (TestUSize.xor (1) (1))⟩,
  ⟨"TestUSize_xor", ["7", "3"], render (TestUSize.xor (7) (3))⟩,
  ⟨"TestUSize_xor", ["255", "16"], render (TestUSize.xor (255) (16))⟩,
  ⟨"TestUSize_xor", ["5", "0"], render (TestUSize.xor (5) (0))⟩,
  ⟨"TestUSize_xor", ["1023", "2"], render (TestUSize.xor (1023) (2))⟩,
  ⟨"TestUSize_complement", ["1"], render (TestUSize.complement (1))⟩,
  ⟨"TestUSize_complement", ["255"], render (TestUSize.complement (255))⟩,
  ⟨"TestUSize_complement", ["0"], render (TestUSize.complement (0))⟩,
  ⟨"TestNat_land", ["10", "3"], render (TestNat.land (10) (3))⟩,
  ⟨"TestNat_land", ["0", "5"], render (TestNat.land (0) (5))⟩,
  ⟨"TestNat_land", ["7", "7"], render (TestNat.land (7) (7))⟩,
  ⟨"TestNat_land", ["5", "0"], render (TestNat.land (5) (0))⟩,
  ⟨"TestNat_land", ["1023", "2"], render (TestNat.land (1023) (2))⟩,
  ⟨"TestNat_lor", ["10", "3"], render (TestNat.lor (10) (3))⟩,
  ⟨"TestNat_lor", ["0", "5"], render (TestNat.lor (0) (5))⟩,
  ⟨"TestNat_lor", ["7", "7"], render (TestNat.lor (7) (7))⟩,
  ⟨"TestNat_lor", ["5", "0"], render (TestNat.lor (5) (0))⟩,
  ⟨"TestNat_lor", ["1023", "2"], render (TestNat.lor (1023) (2))⟩,
  ⟨"TestNat_shiftLeft", ["10", "3"], render (TestNat.shiftLeft (10) (3))⟩,
  ⟨"TestNat_shiftLeft", ["0", "5"], render (TestNat.shiftLeft (0) (5))⟩,
  ⟨"TestNat_shiftLeft", ["7", "7"], render (TestNat.shiftLeft (7) (7))⟩,
  ⟨"TestNat_shiftLeft", ["5", "0"], render (TestNat.shiftLeft (5) (0))⟩,
  ⟨"TestNat_shiftLeft", ["1023", "2"], render (TestNat.shiftLeft (1023) (2))⟩,
  ⟨"TestNat_shiftRight", ["10", "3"], render (TestNat.shiftRight (10) (3))⟩,
  ⟨"TestNat_shiftRight", ["0", "5"], render (TestNat.shiftRight (0) (5))⟩,
  ⟨"TestNat_shiftRight", ["7", "7"], render (TestNat.shiftRight (7) (7))⟩,
  ⟨"TestNat_shiftRight", ["5", "0"], render (TestNat.shiftRight (5) (0))⟩,
  ⟨"TestNat_shiftRight", ["1023", "2"], render (TestNat.shiftRight (1023) (2))⟩,
  ⟨"TestNat_xor", ["10", "3"], render (TestNat.xor (10) (3))⟩,
  ⟨"TestNat_xor", ["0", "5"], render (TestNat.xor (0) (5))⟩,
  ⟨"TestNat_xor", ["7", "7"], render (TestNat.xor (7) (7))⟩,
  ⟨"TestNat_xor", ["5", "0"], render (TestNat.xor (5) (0))⟩,
  ⟨"TestNat_xor", ["1023", "2"], render (TestNat.xor (1023) (2))⟩,
  ⟨"TestInt64_land", ["7", "3"], render (TestInt64.land (7) (3))⟩,
  ⟨"TestInt64_land", ["-7", "3"], render (TestInt64.land (-7) (3))⟩,
  ⟨"TestInt64_land", ["-8", "-3"], render (TestInt64.land (-8) (-3))⟩,
  ⟨"TestInt64_land", ["5", "0"], render (TestInt64.land (5) (0))⟩,
  ⟨"TestInt64_land", ["1023", "2"], render (TestInt64.land (1023) (2))⟩,
  ⟨"TestInt64_lor", ["7", "3"], render (TestInt64.lor (7) (3))⟩,
  ⟨"TestInt64_lor", ["-7", "3"], render (TestInt64.lor (-7) (3))⟩,
  ⟨"TestInt64_lor", ["-8", "-3"], render (TestInt64.lor (-8) (-3))⟩,
  ⟨"TestInt64_lor", ["5", "0"], render (TestInt64.lor (5) (0))⟩,
  ⟨"TestInt64_lor", ["1023", "2"], render (TestInt64.lor (1023) (2))⟩,
  ⟨"TestInt64_shiftLeft", ["7", "3"], render (TestInt64.shiftLeft (7) (3))⟩,
  ⟨"TestInt64_shiftLeft", ["-7", "3"], render (TestInt64.shiftLeft (-7) (3))⟩,
  ⟨"TestInt64_shiftLeft", ["-8", "-3"], render (TestInt64.shiftLeft (-8) (-3))⟩,
  ⟨"TestInt64_shiftLeft", ["5", "0"], render (TestInt64.shiftLeft (5) (0))⟩,
  ⟨"TestInt64_shiftLeft", ["1023", "2"], render (TestInt64.shiftLeft (1023) (2))⟩,
  ⟨"TestInt64_shiftRight", ["7", "3"], render (TestInt64.shiftRight (7) (3))⟩,
  ⟨"TestInt64_shiftRight", ["-7", "3"], render (TestInt64.shiftRight (-7) (3))⟩,
  ⟨"TestInt64_shiftRight", ["-8", "-3"], render (TestInt64.shiftRight (-8) (-3))⟩,
  ⟨"TestInt64_shiftRight", ["5", "0"], render (TestInt64.shiftRight (5) (0))⟩,
  ⟨"TestInt64_shiftRight", ["1023", "2"], render (TestInt64.shiftRight (1023) (2))⟩,
  ⟨"TestInt64_xor", ["7", "3"], render (TestInt64.xor (7) (3))⟩,
  ⟨"TestInt64_xor", ["-7", "3"], render (TestInt64.xor (-7) (3))⟩,
  ⟨"TestInt64_xor", ["-8", "-3"], render (TestInt64.xor (-8) (-3))⟩,
  ⟨"TestInt64_xor", ["5", "0"], render (TestInt64.xor (5) (0))⟩,
  ⟨"TestInt64_xor", ["1023", "2"], render (TestInt64.xor (1023) (2))⟩,
  ⟨"TestInt64_complement", ["1"], render (TestInt64.complement (1))⟩,
  ⟨"TestInt64_complement", ["-1"], render (TestInt64.complement (-1))⟩,
  ⟨"TestInt64_complement", ["0"], render (TestInt64.complement (0))⟩,
  ⟨"TestISize_land", ["7", "3"], render (TestISize.land (7) (3))⟩,
  ⟨"TestISize_land", ["-7", "3"], render (TestISize.land (-7) (3))⟩,
  ⟨"TestISize_land", ["-8", "-3"], render (TestISize.land (-8) (-3))⟩,
  ⟨"TestISize_land", ["5", "0"], render (TestISize.land (5) (0))⟩,
  ⟨"TestISize_land", ["1023", "2"], render (TestISize.land (1023) (2))⟩,
  ⟨"TestISize_lor", ["7", "3"], render (TestISize.lor (7) (3))⟩,
  ⟨"TestISize_lor", ["-7", "3"], render (TestISize.lor (-7) (3))⟩,
  ⟨"TestISize_lor", ["-8", "-3"], render (TestISize.lor (-8) (-3))⟩,
  ⟨"TestISize_lor", ["5", "0"], render (TestISize.lor (5) (0))⟩,
  ⟨"TestISize_lor", ["1023", "2"], render (TestISize.lor (1023) (2))⟩,
  ⟨"TestISize_shiftLeft", ["7", "3"], render (TestISize.shiftLeft (7) (3))⟩,
  ⟨"TestISize_shiftLeft", ["-7", "3"], render (TestISize.shiftLeft (-7) (3))⟩,
  ⟨"TestISize_shiftLeft", ["-8", "-3"], render (TestISize.shiftLeft (-8) (-3))⟩,
  ⟨"TestISize_shiftLeft", ["5", "0"], render (TestISize.shiftLeft (5) (0))⟩,
  ⟨"TestISize_shiftLeft", ["1023", "2"], render (TestISize.shiftLeft (1023) (2))⟩,
  ⟨"TestISize_shiftRight", ["7", "3"], render (TestISize.shiftRight (7) (3))⟩,
  ⟨"TestISize_shiftRight", ["-7", "3"], render (TestISize.shiftRight (-7) (3))⟩,
  ⟨"TestISize_shiftRight", ["-8", "-3"], render (TestISize.shiftRight (-8) (-3))⟩,
  ⟨"TestISize_shiftRight", ["5", "0"], render (TestISize.shiftRight (5) (0))⟩,
  ⟨"TestISize_shiftRight", ["1023", "2"], render (TestISize.shiftRight (1023) (2))⟩,
  ⟨"TestISize_xor", ["7", "3"], render (TestISize.xor (7) (3))⟩,
  ⟨"TestISize_xor", ["-7", "3"], render (TestISize.xor (-7) (3))⟩,
  ⟨"TestISize_xor", ["-8", "-3"], render (TestISize.xor (-8) (-3))⟩,
  ⟨"TestISize_xor", ["5", "0"], render (TestISize.xor (5) (0))⟩,
  ⟨"TestISize_xor", ["1023", "2"], render (TestISize.xor (1023) (2))⟩,
  ⟨"TestISize_complement", ["1"], render (TestISize.complement (1))⟩,
  ⟨"TestISize_complement", ["-1"], render (TestISize.complement (-1))⟩,
  ⟨"TestISize_complement", ["0"], render (TestISize.complement (0))⟩,
  ⟨"TestInt_complement", ["1"], render (TestInt.complement (1))⟩,
  ⟨"TestInt_complement", ["-1"], render (TestInt.complement (-1))⟩,
  ⟨"TestInt_complement", ["0"], render (TestInt.complement (0))⟩
]

private def values : List Value :=
[

]

def main : IO Unit := do
  IO.println "{"
  IO.println ("  \"calls\": [" ++
    (if calls.isEmpty then "],"
     else "\n" ++ String.intercalate ",\n" (calls.map fun c => "    " ++ c.toJson) ++
       "\n  ],"))
  IO.println ("  \"values\": [" ++
    (if values.isEmpty then "]"
     else "\n" ++ String.intercalate ",\n" (values.map fun v => "    " ++ v.toJson) ++
       "\n  ]"))
  IO.println "}"
