-- Generated by `scripts/gen-primop-expectations.py`; do not edit by hand.
--
-- Prints, as JSON, what every export of `SnapshotsPBOPure/PrimOpBitVec01Configurable.lean` answers in
-- Lean: a constant as it stands, a function at the arguments the generator lists.  The
-- Node suites of the generated JavaScript read the result and check the module against
-- it — a configurable module has two of them (`-num.js` and `-bigint.js`) and a
-- non-configurable module one — so the expected answers are Lean's own and no answer is
-- written down by hand.
--
--     scripts/regen-primop-expectations.sh
import SnapshotsPBOPure.PrimOpBitVec01Configurable

/-- How an answer is written down: the same rendering the Node suites compute from the
    JavaScript value, so that the two can be compared as strings. -/
class Render (α : Type) where
  render : α → String

export Render (render)

instance : Render Nat := ⟨toString⟩
instance : Render UInt8 := ⟨fun a => toString a.toNat⟩
instance : Render UInt16 := ⟨fun a => toString a.toNat⟩
instance : Render UInt32 := ⟨fun a => toString a.toNat⟩
instance : Render Int8 := ⟨fun a => toString a.toInt⟩
instance : Render Int16 := ⟨fun a => toString a.toInt⟩
instance : Render Int32 := ⟨fun a => toString a.toInt⟩
instance : Render Int := ⟨toString⟩
instance : Render Bool := ⟨toString⟩
instance : Render UInt64 := ⟨fun a => toString a.toNat⟩
instance : Render USize := ⟨fun a => toString a.toNat⟩
instance : Render Int64 := ⟨fun a => toString a.toInt⟩
instance : Render ISize := ⟨fun a => toString a.toInt⟩
instance {w : Nat} : Render (BitVec w) := ⟨fun a => toString a.toNat⟩
instance [Render α] : Render (Array α) :=
  ⟨fun xs => "[" ++ String.intercalate "," (xs.toList.map render) ++ "]"⟩

private def quote (s : String) : String := "\"" ++ s ++ "\""

/-- One call of an exported function, and what Lean answers. -/
private structure Call where
  fn : String
  args : List String
  expected : String

/-- One exported constant, and what Lean answers. -/
private structure Value where
  name : String
  expected : String

private def Call.toJson (c : Call) : String :=
  "{\"fn\": " ++ quote c.fn ++ ", \"args\": [" ++
    String.intercalate ", " (c.args.map quote) ++ "], \"expected\": " ++
    quote c.expected ++ "}"

private def Value.toJson (v : Value) : String :=
  "{\"name\": " ++ quote v.name ++ ", \"expected\": " ++ quote v.expected ++ "}"

private def calls : List Call :=
[
  ⟨"TestBitVec32_add", ["1", "1"], render (TestBitVec32.add (1) (1))⟩,
  ⟨"TestBitVec32_add", ["7", "3"], render (TestBitVec32.add (7) (3))⟩,
  ⟨"TestBitVec32_add", ["255", "16"], render (TestBitVec32.add (255) (16))⟩,
  ⟨"TestBitVec32_add", ["5", "0"], render (TestBitVec32.add (5) (0))⟩,
  ⟨"TestBitVec32_add", ["1023", "2"], render (TestBitVec32.add (1023) (2))⟩,
  ⟨"TestBitVec32_sub", ["1", "1"], render (TestBitVec32.sub (1) (1))⟩,
  ⟨"TestBitVec32_sub", ["7", "3"], render (TestBitVec32.sub (7) (3))⟩,
  ⟨"TestBitVec32_sub", ["255", "16"], render (TestBitVec32.sub (255) (16))⟩,
  ⟨"TestBitVec32_sub", ["5", "0"], render (TestBitVec32.sub (5) (0))⟩,
  ⟨"TestBitVec32_sub", ["1023", "2"], render (TestBitVec32.sub (1023) (2))⟩,
  ⟨"TestBitVec32_eq", ["1", "1"], render (TestBitVec32.eq (1) (1))⟩,
  ⟨"TestBitVec32_eq", ["7", "3"], render (TestBitVec32.eq (7) (3))⟩,
  ⟨"TestBitVec32_eq", ["255", "16"], render (TestBitVec32.eq (255) (16))⟩,
  ⟨"TestBitVec32_eq", ["5", "0"], render (TestBitVec32.eq (5) (0))⟩,
  ⟨"TestBitVec32_eq", ["1023", "2"], render (TestBitVec32.eq (1023) (2))⟩,
  ⟨"TestBitVec32_ne", ["1", "1"], render (TestBitVec32.ne (1) (1))⟩,
  ⟨"TestBitVec32_ne", ["7", "3"], render (TestBitVec32.ne (7) (3))⟩,
  ⟨"TestBitVec32_ne", ["255", "16"], render (TestBitVec32.ne (255) (16))⟩,
  ⟨"TestBitVec32_ne", ["5", "0"], render (TestBitVec32.ne (5) (0))⟩,
  ⟨"TestBitVec32_ne", ["1023", "2"], render (TestBitVec32.ne (1023) (2))⟩,
  ⟨"TestBitVec32_lt", ["1", "1"], render (TestBitVec32.lt (1) (1))⟩,
  ⟨"TestBitVec32_lt", ["7", "3"], render (TestBitVec32.lt (7) (3))⟩,
  ⟨"TestBitVec32_lt", ["255", "16"], render (TestBitVec32.lt (255) (16))⟩,
  ⟨"TestBitVec32_lt", ["5", "0"], render (TestBitVec32.lt (5) (0))⟩,
  ⟨"TestBitVec32_lt", ["1023", "2"], render (TestBitVec32.lt (1023) (2))⟩,
  ⟨"TestBitVec32_gt", ["1", "1"], render (TestBitVec32.gt (1) (1))⟩,
  ⟨"TestBitVec32_gt", ["7", "3"], render (TestBitVec32.gt (7) (3))⟩,
  ⟨"TestBitVec32_gt", ["255", "16"], render (TestBitVec32.gt (255) (16))⟩,
  ⟨"TestBitVec32_gt", ["5", "0"], render (TestBitVec32.gt (5) (0))⟩,
  ⟨"TestBitVec32_gt", ["1023", "2"], render (TestBitVec32.gt (1023) (2))⟩,
  ⟨"TestBitVec32_le", ["1", "1"], render (TestBitVec32.le (1) (1))⟩,
  ⟨"TestBitVec32_le", ["7", "3"], render (TestBitVec32.le (7) (3))⟩,
  ⟨"TestBitVec32_le", ["255", "16"], render (TestBitVec32.le (255) (16))⟩,
  ⟨"TestBitVec32_le", ["5", "0"], render (TestBitVec32.le (5) (0))⟩,
  ⟨"TestBitVec32_le", ["1023", "2"], render (TestBitVec32.le (1023) (2))⟩,
  ⟨"TestBitVec32_ge", ["1", "1"], render (TestBitVec32.ge (1) (1))⟩,
  ⟨"TestBitVec32_ge", ["7", "3"], render (TestBitVec32.ge (7) (3))⟩,
  ⟨"TestBitVec32_ge", ["255", "16"], render (TestBitVec32.ge (255) (16))⟩,
  ⟨"TestBitVec32_ge", ["5", "0"], render (TestBitVec32.ge (5) (0))⟩,
  ⟨"TestBitVec32_ge", ["1023", "2"], render (TestBitVec32.ge (1023) (2))⟩,
  ⟨"TestBitVec32_mul", ["1", "1"], render (TestBitVec32.mul (1) (1))⟩,
  ⟨"TestBitVec32_mul", ["7", "3"], render (TestBitVec32.mul (7) (3))⟩,
  ⟨"TestBitVec32_mul", ["255", "16"], render (TestBitVec32.mul (255) (16))⟩,
  ⟨"TestBitVec32_mul", ["5", "0"], render (TestBitVec32.mul (5) (0))⟩,
  ⟨"TestBitVec32_mul", ["1023", "2"], render (TestBitVec32.mul (1023) (2))⟩,
  ⟨"TestBitVec32_div", ["1", "1"], render (TestBitVec32.div (1) (1))⟩,
  ⟨"TestBitVec32_div", ["7", "3"], render (TestBitVec32.div (7) (3))⟩,
  ⟨"TestBitVec32_div", ["255", "16"], render (TestBitVec32.div (255) (16))⟩,
  ⟨"TestBitVec32_div", ["5", "0"], render (TestBitVec32.div (5) (0))⟩,
  ⟨"TestBitVec32_div", ["1023", "2"], render (TestBitVec32.div (1023) (2))⟩,
  ⟨"TestBitVec32_neg", ["1"], render (TestBitVec32.neg (1))⟩,
  ⟨"TestBitVec32_neg", ["255"], render (TestBitVec32.neg (255))⟩,
  ⟨"TestBitVec32_neg", ["0"], render (TestBitVec32.neg (0))⟩,
  ⟨"TestBitVec64_add", ["1", "1"], render (TestBitVec64.add (1) (1))⟩,
  ⟨"TestBitVec64_add", ["7", "3"], render (TestBitVec64.add (7) (3))⟩,
  ⟨"TestBitVec64_add", ["255", "16"], render (TestBitVec64.add (255) (16))⟩,
  ⟨"TestBitVec64_add", ["5", "0"], render (TestBitVec64.add (5) (0))⟩,
  ⟨"TestBitVec64_add", ["1023", "2"], render (TestBitVec64.add (1023) (2))⟩,
  ⟨"TestBitVec64_sub", ["1", "1"], render (TestBitVec64.sub (1) (1))⟩,
  ⟨"TestBitVec64_sub", ["7", "3"], render (TestBitVec64.sub (7) (3))⟩,
  ⟨"TestBitVec64_sub", ["255", "16"], render (TestBitVec64.sub (255) (16))⟩,
  ⟨"TestBitVec64_sub", ["5", "0"], render (TestBitVec64.sub (5) (0))⟩,
  ⟨"TestBitVec64_sub", ["1023", "2"], render (TestBitVec64.sub (1023) (2))⟩,
  ⟨"TestBitVec64_eq", ["1", "1"], render (TestBitVec64.eq (1) (1))⟩,
  ⟨"TestBitVec64_eq", ["7", "3"], render (TestBitVec64.eq (7) (3))⟩,
  ⟨"TestBitVec64_eq", ["255", "16"], render (TestBitVec64.eq (255) (16))⟩,
  ⟨"TestBitVec64_eq", ["5", "0"], render (TestBitVec64.eq (5) (0))⟩,
  ⟨"TestBitVec64_eq", ["1023", "2"], render (TestBitVec64.eq (1023) (2))⟩,
  ⟨"TestBitVec64_ne", ["1", "1"], render (TestBitVec64.ne (1) (1))⟩,
  ⟨"TestBitVec64_ne", ["7", "3"], render (TestBitVec64.ne (7) (3))⟩,
  ⟨"TestBitVec64_ne", ["255", "16"], render (TestBitVec64.ne (255) (16))⟩,
  ⟨"TestBitVec64_ne", ["5", "0"], render (TestBitVec64.ne (5) (0))⟩,
  ⟨"TestBitVec64_ne", ["1023", "2"], render (TestBitVec64.ne (1023) (2))⟩,
  ⟨"TestBitVec64_lt", ["1", "1"], render (TestBitVec64.lt (1) (1))⟩,
  ⟨"TestBitVec64_lt", ["7", "3"], render (TestBitVec64.lt (7) (3))⟩,
  ⟨"TestBitVec64_lt", ["255", "16"], render (TestBitVec64.lt (255) (16))⟩,
  ⟨"TestBitVec64_lt", ["5", "0"], render (TestBitVec64.lt (5) (0))⟩,
  ⟨"TestBitVec64_lt", ["1023", "2"], render (TestBitVec64.lt (1023) (2))⟩,
  ⟨"TestBitVec64_gt", ["1", "1"], render (TestBitVec64.gt (1) (1))⟩,
  ⟨"TestBitVec64_gt", ["7", "3"], render (TestBitVec64.gt (7) (3))⟩,
  ⟨"TestBitVec64_gt", ["255", "16"], render (TestBitVec64.gt (255) (16))⟩,
  ⟨"TestBitVec64_gt", ["5", "0"], render (TestBitVec64.gt (5) (0))⟩,
  ⟨"TestBitVec64_gt", ["1023", "2"], render (TestBitVec64.gt (1023) (2))⟩,
  ⟨"TestBitVec64_le", ["1", "1"], render (TestBitVec64.le (1) (1))⟩,
  ⟨"TestBitVec64_le", ["7", "3"], render (TestBitVec64.le (7) (3))⟩,
  ⟨"TestBitVec64_le", ["255", "16"], render (TestBitVec64.le (255) (16))⟩,
  ⟨"TestBitVec64_le", ["5", "0"], render (TestBitVec64.le (5) (0))⟩,
  ⟨"TestBitVec64_le", ["1023", "2"], render (TestBitVec64.le (1023) (2))⟩,
  ⟨"TestBitVec64_ge", ["1", "1"], render (TestBitVec64.ge (1) (1))⟩,
  ⟨"TestBitVec64_ge", ["7", "3"], render (TestBitVec64.ge (7) (3))⟩,
  ⟨"TestBitVec64_ge", ["255", "16"], render (TestBitVec64.ge (255) (16))⟩,
  ⟨"TestBitVec64_ge", ["5", "0"], render (TestBitVec64.ge (5) (0))⟩,
  ⟨"TestBitVec64_ge", ["1023", "2"], render (TestBitVec64.ge (1023) (2))⟩,
  ⟨"TestBitVec64_mul", ["1", "1"], render (TestBitVec64.mul (1) (1))⟩,
  ⟨"TestBitVec64_mul", ["7", "3"], render (TestBitVec64.mul (7) (3))⟩,
  ⟨"TestBitVec64_mul", ["255", "16"], render (TestBitVec64.mul (255) (16))⟩,
  ⟨"TestBitVec64_mul", ["5", "0"], render (TestBitVec64.mul (5) (0))⟩,
  ⟨"TestBitVec64_mul", ["1023", "2"], render (TestBitVec64.mul (1023) (2))⟩,
  ⟨"TestBitVec64_div", ["1", "1"], render (TestBitVec64.div (1) (1))⟩,
  ⟨"TestBitVec64_div", ["7", "3"], render (TestBitVec64.div (7) (3))⟩,
  ⟨"TestBitVec64_div", ["255", "16"], render (TestBitVec64.div (255) (16))⟩,
  ⟨"TestBitVec64_div", ["5", "0"], render (TestBitVec64.div (5) (0))⟩,
  ⟨"TestBitVec64_div", ["1023", "2"], render (TestBitVec64.div (1023) (2))⟩,
  ⟨"TestBitVec64_neg", ["1"], render (TestBitVec64.neg (1))⟩,
  ⟨"TestBitVec64_neg", ["255"], render (TestBitVec64.neg (255))⟩,
  ⟨"TestBitVec64_neg", ["0"], render (TestBitVec64.neg (0))⟩
]

private def values : List Value :=
[

]

def main : IO Unit := do
  IO.println "{"
  IO.println ("  \"calls\": [" ++
    (if calls.isEmpty then "],"
     else "\n" ++ String.intercalate ",\n" (calls.map fun c => "    " ++ c.toJson) ++
       "\n  ],"))
  IO.println ("  \"values\": [" ++
    (if values.isEmpty then "]"
     else "\n" ++ String.intercalate ",\n" (values.map fun v => "    " ++ v.toJson) ++
       "\n  ]"))
  IO.println "}"
