-- Generated by `scripts/gen-primop-expectations.py`; do not edit by hand.
--
-- Prints, as JSON, what every export of `SnapshotsPBOPure/PrimOpIntBit02NonConfigurable.lean` answers in
-- Lean: a constant as it stands, a function at the arguments the generator lists.  The
-- Node suites of the generated JavaScript read the result and check the module against
-- it — a configurable module has two of them (`-num.js` and `-bigint.js`) and a
-- non-configurable module one — so the expected answers are Lean's own and no answer is
-- written down by hand.
--
--     scripts/regen-primop-expectations.sh
import SnapshotsPBOPure.PrimOpIntBit02NonConfigurable

/-- How an answer is written down: the same rendering the Node suites compute from the
    JavaScript value, so that the two can be compared as strings. -/
class Render (α : Type) where
  render : α → String

export Render (render)

instance : Render Nat := ⟨toString⟩
instance : Render UInt8 := ⟨fun a => toString a.toNat⟩
instance : Render UInt16 := ⟨fun a => toString a.toNat⟩
instance : Render UInt32 := ⟨fun a => toString a.toNat⟩
instance : Render Int8 := ⟨fun a => toString a.toInt⟩
instance : Render Int16 := ⟨fun a => toString a.toInt⟩
instance : Render Int32 := ⟨fun a => toString a.toInt⟩
instance : Render Int := ⟨toString⟩
instance : Render Bool := ⟨toString⟩
instance : Render UInt64 := ⟨fun a => toString a.toNat⟩
instance : Render USize := ⟨fun a => toString a.toNat⟩
instance : Render Int64 := ⟨fun a => toString a.toInt⟩
instance : Render ISize := ⟨fun a => toString a.toInt⟩
instance [Render α] : Render (Array α) :=
  ⟨fun xs => "[" ++ String.intercalate "," (xs.toList.map render) ++ "]"⟩

private def quote (s : String) : String := "\"" ++ s ++ "\""

/-- One call of an exported function, and what Lean answers. -/
private structure Call where
  fn : String
  args : List String
  expected : String

/-- One exported constant, and what Lean answers. -/
private structure Value where
  name : String
  expected : String

private def Call.toJson (c : Call) : String :=
  "{\"fn\": " ++ quote c.fn ++ ", \"args\": [" ++
    String.intercalate ", " (c.args.map quote) ++ "], \"expected\": " ++
    quote c.expected ++ "}"

private def Value.toJson (v : Value) : String :=
  "{\"name\": " ++ quote v.name ++ ", \"expected\": " ++ quote v.expected ++ "}"

private def calls : List Call :=
[

]

private def values : List Value :=
[
  ⟨"TestUInt8_land", render (TestUInt8.land)⟩,
  ⟨"TestUInt8_lor", render (TestUInt8.lor)⟩,
  ⟨"TestUInt8_shiftLeft", render (TestUInt8.shiftLeft)⟩,
  ⟨"TestUInt8_shiftRight", render (TestUInt8.shiftRight)⟩,
  ⟨"TestUInt8_xor", render (TestUInt8.xor)⟩,
  ⟨"TestUInt8_complement", render (TestUInt8.complement)⟩,
  ⟨"TestUInt16_land", render (TestUInt16.land)⟩,
  ⟨"TestUInt16_lor", render (TestUInt16.lor)⟩,
  ⟨"TestUInt16_shiftLeft", render (TestUInt16.shiftLeft)⟩,
  ⟨"TestUInt16_shiftRight", render (TestUInt16.shiftRight)⟩,
  ⟨"TestUInt16_xor", render (TestUInt16.xor)⟩,
  ⟨"TestUInt16_complement", render (TestUInt16.complement)⟩,
  ⟨"TestUInt32_land", render (TestUInt32.land)⟩,
  ⟨"TestUInt32_lor", render (TestUInt32.lor)⟩,
  ⟨"TestUInt32_shiftLeft", render (TestUInt32.shiftLeft)⟩,
  ⟨"TestUInt32_shiftRight", render (TestUInt32.shiftRight)⟩,
  ⟨"TestUInt32_xor", render (TestUInt32.xor)⟩,
  ⟨"TestUInt32_complement", render (TestUInt32.complement)⟩,
  ⟨"TestInt8_land", render (TestInt8.land)⟩,
  ⟨"TestInt8_lor", render (TestInt8.lor)⟩,
  ⟨"TestInt8_shiftLeft", render (TestInt8.shiftLeft)⟩,
  ⟨"TestInt8_shiftRight", render (TestInt8.shiftRight)⟩,
  ⟨"TestInt8_xor", render (TestInt8.xor)⟩,
  ⟨"TestInt8_complement", render (TestInt8.complement)⟩,
  ⟨"TestInt16_land", render (TestInt16.land)⟩,
  ⟨"TestInt16_lor", render (TestInt16.lor)⟩,
  ⟨"TestInt16_shiftLeft", render (TestInt16.shiftLeft)⟩,
  ⟨"TestInt16_shiftRight", render (TestInt16.shiftRight)⟩,
  ⟨"TestInt16_xor", render (TestInt16.xor)⟩,
  ⟨"TestInt16_complement", render (TestInt16.complement)⟩,
  ⟨"TestInt32_land", render (TestInt32.land)⟩,
  ⟨"TestInt32_lor", render (TestInt32.lor)⟩,
  ⟨"TestInt32_shiftLeft", render (TestInt32.shiftLeft)⟩,
  ⟨"TestInt32_shiftRight", render (TestInt32.shiftRight)⟩,
  ⟨"TestInt32_xor", render (TestInt32.xor)⟩,
  ⟨"TestInt32_complement", render (TestInt32.complement)⟩
]

def main : IO Unit := do
  IO.println "{"
  IO.println ("  \"calls\": [" ++
    (if calls.isEmpty then "],"
     else "\n" ++ String.intercalate ",\n" (calls.map fun c => "    " ++ c.toJson) ++
       "\n  ],"))
  IO.println ("  \"values\": [" ++
    (if values.isEmpty then "]"
     else "\n" ++ String.intercalate ",\n" (values.map fun v => "    " ++ v.toJson) ++
       "\n  ]"))
  IO.println "}"
