-- Generated by `scripts/gen-primop-expectations.py`; do not edit by hand.
--
-- Prints, as JSON, what every export of `SnapshotsPBOPure/PrimOpInt03Configurable.lean` answers in
-- Lean: a constant as it stands, a function at the arguments the generator lists.  The
-- Node suites of the generated JavaScript read the result and check the module against
-- it — a configurable module has two of them (`-num.js` and `-bigint.js`) and a
-- non-configurable module one — so the expected answers are Lean's own and no answer is
-- written down by hand.
--
--     scripts/regen-primop-expectations.sh
import SnapshotsPBOPure.PrimOpInt03Configurable

/-- How an answer is written down: the same rendering the Node suites compute from the
    JavaScript value, so that the two can be compared as strings. -/
class Render (α : Type) where
  render : α → String

export Render (render)

instance : Render Nat := ⟨toString⟩
instance : Render UInt8 := ⟨fun a => toString a.toNat⟩
instance : Render UInt16 := ⟨fun a => toString a.toNat⟩
instance : Render UInt32 := ⟨fun a => toString a.toNat⟩
instance : Render Int8 := ⟨fun a => toString a.toInt⟩
instance : Render Int16 := ⟨fun a => toString a.toInt⟩
instance : Render Int32 := ⟨fun a => toString a.toInt⟩
instance : Render Int := ⟨toString⟩
instance : Render Bool := ⟨toString⟩
instance : Render UInt64 := ⟨fun a => toString a.toNat⟩
instance : Render USize := ⟨fun a => toString a.toNat⟩
instance : Render Int64 := ⟨fun a => toString a.toInt⟩
instance : Render ISize := ⟨fun a => toString a.toInt⟩
instance [Render α] : Render (Array α) :=
  ⟨fun xs => "[" ++ String.intercalate "," (xs.toList.map render) ++ "]"⟩

private def quote (s : String) : String := "\"" ++ s ++ "\""

/-- One call of an exported function, and what Lean answers. -/
private structure Call where
  fn : String
  args : List String
  expected : String

/-- One exported constant, and what Lean answers. -/
private structure Value where
  name : String
  expected : String

private def Call.toJson (c : Call) : String :=
  "{\"fn\": " ++ quote c.fn ++ ", \"args\": [" ++
    String.intercalate ", " (c.args.map quote) ++ "], \"expected\": " ++
    quote c.expected ++ "}"

private def Value.toJson (v : Value) : String :=
  "{\"name\": " ++ quote v.name ++ ", \"expected\": " ++ quote v.expected ++ "}"

private def calls : List Call :=
[
  ⟨"TestUInt64_test4", ["3"], render (TestUInt64.test4 (3))⟩,
  ⟨"TestUSize_test4", ["3"], render (TestUSize.test4 (3))⟩,
  ⟨"TestNat_test4", ["3"], render (TestNat.test4 (3))⟩,
  ⟨"TestInt64_test4", ["3"], render (TestInt64.test4 (3))⟩,
  ⟨"TestISize_test4", ["3"], render (TestISize.test4 (3))⟩,
  ⟨"TestInt_test4", ["3"], render (TestInt.test4 (3))⟩
]

private def values : List Value :=
[
  ⟨"TestUInt64_test1", render (TestUInt64.test1)⟩,
  ⟨"TestUInt64_test2", render (TestUInt64.test2)⟩,
  ⟨"TestUInt64_test3", render (TestUInt64.test3)⟩,
  ⟨"TestUSize_test1", render (TestUSize.test1)⟩,
  ⟨"TestUSize_test2", render (TestUSize.test2)⟩,
  ⟨"TestUSize_test3", render (TestUSize.test3)⟩,
  ⟨"TestNat_test1", render (TestNat.test1)⟩,
  ⟨"TestNat_test2", render (TestNat.test2)⟩,
  ⟨"TestNat_test3", render (TestNat.test3)⟩,
  ⟨"TestInt64_test1", render (TestInt64.test1)⟩,
  ⟨"TestInt64_test2", render (TestInt64.test2)⟩,
  ⟨"TestInt64_test3", render (TestInt64.test3)⟩,
  ⟨"TestISize_test1", render (TestISize.test1)⟩,
  ⟨"TestISize_test2", render (TestISize.test2)⟩,
  ⟨"TestISize_test3", render (TestISize.test3)⟩,
  ⟨"TestInt_test1", render (TestInt.test1)⟩,
  ⟨"TestInt_test2", render (TestInt.test2)⟩,
  ⟨"TestInt_test3", render (TestInt.test3)⟩
]

def main : IO Unit := do
  IO.println "{"
  IO.println ("  \"calls\": [" ++
    (if calls.isEmpty then "],"
     else "\n" ++ String.intercalate ",\n" (calls.map fun c => "    " ++ c.toJson) ++
       "\n  ],"))
  IO.println ("  \"values\": [" ++
    (if values.isEmpty then "]"
     else "\n" ++ String.intercalate ",\n" (values.map fun v => "    " ++ v.toJson) ++
       "\n  ]"))
  IO.println "}"
