-- Generated by `scripts/gen-primop-expectations.py`; do not edit by hand.
--
-- Prints, as JSON, what every export of `SnapshotsPBOPure/PrimOpBitVec02Configurable.lean` answers in
-- Lean: a constant as it stands, a function at the arguments the generator lists.  The
-- Node suites of the generated JavaScript read the result and check the module against
-- it — a configurable module has two of them (`-num.js` and `-bigint.js`) and a
-- non-configurable module one — so the expected answers are Lean's own and no answer is
-- written down by hand.
--
--     scripts/regen-primop-expectations.sh
import SnapshotsPBOPure.PrimOpBitVec02Configurable

/-- How an answer is written down: the same rendering the Node suites compute from the
    JavaScript value, so that the two can be compared as strings. -/
class Render (α : Type) where
  render : α → String

export Render (render)

instance : Render Nat := ⟨toString⟩
instance : Render UInt8 := ⟨fun a => toString a.toNat⟩
instance : Render UInt16 := ⟨fun a => toString a.toNat⟩
instance : Render UInt32 := ⟨fun a => toString a.toNat⟩
instance : Render Int8 := ⟨fun a => toString a.toInt⟩
instance : Render Int16 := ⟨fun a => toString a.toInt⟩
instance : Render Int32 := ⟨fun a => toString a.toInt⟩
instance : Render Int := ⟨toString⟩
instance : Render Bool := ⟨toString⟩
instance : Render UInt64 := ⟨fun a => toString a.toNat⟩
instance : Render USize := ⟨fun a => toString a.toNat⟩
instance : Render Int64 := ⟨fun a => toString a.toInt⟩
instance : Render ISize := ⟨fun a => toString a.toInt⟩
instance {w : Nat} : Render (BitVec w) := ⟨fun a => toString a.toNat⟩
instance [Render α] : Render (Array α) :=
  ⟨fun xs => "[" ++ String.intercalate "," (xs.toList.map render) ++ "]"⟩

private def quote (s : String) : String := "\"" ++ s ++ "\""

/-- One call of an exported function, and what Lean answers. -/
private structure Call where
  fn : String
  args : List String
  expected : String

/-- One exported constant, and what Lean answers. -/
private structure Value where
  name : String
  expected : String

private def Call.toJson (c : Call) : String :=
  "{\"fn\": " ++ quote c.fn ++ ", \"args\": [" ++
    String.intercalate ", " (c.args.map quote) ++ "], \"expected\": " ++
    quote c.expected ++ "}"

private def Value.toJson (v : Value) : String :=
  "{\"name\": " ++ quote v.name ++ ", \"expected\": " ++ quote v.expected ++ "}"

private def calls : List Call :=
[
  ⟨"TestBitVec32_land", ["1", "1"], render (TestBitVec32.land (1) (1))⟩,
  ⟨"TestBitVec32_land", ["7", "3"], render (TestBitVec32.land (7) (3))⟩,
  ⟨"TestBitVec32_land", ["255", "16"], render (TestBitVec32.land (255) (16))⟩,
  ⟨"TestBitVec32_land", ["5", "0"], render (TestBitVec32.land (5) (0))⟩,
  ⟨"TestBitVec32_land", ["1023", "2"], render (TestBitVec32.land (1023) (2))⟩,
  ⟨"TestBitVec32_lor", ["1", "1"], render (TestBitVec32.lor (1) (1))⟩,
  ⟨"TestBitVec32_lor", ["7", "3"], render (TestBitVec32.lor (7) (3))⟩,
  ⟨"TestBitVec32_lor", ["255", "16"], render (TestBitVec32.lor (255) (16))⟩,
  ⟨"TestBitVec32_lor", ["5", "0"], render (TestBitVec32.lor (5) (0))⟩,
  ⟨"TestBitVec32_lor", ["1023", "2"], render (TestBitVec32.lor (1023) (2))⟩,
  ⟨"TestBitVec32_shiftLeft", ["1", "1"], render (TestBitVec32.shiftLeft (1) (1))⟩,
  ⟨"TestBitVec32_shiftLeft", ["7", "3"], render (TestBitVec32.shiftLeft (7) (3))⟩,
  ⟨"TestBitVec32_shiftLeft", ["255", "16"], render (TestBitVec32.shiftLeft (255) (16))⟩,
  ⟨"TestBitVec32_shiftLeft", ["5", "0"], render (TestBitVec32.shiftLeft (5) (0))⟩,
  ⟨"TestBitVec32_shiftLeft", ["1023", "2"], render (TestBitVec32.shiftLeft (1023) (2))⟩,
  ⟨"TestBitVec32_shiftRight", ["1", "1"], render (TestBitVec32.shiftRight (1) (1))⟩,
  ⟨"TestBitVec32_shiftRight", ["7", "3"], render (TestBitVec32.shiftRight (7) (3))⟩,
  ⟨"TestBitVec32_shiftRight", ["255", "16"], render (TestBitVec32.shiftRight (255) (16))⟩,
  ⟨"TestBitVec32_shiftRight", ["5", "0"], render (TestBitVec32.shiftRight (5) (0))⟩,
  ⟨"TestBitVec32_shiftRight", ["1023", "2"], render (TestBitVec32.shiftRight (1023) (2))⟩,
  ⟨"TestBitVec32_xor", ["1", "1"], render (TestBitVec32.xor (1) (1))⟩,
  ⟨"TestBitVec32_xor", ["7", "3"], render (TestBitVec32.xor (7) (3))⟩,
  ⟨"TestBitVec32_xor", ["255", "16"], render (TestBitVec32.xor (255) (16))⟩,
  ⟨"TestBitVec32_xor", ["5", "0"], render (TestBitVec32.xor (5) (0))⟩,
  ⟨"TestBitVec32_xor", ["1023", "2"], render (TestBitVec32.xor (1023) (2))⟩,
  ⟨"TestBitVec32_complement", ["1"], render (TestBitVec32.complement (1))⟩,
  ⟨"TestBitVec32_complement", ["255"], render (TestBitVec32.complement (255))⟩,
  ⟨"TestBitVec32_complement", ["0"], render (TestBitVec32.complement (0))⟩,
  ⟨"TestBitVec64_land", ["1", "1"], render (TestBitVec64.land (1) (1))⟩,
  ⟨"TestBitVec64_land", ["7", "3"], render (TestBitVec64.land (7) (3))⟩,
  ⟨"TestBitVec64_land", ["255", "16"], render (TestBitVec64.land (255) (16))⟩,
  ⟨"TestBitVec64_land", ["5", "0"], render (TestBitVec64.land (5) (0))⟩,
  ⟨"TestBitVec64_land", ["1023", "2"], render (TestBitVec64.land (1023) (2))⟩,
  ⟨"TestBitVec64_lor", ["1", "1"], render (TestBitVec64.lor (1) (1))⟩,
  ⟨"TestBitVec64_lor", ["7", "3"], render (TestBitVec64.lor (7) (3))⟩,
  ⟨"TestBitVec64_lor", ["255", "16"], render (TestBitVec64.lor (255) (16))⟩,
  ⟨"TestBitVec64_lor", ["5", "0"], render (TestBitVec64.lor (5) (0))⟩,
  ⟨"TestBitVec64_lor", ["1023", "2"], render (TestBitVec64.lor (1023) (2))⟩,
  ⟨"TestBitVec64_shiftLeft", ["1", "1"], render (TestBitVec64.shiftLeft (1) (1))⟩,
  ⟨"TestBitVec64_shiftLeft", ["7", "3"], render (TestBitVec64.shiftLeft (7) (3))⟩,
  ⟨"TestBitVec64_shiftLeft", ["255", "16"], render (TestBitVec64.shiftLeft (255) (16))⟩,
  ⟨"TestBitVec64_shiftLeft", ["5", "0"], render (TestBitVec64.shiftLeft (5) (0))⟩,
  ⟨"TestBitVec64_shiftLeft", ["1023", "2"], render (TestBitVec64.shiftLeft (1023) (2))⟩,
  ⟨"TestBitVec64_shiftRight", ["1", "1"], render (TestBitVec64.shiftRight (1) (1))⟩,
  ⟨"TestBitVec64_shiftRight", ["7", "3"], render (TestBitVec64.shiftRight (7) (3))⟩,
  ⟨"TestBitVec64_shiftRight", ["255", "16"], render (TestBitVec64.shiftRight (255) (16))⟩,
  ⟨"TestBitVec64_shiftRight", ["5", "0"], render (TestBitVec64.shiftRight (5) (0))⟩,
  ⟨"TestBitVec64_shiftRight", ["1023", "2"], render (TestBitVec64.shiftRight (1023) (2))⟩,
  ⟨"TestBitVec64_xor", ["1", "1"], render (TestBitVec64.xor (1) (1))⟩,
  ⟨"TestBitVec64_xor", ["7", "3"], render (TestBitVec64.xor (7) (3))⟩,
  ⟨"TestBitVec64_xor", ["255", "16"], render (TestBitVec64.xor (255) (16))⟩,
  ⟨"TestBitVec64_xor", ["5", "0"], render (TestBitVec64.xor (5) (0))⟩,
  ⟨"TestBitVec64_xor", ["1023", "2"], render (TestBitVec64.xor (1023) (2))⟩,
  ⟨"TestBitVec64_complement", ["1"], render (TestBitVec64.complement (1))⟩,
  ⟨"TestBitVec64_complement", ["255"], render (TestBitVec64.complement (255))⟩,
  ⟨"TestBitVec64_complement", ["0"], render (TestBitVec64.complement (0))⟩
]

private def values : List Value :=
[

]

def main : IO Unit := do
  IO.println "{"
  IO.println ("  \"calls\": [" ++
    (if calls.isEmpty then "],"
     else "\n" ++ String.intercalate ",\n" (calls.map fun c => "    " ++ c.toJson) ++
       "\n  ],"))
  IO.println ("  \"values\": [" ++
    (if values.isEmpty then "]"
     else "\n" ++ String.intercalate ",\n" (values.map fun v => "    " ++ v.toJson) ++
       "\n  ]"))
  IO.println "}"
