-- Generated by `scripts/gen-primop-expectations.py`; do not edit by hand.
--
-- Prints, as JSON, what every export of `SnapshotsPBOPure/PrimOpInt02NonConfigurable.lean` answers in
-- Lean: a constant as it stands, a function at the arguments the generator lists.  The
-- Node suites of the generated JavaScript read the result and check the module against
-- it — a configurable module has two of them (`-num.js` and `-bigint.js`) and a
-- non-configurable module one — so the expected answers are Lean's own and no answer is
-- written down by hand.
--
--     scripts/regen-primop-expectations.sh
import SnapshotsPBOPure.PrimOpInt02NonConfigurable

/-- How an answer is written down: the same rendering the Node suites compute from the
    JavaScript value, so that the two can be compared as strings. -/
class Render (α : Type) where
  render : α → String

export Render (render)

instance : Render Nat := ⟨toString⟩
instance : Render UInt8 := ⟨fun a => toString a.toNat⟩
instance : Render UInt16 := ⟨fun a => toString a.toNat⟩
instance : Render UInt32 := ⟨fun a => toString a.toNat⟩
instance : Render Int8 := ⟨fun a => toString a.toInt⟩
instance : Render Int16 := ⟨fun a => toString a.toInt⟩
instance : Render Int32 := ⟨fun a => toString a.toInt⟩
instance : Render Int := ⟨toString⟩
instance : Render Bool := ⟨toString⟩
instance : Render UInt64 := ⟨fun a => toString a.toNat⟩
instance : Render USize := ⟨fun a => toString a.toNat⟩
instance : Render Int64 := ⟨fun a => toString a.toInt⟩
instance : Render ISize := ⟨fun a => toString a.toInt⟩
instance [Render α] : Render (Array α) :=
  ⟨fun xs => "[" ++ String.intercalate "," (xs.toList.map render) ++ "]"⟩

private def quote (s : String) : String := "\"" ++ s ++ "\""

/-- One call of an exported function, and what Lean answers. -/
private structure Call where
  fn : String
  args : List String
  expected : String

/-- One exported constant, and what Lean answers. -/
private structure Value where
  name : String
  expected : String

private def Call.toJson (c : Call) : String :=
  "{\"fn\": " ++ quote c.fn ++ ", \"args\": [" ++
    String.intercalate ", " (c.args.map quote) ++ "], \"expected\": " ++
    quote c.expected ++ "}"

private def Value.toJson (v : Value) : String :=
  "{\"name\": " ++ quote v.name ++ ", \"expected\": " ++ quote v.expected ++ "}"

private def calls : List Call :=
[

]

private def values : List Value :=
[
  ⟨"TestUInt8_test1", render (TestUInt8.test1)⟩,
  ⟨"TestUInt8_test2", render (TestUInt8.test2)⟩,
  ⟨"TestUInt8_test3", render (TestUInt8.test3)⟩,
  ⟨"TestUInt8_test4", render (TestUInt8.test4)⟩,
  ⟨"TestUInt8_test5", render (TestUInt8.test5)⟩,
  ⟨"TestUInt8_test6", render (TestUInt8.test6)⟩,
  ⟨"TestUInt8_test7", render (TestUInt8.test7)⟩,
  ⟨"TestUInt8_test8", render (TestUInt8.test8)⟩,
  ⟨"TestUInt8_test9", render (TestUInt8.test9)⟩,
  ⟨"TestUInt8_test10", render (TestUInt8.test10)⟩,
  ⟨"TestUInt8_test11", render (TestUInt8.test11)⟩,
  ⟨"TestUInt16_test1", render (TestUInt16.test1)⟩,
  ⟨"TestUInt16_test2", render (TestUInt16.test2)⟩,
  ⟨"TestUInt16_test3", render (TestUInt16.test3)⟩,
  ⟨"TestUInt16_test4", render (TestUInt16.test4)⟩,
  ⟨"TestUInt16_test5", render (TestUInt16.test5)⟩,
  ⟨"TestUInt16_test6", render (TestUInt16.test6)⟩,
  ⟨"TestUInt16_test7", render (TestUInt16.test7)⟩,
  ⟨"TestUInt16_test8", render (TestUInt16.test8)⟩,
  ⟨"TestUInt16_test9", render (TestUInt16.test9)⟩,
  ⟨"TestUInt16_test10", render (TestUInt16.test10)⟩,
  ⟨"TestUInt16_test11", render (TestUInt16.test11)⟩,
  ⟨"TestUInt32_test1", render (TestUInt32.test1)⟩,
  ⟨"TestUInt32_test2", render (TestUInt32.test2)⟩,
  ⟨"TestUInt32_test3", render (TestUInt32.test3)⟩,
  ⟨"TestUInt32_test4", render (TestUInt32.test4)⟩,
  ⟨"TestUInt32_test5", render (TestUInt32.test5)⟩,
  ⟨"TestUInt32_test6", render (TestUInt32.test6)⟩,
  ⟨"TestUInt32_test7", render (TestUInt32.test7)⟩,
  ⟨"TestUInt32_test8", render (TestUInt32.test8)⟩,
  ⟨"TestUInt32_test9", render (TestUInt32.test9)⟩,
  ⟨"TestUInt32_test10", render (TestUInt32.test10)⟩,
  ⟨"TestUInt32_test11", render (TestUInt32.test11)⟩,
  ⟨"TestInt8_test1", render (TestInt8.test1)⟩,
  ⟨"TestInt8_test2", render (TestInt8.test2)⟩,
  ⟨"TestInt8_test3", render (TestInt8.test3)⟩,
  ⟨"TestInt8_test4", render (TestInt8.test4)⟩,
  ⟨"TestInt8_test5", render (TestInt8.test5)⟩,
  ⟨"TestInt8_test6", render (TestInt8.test6)⟩,
  ⟨"TestInt8_test7", render (TestInt8.test7)⟩,
  ⟨"TestInt8_test8", render (TestInt8.test8)⟩,
  ⟨"TestInt8_test9", render (TestInt8.test9)⟩,
  ⟨"TestInt8_test10", render (TestInt8.test10)⟩,
  ⟨"TestInt8_test11", render (TestInt8.test11)⟩,
  ⟨"TestInt16_test1", render (TestInt16.test1)⟩,
  ⟨"TestInt16_test2", render (TestInt16.test2)⟩,
  ⟨"TestInt16_test3", render (TestInt16.test3)⟩,
  ⟨"TestInt16_test4", render (TestInt16.test4)⟩,
  ⟨"TestInt16_test5", render (TestInt16.test5)⟩,
  ⟨"TestInt16_test6", render (TestInt16.test6)⟩,
  ⟨"TestInt16_test7", render (TestInt16.test7)⟩,
  ⟨"TestInt16_test8", render (TestInt16.test8)⟩,
  ⟨"TestInt16_test9", render (TestInt16.test9)⟩,
  ⟨"TestInt16_test10", render (TestInt16.test10)⟩,
  ⟨"TestInt16_test11", render (TestInt16.test11)⟩,
  ⟨"TestInt32_test1", render (TestInt32.test1)⟩,
  ⟨"TestInt32_test2", render (TestInt32.test2)⟩,
  ⟨"TestInt32_test3", render (TestInt32.test3)⟩,
  ⟨"TestInt32_test4", render (TestInt32.test4)⟩,
  ⟨"TestInt32_test5", render (TestInt32.test5)⟩,
  ⟨"TestInt32_test6", render (TestInt32.test6)⟩,
  ⟨"TestInt32_test7", render (TestInt32.test7)⟩,
  ⟨"TestInt32_test8", render (TestInt32.test8)⟩,
  ⟨"TestInt32_test9", render (TestInt32.test9)⟩,
  ⟨"TestInt32_test10", render (TestInt32.test10)⟩,
  ⟨"TestInt32_test11", render (TestInt32.test11)⟩
]

def main : IO Unit := do
  IO.println "{"
  IO.println ("  \"calls\": [" ++
    (if calls.isEmpty then "],"
     else "\n" ++ String.intercalate ",\n" (calls.map fun c => "    " ++ c.toJson) ++
       "\n  ],"))
  IO.println ("  \"values\": [" ++
    (if values.isEmpty then "]"
     else "\n" ++ String.intercalate ",\n" (values.map fun v => "    " ++ v.toJson) ++
       "\n  ]"))
  IO.println "}"
