-- Generated by `scripts/gen-primop-expectations.py`; do not edit by hand.
--
-- Prints, as JSON, what every export of `SnapshotsPBOPure/PrimOpInt02Configurable.lean` answers in
-- Lean: a constant as it stands, a function at the arguments the generator lists.  The
-- Node suites of the generated JavaScript read the result and check the module against
-- it — a configurable module has two of them (`-num.js` and `-bigint.js`) and a
-- non-configurable module one — so the expected answers are Lean's own and no answer is
-- written down by hand.
--
--     scripts/regen-primop-expectations.sh
import SnapshotsPBOPure.PrimOpInt02Configurable

/-- How an answer is written down: the same rendering the Node suites compute from the
    JavaScript value, so that the two can be compared as strings. -/
class Render (α : Type) where
  render : α → String

export Render (render)

instance : Render Nat := ⟨toString⟩
instance : Render UInt8 := ⟨fun a => toString a.toNat⟩
instance : Render UInt16 := ⟨fun a => toString a.toNat⟩
instance : Render UInt32 := ⟨fun a => toString a.toNat⟩
instance : Render Int8 := ⟨fun a => toString a.toInt⟩
instance : Render Int16 := ⟨fun a => toString a.toInt⟩
instance : Render Int32 := ⟨fun a => toString a.toInt⟩
instance : Render Int := ⟨toString⟩
instance : Render Bool := ⟨toString⟩
instance : Render UInt64 := ⟨fun a => toString a.toNat⟩
instance : Render USize := ⟨fun a => toString a.toNat⟩
instance : Render Int64 := ⟨fun a => toString a.toInt⟩
instance : Render ISize := ⟨fun a => toString a.toInt⟩
instance [Render α] : Render (Array α) :=
  ⟨fun xs => "[" ++ String.intercalate "," (xs.toList.map render) ++ "]"⟩

private def quote (s : String) : String := "\"" ++ s ++ "\""

/-- One call of an exported function, and what Lean answers. -/
private structure Call where
  fn : String
  args : List String
  expected : String

/-- One exported constant, and what Lean answers. -/
private structure Value where
  name : String
  expected : String

private def Call.toJson (c : Call) : String :=
  "{\"fn\": " ++ quote c.fn ++ ", \"args\": [" ++
    String.intercalate ", " (c.args.map quote) ++ "], \"expected\": " ++
    quote c.expected ++ "}"

private def Value.toJson (v : Value) : String :=
  "{\"name\": " ++ quote v.name ++ ", \"expected\": " ++ quote v.expected ++ "}"

private def calls : List Call :=
[

]

private def values : List Value :=
[
  ⟨"TestUInt64_test1", render (TestUInt64.test1)⟩,
  ⟨"TestUInt64_test2", render (TestUInt64.test2)⟩,
  ⟨"TestUInt64_test3", render (TestUInt64.test3)⟩,
  ⟨"TestUInt64_test4", render (TestUInt64.test4)⟩,
  ⟨"TestUInt64_test5", render (TestUInt64.test5)⟩,
  ⟨"TestUInt64_test6", render (TestUInt64.test6)⟩,
  ⟨"TestUInt64_test7", render (TestUInt64.test7)⟩,
  ⟨"TestUInt64_test8", render (TestUInt64.test8)⟩,
  ⟨"TestUInt64_test9", render (TestUInt64.test9)⟩,
  ⟨"TestUInt64_test10", render (TestUInt64.test10)⟩,
  ⟨"TestUInt64_test11", render (TestUInt64.test11)⟩,
  ⟨"TestUSize_test1", render (TestUSize.test1)⟩,
  ⟨"TestUSize_test2", render (TestUSize.test2)⟩,
  ⟨"TestUSize_test3", render (TestUSize.test3)⟩,
  ⟨"TestUSize_test4", render (TestUSize.test4)⟩,
  ⟨"TestUSize_test5", render (TestUSize.test5)⟩,
  ⟨"TestUSize_test6", render (TestUSize.test6)⟩,
  ⟨"TestUSize_test7", render (TestUSize.test7)⟩,
  ⟨"TestUSize_test8", render (TestUSize.test8)⟩,
  ⟨"TestUSize_test9", render (TestUSize.test9)⟩,
  ⟨"TestUSize_test10", render (TestUSize.test10)⟩,
  ⟨"TestUSize_test11", render (TestUSize.test11)⟩,
  ⟨"TestNat_test1", render (TestNat.test1)⟩,
  ⟨"TestNat_test2", render (TestNat.test2)⟩,
  ⟨"TestNat_test3", render (TestNat.test3)⟩,
  ⟨"TestNat_test4", render (TestNat.test4)⟩,
  ⟨"TestNat_test5", render (TestNat.test5)⟩,
  ⟨"TestNat_test6", render (TestNat.test6)⟩,
  ⟨"TestNat_test7", render (TestNat.test7)⟩,
  ⟨"TestNat_test8", render (TestNat.test8)⟩,
  ⟨"TestNat_test9", render (TestNat.test9)⟩,
  ⟨"TestNat_test10", render (TestNat.test10)⟩,
  ⟨"TestInt64_test1", render (TestInt64.test1)⟩,
  ⟨"TestInt64_test2", render (TestInt64.test2)⟩,
  ⟨"TestInt64_test3", render (TestInt64.test3)⟩,
  ⟨"TestInt64_test4", render (TestInt64.test4)⟩,
  ⟨"TestInt64_test5", render (TestInt64.test5)⟩,
  ⟨"TestInt64_test6", render (TestInt64.test6)⟩,
  ⟨"TestInt64_test7", render (TestInt64.test7)⟩,
  ⟨"TestInt64_test8", render (TestInt64.test8)⟩,
  ⟨"TestInt64_test9", render (TestInt64.test9)⟩,
  ⟨"TestInt64_test10", render (TestInt64.test10)⟩,
  ⟨"TestInt64_test11", render (TestInt64.test11)⟩,
  ⟨"TestISize_test1", render (TestISize.test1)⟩,
  ⟨"TestISize_test2", render (TestISize.test2)⟩,
  ⟨"TestISize_test3", render (TestISize.test3)⟩,
  ⟨"TestISize_test4", render (TestISize.test4)⟩,
  ⟨"TestISize_test5", render (TestISize.test5)⟩,
  ⟨"TestISize_test6", render (TestISize.test6)⟩,
  ⟨"TestISize_test7", render (TestISize.test7)⟩,
  ⟨"TestISize_test8", render (TestISize.test8)⟩,
  ⟨"TestISize_test9", render (TestISize.test9)⟩,
  ⟨"TestISize_test10", render (TestISize.test10)⟩,
  ⟨"TestISize_test11", render (TestISize.test11)⟩,
  ⟨"TestInt_test1", render (TestInt.test1)⟩,
  ⟨"TestInt_test2", render (TestInt.test2)⟩,
  ⟨"TestInt_test3", render (TestInt.test3)⟩,
  ⟨"TestInt_test4", render (TestInt.test4)⟩,
  ⟨"TestInt_test5", render (TestInt.test5)⟩,
  ⟨"TestInt_test6", render (TestInt.test6)⟩,
  ⟨"TestInt_test7", render (TestInt.test7)⟩,
  ⟨"TestInt_test8", render (TestInt.test8)⟩,
  ⟨"TestInt_test9", render (TestInt.test9)⟩,
  ⟨"TestInt_test10", render (TestInt.test10)⟩,
  ⟨"TestInt_test11", render (TestInt.test11)⟩
]

def main : IO Unit := do
  IO.println "{"
  IO.println ("  \"calls\": [" ++
    (if calls.isEmpty then "],"
     else "\n" ++ String.intercalate ",\n" (calls.map fun c => "    " ++ c.toJson) ++
       "\n  ],"))
  IO.println ("  \"values\": [" ++
    (if values.isEmpty then "]"
     else "\n" ++ String.intercalate ",\n" (values.map fun v => "    " ++ v.toJson) ++
       "\n  ]"))
  IO.println "}"
