-- Generated by `scripts/gen-primop-expectations.py`; do not edit by hand.
--
-- Prints, as JSON, what every export of `SnapshotsPBOPure/PrimOpIntBit01NonConfigurable.lean` answers in
-- Lean: a constant as it stands, a function at the arguments the generator lists.  The
-- Node suites of the generated JavaScript read the result and check the module against
-- it — a configurable module has two of them (`-num.js` and `-bigint.js`) and a
-- non-configurable module one — so the expected answers are Lean's own and no answer is
-- written down by hand.
--
--     scripts/regen-primop-expectations.sh
import SnapshotsPBOPure.PrimOpIntBit01NonConfigurable

/-- How an answer is written down: the same rendering the Node suites compute from the
    JavaScript value, so that the two can be compared as strings. -/
class Render (α : Type) where
  render : α → String

export Render (render)

instance : Render Nat := ⟨toString⟩
instance : Render UInt8 := ⟨fun a => toString a.toNat⟩
instance : Render UInt16 := ⟨fun a => toString a.toNat⟩
instance : Render UInt32 := ⟨fun a => toString a.toNat⟩
instance : Render Int8 := ⟨fun a => toString a.toInt⟩
instance : Render Int16 := ⟨fun a => toString a.toInt⟩
instance : Render Int32 := ⟨fun a => toString a.toInt⟩
instance : Render Int := ⟨toString⟩
instance : Render Bool := ⟨toString⟩
instance : Render UInt64 := ⟨fun a => toString a.toNat⟩
instance : Render USize := ⟨fun a => toString a.toNat⟩
instance : Render Int64 := ⟨fun a => toString a.toInt⟩
instance : Render ISize := ⟨fun a => toString a.toInt⟩
instance {w : Nat} : Render (BitVec w) := ⟨fun a => toString a.toNat⟩
instance [Render α] : Render (Array α) :=
  ⟨fun xs => "[" ++ String.intercalate "," (xs.toList.map render) ++ "]"⟩

private def quote (s : String) : String := "\"" ++ s ++ "\""

/-- One call of an exported function, and what Lean answers. -/
private structure Call where
  fn : String
  args : List String
  expected : String

/-- One exported constant, and what Lean answers. -/
private structure Value where
  name : String
  expected : String

private def Call.toJson (c : Call) : String :=
  "{\"fn\": " ++ quote c.fn ++ ", \"args\": [" ++
    String.intercalate ", " (c.args.map quote) ++ "], \"expected\": " ++
    quote c.expected ++ "}"

private def Value.toJson (v : Value) : String :=
  "{\"name\": " ++ quote v.name ++ ", \"expected\": " ++ quote v.expected ++ "}"

private def calls : List Call :=
[
  ⟨"TestUInt8_land", ["1", "1"], render (TestUInt8.land (1) (1))⟩,
  ⟨"TestUInt8_land", ["7", "3"], render (TestUInt8.land (7) (3))⟩,
  ⟨"TestUInt8_land", ["255", "16"], render (TestUInt8.land (255) (16))⟩,
  ⟨"TestUInt8_land", ["5", "0"], render (TestUInt8.land (5) (0))⟩,
  ⟨"TestUInt8_land", ["200", "2"], render (TestUInt8.land (200) (2))⟩,
  ⟨"TestUInt8_lor", ["1", "1"], render (TestUInt8.lor (1) (1))⟩,
  ⟨"TestUInt8_lor", ["7", "3"], render (TestUInt8.lor (7) (3))⟩,
  ⟨"TestUInt8_lor", ["255", "16"], render (TestUInt8.lor (255) (16))⟩,
  ⟨"TestUInt8_lor", ["5", "0"], render (TestUInt8.lor (5) (0))⟩,
  ⟨"TestUInt8_lor", ["200", "2"], render (TestUInt8.lor (200) (2))⟩,
  ⟨"TestUInt8_shiftLeft", ["1", "1"], render (TestUInt8.shiftLeft (1) (1))⟩,
  ⟨"TestUInt8_shiftLeft", ["7", "3"], render (TestUInt8.shiftLeft (7) (3))⟩,
  ⟨"TestUInt8_shiftLeft", ["255", "16"], render (TestUInt8.shiftLeft (255) (16))⟩,
  ⟨"TestUInt8_shiftLeft", ["5", "0"], render (TestUInt8.shiftLeft (5) (0))⟩,
  ⟨"TestUInt8_shiftLeft", ["200", "2"], render (TestUInt8.shiftLeft (200) (2))⟩,
  ⟨"TestUInt8_shiftRight", ["1", "1"], render (TestUInt8.shiftRight (1) (1))⟩,
  ⟨"TestUInt8_shiftRight", ["7", "3"], render (TestUInt8.shiftRight (7) (3))⟩,
  ⟨"TestUInt8_shiftRight", ["255", "16"], render (TestUInt8.shiftRight (255) (16))⟩,
  ⟨"TestUInt8_shiftRight", ["5", "0"], render (TestUInt8.shiftRight (5) (0))⟩,
  ⟨"TestUInt8_shiftRight", ["200", "2"], render (TestUInt8.shiftRight (200) (2))⟩,
  ⟨"TestUInt8_xor", ["1", "1"], render (TestUInt8.xor (1) (1))⟩,
  ⟨"TestUInt8_xor", ["7", "3"], render (TestUInt8.xor (7) (3))⟩,
  ⟨"TestUInt8_xor", ["255", "16"], render (TestUInt8.xor (255) (16))⟩,
  ⟨"TestUInt8_xor", ["5", "0"], render (TestUInt8.xor (5) (0))⟩,
  ⟨"TestUInt8_xor", ["200", "2"], render (TestUInt8.xor (200) (2))⟩,
  ⟨"TestUInt8_complement", ["1"], render (TestUInt8.complement (1))⟩,
  ⟨"TestUInt8_complement", ["255"], render (TestUInt8.complement (255))⟩,
  ⟨"TestUInt8_complement", ["0"], render (TestUInt8.complement (0))⟩,
  ⟨"TestUInt16_land", ["1", "1"], render (TestUInt16.land (1) (1))⟩,
  ⟨"TestUInt16_land", ["7", "3"], render (TestUInt16.land (7) (3))⟩,
  ⟨"TestUInt16_land", ["255", "16"], render (TestUInt16.land (255) (16))⟩,
  ⟨"TestUInt16_land", ["5", "0"], render (TestUInt16.land (5) (0))⟩,
  ⟨"TestUInt16_land", ["1023", "2"], render (TestUInt16.land (1023) (2))⟩,
  ⟨"TestUInt16_lor", ["1", "1"], render (TestUInt16.lor (1) (1))⟩,
  ⟨"TestUInt16_lor", ["7", "3"], render (TestUInt16.lor (7) (3))⟩,
  ⟨"TestUInt16_lor", ["255", "16"], render (TestUInt16.lor (255) (16))⟩,
  ⟨"TestUInt16_lor", ["5", "0"], render (TestUInt16.lor (5) (0))⟩,
  ⟨"TestUInt16_lor", ["1023", "2"], render (TestUInt16.lor (1023) (2))⟩,
  ⟨"TestUInt16_shiftLeft", ["1", "1"], render (TestUInt16.shiftLeft (1) (1))⟩,
  ⟨"TestUInt16_shiftLeft", ["7", "3"], render (TestUInt16.shiftLeft (7) (3))⟩,
  ⟨"TestUInt16_shiftLeft", ["255", "16"], render (TestUInt16.shiftLeft (255) (16))⟩,
  ⟨"TestUInt16_shiftLeft", ["5", "0"], render (TestUInt16.shiftLeft (5) (0))⟩,
  ⟨"TestUInt16_shiftLeft", ["1023", "2"], render (TestUInt16.shiftLeft (1023) (2))⟩,
  ⟨"TestUInt16_shiftRight", ["1", "1"], render (TestUInt16.shiftRight (1) (1))⟩,
  ⟨"TestUInt16_shiftRight", ["7", "3"], render (TestUInt16.shiftRight (7) (3))⟩,
  ⟨"TestUInt16_shiftRight", ["255", "16"], render (TestUInt16.shiftRight (255) (16))⟩,
  ⟨"TestUInt16_shiftRight", ["5", "0"], render (TestUInt16.shiftRight (5) (0))⟩,
  ⟨"TestUInt16_shiftRight", ["1023", "2"], render (TestUInt16.shiftRight (1023) (2))⟩,
  ⟨"TestUInt16_xor", ["1", "1"], render (TestUInt16.xor (1) (1))⟩,
  ⟨"TestUInt16_xor", ["7", "3"], render (TestUInt16.xor (7) (3))⟩,
  ⟨"TestUInt16_xor", ["255", "16"], render (TestUInt16.xor (255) (16))⟩,
  ⟨"TestUInt16_xor", ["5", "0"], render (TestUInt16.xor (5) (0))⟩,
  ⟨"TestUInt16_xor", ["1023", "2"], render (TestUInt16.xor (1023) (2))⟩,
  ⟨"TestUInt16_complement", ["1"], render (TestUInt16.complement (1))⟩,
  ⟨"TestUInt16_complement", ["255"], render (TestUInt16.complement (255))⟩,
  ⟨"TestUInt16_complement", ["0"], render (TestUInt16.complement (0))⟩,
  ⟨"TestUInt32_land", ["1", "1"], render (TestUInt32.land (1) (1))⟩,
  ⟨"TestUInt32_land", ["7", "3"], render (TestUInt32.land (7) (3))⟩,
  ⟨"TestUInt32_land", ["255", "16"], render (TestUInt32.land (255) (16))⟩,
  ⟨"TestUInt32_land", ["5", "0"], render (TestUInt32.land (5) (0))⟩,
  ⟨"TestUInt32_land", ["1023", "2"], render (TestUInt32.land (1023) (2))⟩,
  ⟨"TestUInt32_lor", ["1", "1"], render (TestUInt32.lor (1) (1))⟩,
  ⟨"TestUInt32_lor", ["7", "3"], render (TestUInt32.lor (7) (3))⟩,
  ⟨"TestUInt32_lor", ["255", "16"], render (TestUInt32.lor (255) (16))⟩,
  ⟨"TestUInt32_lor", ["5", "0"], render (TestUInt32.lor (5) (0))⟩,
  ⟨"TestUInt32_lor", ["1023", "2"], render (TestUInt32.lor (1023) (2))⟩,
  ⟨"TestUInt32_shiftLeft", ["1", "1"], render (TestUInt32.shiftLeft (1) (1))⟩,
  ⟨"TestUInt32_shiftLeft", ["7", "3"], render (TestUInt32.shiftLeft (7) (3))⟩,
  ⟨"TestUInt32_shiftLeft", ["255", "16"], render (TestUInt32.shiftLeft (255) (16))⟩,
  ⟨"TestUInt32_shiftLeft", ["5", "0"], render (TestUInt32.shiftLeft (5) (0))⟩,
  ⟨"TestUInt32_shiftLeft", ["1023", "2"], render (TestUInt32.shiftLeft (1023) (2))⟩,
  ⟨"TestUInt32_shiftRight", ["1", "1"], render (TestUInt32.shiftRight (1) (1))⟩,
  ⟨"TestUInt32_shiftRight", ["7", "3"], render (TestUInt32.shiftRight (7) (3))⟩,
  ⟨"TestUInt32_shiftRight", ["255", "16"], render (TestUInt32.shiftRight (255) (16))⟩,
  ⟨"TestUInt32_shiftRight", ["5", "0"], render (TestUInt32.shiftRight (5) (0))⟩,
  ⟨"TestUInt32_shiftRight", ["1023", "2"], render (TestUInt32.shiftRight (1023) (2))⟩,
  ⟨"TestUInt32_xor", ["1", "1"], render (TestUInt32.xor (1) (1))⟩,
  ⟨"TestUInt32_xor", ["7", "3"], render (TestUInt32.xor (7) (3))⟩,
  ⟨"TestUInt32_xor", ["255", "16"], render (TestUInt32.xor (255) (16))⟩,
  ⟨"TestUInt32_xor", ["5", "0"], render (TestUInt32.xor (5) (0))⟩,
  ⟨"TestUInt32_xor", ["1023", "2"], render (TestUInt32.xor (1023) (2))⟩,
  ⟨"TestUInt32_complement", ["1"], render (TestUInt32.complement (1))⟩,
  ⟨"TestUInt32_complement", ["255"], render (TestUInt32.complement (255))⟩,
  ⟨"TestUInt32_complement", ["0"], render (TestUInt32.complement (0))⟩,
  ⟨"TestInt8_land", ["7", "3"], render (TestInt8.land (7) (3))⟩,
  ⟨"TestInt8_land", ["-7", "3"], render (TestInt8.land (-7) (3))⟩,
  ⟨"TestInt8_land", ["-8", "-3"], render (TestInt8.land (-8) (-3))⟩,
  ⟨"TestInt8_land", ["5", "0"], render (TestInt8.land (5) (0))⟩,
  ⟨"TestInt8_land", ["100", "2"], render (TestInt8.land (100) (2))⟩,
  ⟨"TestInt8_lor", ["7", "3"], render (TestInt8.lor (7) (3))⟩,
  ⟨"TestInt8_lor", ["-7", "3"], render (TestInt8.lor (-7) (3))⟩,
  ⟨"TestInt8_lor", ["-8", "-3"], render (TestInt8.lor (-8) (-3))⟩,
  ⟨"TestInt8_lor", ["5", "0"], render (TestInt8.lor (5) (0))⟩,
  ⟨"TestInt8_lor", ["100", "2"], render (TestInt8.lor (100) (2))⟩,
  ⟨"TestInt8_shiftLeft", ["7", "3"], render (TestInt8.shiftLeft (7) (3))⟩,
  ⟨"TestInt8_shiftLeft", ["-7", "3"], render (TestInt8.shiftLeft (-7) (3))⟩,
  ⟨"TestInt8_shiftLeft", ["-8", "-3"], render (TestInt8.shiftLeft (-8) (-3))⟩,
  ⟨"TestInt8_shiftLeft", ["5", "0"], render (TestInt8.shiftLeft (5) (0))⟩,
  ⟨"TestInt8_shiftLeft", ["100", "2"], render (TestInt8.shiftLeft (100) (2))⟩,
  ⟨"TestInt8_shiftRight", ["7", "3"], render (TestInt8.shiftRight (7) (3))⟩,
  ⟨"TestInt8_shiftRight", ["-7", "3"], render (TestInt8.shiftRight (-7) (3))⟩,
  ⟨"TestInt8_shiftRight", ["-8", "-3"], render (TestInt8.shiftRight (-8) (-3))⟩,
  ⟨"TestInt8_shiftRight", ["5", "0"], render (TestInt8.shiftRight (5) (0))⟩,
  ⟨"TestInt8_shiftRight", ["100", "2"], render (TestInt8.shiftRight (100) (2))⟩,
  ⟨"TestInt8_xor", ["7", "3"], render (TestInt8.xor (7) (3))⟩,
  ⟨"TestInt8_xor", ["-7", "3"], render (TestInt8.xor (-7) (3))⟩,
  ⟨"TestInt8_xor", ["-8", "-3"], render (TestInt8.xor (-8) (-3))⟩,
  ⟨"TestInt8_xor", ["5", "0"], render (TestInt8.xor (5) (0))⟩,
  ⟨"TestInt8_xor", ["100", "2"], render (TestInt8.xor (100) (2))⟩,
  ⟨"TestInt8_complement", ["1"], render (TestInt8.complement (1))⟩,
  ⟨"TestInt8_complement", ["-1"], render (TestInt8.complement (-1))⟩,
  ⟨"TestInt8_complement", ["0"], render (TestInt8.complement (0))⟩,
  ⟨"TestInt16_land", ["7", "3"], render (TestInt16.land (7) (3))⟩,
  ⟨"TestInt16_land", ["-7", "3"], render (TestInt16.land (-7) (3))⟩,
  ⟨"TestInt16_land", ["-8", "-3"], render (TestInt16.land (-8) (-3))⟩,
  ⟨"TestInt16_land", ["5", "0"], render (TestInt16.land (5) (0))⟩,
  ⟨"TestInt16_land", ["1023", "2"], render (TestInt16.land (1023) (2))⟩,
  ⟨"TestInt16_lor", ["7", "3"], render (TestInt16.lor (7) (3))⟩,
  ⟨"TestInt16_lor", ["-7", "3"], render (TestInt16.lor (-7) (3))⟩,
  ⟨"TestInt16_lor", ["-8", "-3"], render (TestInt16.lor (-8) (-3))⟩,
  ⟨"TestInt16_lor", ["5", "0"], render (TestInt16.lor (5) (0))⟩,
  ⟨"TestInt16_lor", ["1023", "2"], render (TestInt16.lor (1023) (2))⟩,
  ⟨"TestInt16_shiftLeft", ["7", "3"], render (TestInt16.shiftLeft (7) (3))⟩,
  ⟨"TestInt16_shiftLeft", ["-7", "3"], render (TestInt16.shiftLeft (-7) (3))⟩,
  ⟨"TestInt16_shiftLeft", ["-8", "-3"], render (TestInt16.shiftLeft (-8) (-3))⟩,
  ⟨"TestInt16_shiftLeft", ["5", "0"], render (TestInt16.shiftLeft (5) (0))⟩,
  ⟨"TestInt16_shiftLeft", ["1023", "2"], render (TestInt16.shiftLeft (1023) (2))⟩,
  ⟨"TestInt16_shiftRight", ["7", "3"], render (TestInt16.shiftRight (7) (3))⟩,
  ⟨"TestInt16_shiftRight", ["-7", "3"], render (TestInt16.shiftRight (-7) (3))⟩,
  ⟨"TestInt16_shiftRight", ["-8", "-3"], render (TestInt16.shiftRight (-8) (-3))⟩,
  ⟨"TestInt16_shiftRight", ["5", "0"], render (TestInt16.shiftRight (5) (0))⟩,
  ⟨"TestInt16_shiftRight", ["1023", "2"], render (TestInt16.shiftRight (1023) (2))⟩,
  ⟨"TestInt16_xor", ["7", "3"], render (TestInt16.xor (7) (3))⟩,
  ⟨"TestInt16_xor", ["-7", "3"], render (TestInt16.xor (-7) (3))⟩,
  ⟨"TestInt16_xor", ["-8", "-3"], render (TestInt16.xor (-8) (-3))⟩,
  ⟨"TestInt16_xor", ["5", "0"], render (TestInt16.xor (5) (0))⟩,
  ⟨"TestInt16_xor", ["1023", "2"], render (TestInt16.xor (1023) (2))⟩,
  ⟨"TestInt16_complement", ["1"], render (TestInt16.complement (1))⟩,
  ⟨"TestInt16_complement", ["-1"], render (TestInt16.complement (-1))⟩,
  ⟨"TestInt16_complement", ["0"], render (TestInt16.complement (0))⟩,
  ⟨"TestInt32_land", ["7", "3"], render (TestInt32.land (7) (3))⟩,
  ⟨"TestInt32_land", ["-7", "3"], render (TestInt32.land (-7) (3))⟩,
  ⟨"TestInt32_land", ["-8", "-3"], render (TestInt32.land (-8) (-3))⟩,
  ⟨"TestInt32_land", ["5", "0"], render (TestInt32.land (5) (0))⟩,
  ⟨"TestInt32_land", ["1023", "2"], render (TestInt32.land (1023) (2))⟩,
  ⟨"TestInt32_lor", ["7", "3"], render (TestInt32.lor (7) (3))⟩,
  ⟨"TestInt32_lor", ["-7", "3"], render (TestInt32.lor (-7) (3))⟩,
  ⟨"TestInt32_lor", ["-8", "-3"], render (TestInt32.lor (-8) (-3))⟩,
  ⟨"TestInt32_lor", ["5", "0"], render (TestInt32.lor (5) (0))⟩,
  ⟨"TestInt32_lor", ["1023", "2"], render (TestInt32.lor (1023) (2))⟩,
  ⟨"TestInt32_shiftLeft", ["7", "3"], render (TestInt32.shiftLeft (7) (3))⟩,
  ⟨"TestInt32_shiftLeft", ["-7", "3"], render (TestInt32.shiftLeft (-7) (3))⟩,
  ⟨"TestInt32_shiftLeft", ["-8", "-3"], render (TestInt32.shiftLeft (-8) (-3))⟩,
  ⟨"TestInt32_shiftLeft", ["5", "0"], render (TestInt32.shiftLeft (5) (0))⟩,
  ⟨"TestInt32_shiftLeft", ["1023", "2"], render (TestInt32.shiftLeft (1023) (2))⟩,
  ⟨"TestInt32_shiftRight", ["7", "3"], render (TestInt32.shiftRight (7) (3))⟩,
  ⟨"TestInt32_shiftRight", ["-7", "3"], render (TestInt32.shiftRight (-7) (3))⟩,
  ⟨"TestInt32_shiftRight", ["-8", "-3"], render (TestInt32.shiftRight (-8) (-3))⟩,
  ⟨"TestInt32_shiftRight", ["5", "0"], render (TestInt32.shiftRight (5) (0))⟩,
  ⟨"TestInt32_shiftRight", ["1023", "2"], render (TestInt32.shiftRight (1023) (2))⟩,
  ⟨"TestInt32_xor", ["7", "3"], render (TestInt32.xor (7) (3))⟩,
  ⟨"TestInt32_xor", ["-7", "3"], render (TestInt32.xor (-7) (3))⟩,
  ⟨"TestInt32_xor", ["-8", "-3"], render (TestInt32.xor (-8) (-3))⟩,
  ⟨"TestInt32_xor", ["5", "0"], render (TestInt32.xor (5) (0))⟩,
  ⟨"TestInt32_xor", ["1023", "2"], render (TestInt32.xor (1023) (2))⟩,
  ⟨"TestInt32_complement", ["1"], render (TestInt32.complement (1))⟩,
  ⟨"TestInt32_complement", ["-1"], render (TestInt32.complement (-1))⟩,
  ⟨"TestInt32_complement", ["0"], render (TestInt32.complement (0))⟩
]

private def values : List Value :=
[

]

def main : IO Unit := do
  IO.println "{"
  IO.println ("  \"calls\": [" ++
    (if calls.isEmpty then "],"
     else "\n" ++ String.intercalate ",\n" (calls.map fun c => "    " ++ c.toJson) ++
       "\n  ],"))
  IO.println ("  \"values\": [" ++
    (if values.isEmpty then "]"
     else "\n" ++ String.intercalate ",\n" (values.map fun v => "    " ++ v.toJson) ++
       "\n  ]"))
  IO.println "}"
