-- Generated by `scripts/gen-primop-expectations.py`; do not edit by hand.
--
-- Prints, as JSON, what every export of `SnapshotsPBOPure/PrimOpIntBit02Configurable.lean` answers in
-- Lean: a constant as it stands, a function at the arguments the generator lists.  The
-- Node suites of the generated JavaScript read the result and check the module against
-- it — a configurable module has two of them (`-num.js` and `-bigint.js`) and a
-- non-configurable module one — so the expected answers are Lean's own and no answer is
-- written down by hand.
--
--     scripts/regen-primop-expectations.sh
import SnapshotsPBOPure.PrimOpIntBit02Configurable

/-- How an answer is written down: the same rendering the Node suites compute from the
    JavaScript value, so that the two can be compared as strings. -/
class Render (α : Type) where
  render : α → String

export Render (render)

instance : Render Nat := ⟨toString⟩
instance : Render UInt8 := ⟨fun a => toString a.toNat⟩
instance : Render UInt16 := ⟨fun a => toString a.toNat⟩
instance : Render UInt32 := ⟨fun a => toString a.toNat⟩
instance : Render Int8 := ⟨fun a => toString a.toInt⟩
instance : Render Int16 := ⟨fun a => toString a.toInt⟩
instance : Render Int32 := ⟨fun a => toString a.toInt⟩
instance : Render Int := ⟨toString⟩
instance : Render Bool := ⟨toString⟩
instance : Render UInt64 := ⟨fun a => toString a.toNat⟩
instance : Render USize := ⟨fun a => toString a.toNat⟩
instance : Render Int64 := ⟨fun a => toString a.toInt⟩
instance : Render ISize := ⟨fun a => toString a.toInt⟩
instance [Render α] : Render (Array α) :=
  ⟨fun xs => "[" ++ String.intercalate "," (xs.toList.map render) ++ "]"⟩

private def quote (s : String) : String := "\"" ++ s ++ "\""

/-- One call of an exported function, and what Lean answers. -/
private structure Call where
  fn : String
  args : List String
  expected : String

/-- One exported constant, and what Lean answers. -/
private structure Value where
  name : String
  expected : String

private def Call.toJson (c : Call) : String :=
  "{\"fn\": " ++ quote c.fn ++ ", \"args\": [" ++
    String.intercalate ", " (c.args.map quote) ++ "], \"expected\": " ++
    quote c.expected ++ "}"

private def Value.toJson (v : Value) : String :=
  "{\"name\": " ++ quote v.name ++ ", \"expected\": " ++ quote v.expected ++ "}"

private def calls : List Call :=
[

]

private def values : List Value :=
[
  ⟨"TestUInt64_land", render (TestUInt64.land)⟩,
  ⟨"TestUInt64_lor", render (TestUInt64.lor)⟩,
  ⟨"TestUInt64_shiftLeft", render (TestUInt64.shiftLeft)⟩,
  ⟨"TestUInt64_shiftRight", render (TestUInt64.shiftRight)⟩,
  ⟨"TestUInt64_xor", render (TestUInt64.xor)⟩,
  ⟨"TestUInt64_complement", render (TestUInt64.complement)⟩,
  ⟨"TestUSize_land", render (TestUSize.land)⟩,
  ⟨"TestUSize_lor", render (TestUSize.lor)⟩,
  ⟨"TestUSize_shiftLeft", render (TestUSize.shiftLeft)⟩,
  ⟨"TestUSize_shiftRight", render (TestUSize.shiftRight)⟩,
  ⟨"TestUSize_xor", render (TestUSize.xor)⟩,
  ⟨"TestUSize_complement", render (TestUSize.complement)⟩,
  ⟨"TestNat_land", render (TestNat.land)⟩,
  ⟨"TestNat_lor", render (TestNat.lor)⟩,
  ⟨"TestNat_shiftLeft", render (TestNat.shiftLeft)⟩,
  ⟨"TestNat_shiftRight", render (TestNat.shiftRight)⟩,
  ⟨"TestNat_xor", render (TestNat.xor)⟩,
  ⟨"TestInt64_land", render (TestInt64.land)⟩,
  ⟨"TestInt64_lor", render (TestInt64.lor)⟩,
  ⟨"TestInt64_shiftLeft", render (TestInt64.shiftLeft)⟩,
  ⟨"TestInt64_shiftRight", render (TestInt64.shiftRight)⟩,
  ⟨"TestInt64_xor", render (TestInt64.xor)⟩,
  ⟨"TestInt64_complement", render (TestInt64.complement)⟩,
  ⟨"TestISize_land", render (TestISize.land)⟩,
  ⟨"TestISize_lor", render (TestISize.lor)⟩,
  ⟨"TestISize_shiftLeft", render (TestISize.shiftLeft)⟩,
  ⟨"TestISize_shiftRight", render (TestISize.shiftRight)⟩,
  ⟨"TestISize_xor", render (TestISize.xor)⟩,
  ⟨"TestISize_complement", render (TestISize.complement)⟩,
  ⟨"TestInt_complement", render (TestInt.complement)⟩
]

def main : IO Unit := do
  IO.println "{"
  IO.println ("  \"calls\": [" ++
    (if calls.isEmpty then "],"
     else "\n" ++ String.intercalate ",\n" (calls.map fun c => "    " ++ c.toJson) ++
       "\n  ],"))
  IO.println ("  \"values\": [" ++
    (if values.isEmpty then "]"
     else "\n" ++ String.intercalate ",\n" (values.map fun v => "    " ++ v.toJson) ++
       "\n  ]"))
  IO.println "}"
