/-
Differential checks for `RankFlakiness.AckOpaqueArg`, generated by the front end.

Every declaration below was translated into a `Term`, which is terminating by construction; what these checks add is that it computes the *same function* as the Lean declaration it came from.  A recursion whose measure fails to descend at a self call answers `stuck`, so a measure the front end read wrongly shows up here as a disagreement rather than as a silent wrong answer later.
-/

import RankFlakiness.AckOpaqueArgProgram
import RankFlakiness.AckOpaqueArg

open LakeJs LakeJs.Expr ProgramRankFlakinessAckOpaqueArg

namespace AutoCheckRankFlakinessAckOpaqueArg

/-- `ackOpaque`, as the emitted term computes it. -/
def run_ackOpaque (a0 : Nat) (a1 : Nat) : Nat :=
  Program.run Program.nil tm_ackOpaque a0 a1

/-- The emitted term and `ackOpaque` agree on the sample. -/
theorem ackOpaque_agrees :
    [run_ackOpaque 0 0, run_ackOpaque 1 0, run_ackOpaque 2 0, run_ackOpaque 3 0, run_ackOpaque 0 1, run_ackOpaque 1 1, run_ackOpaque 2 1, run_ackOpaque 3 1, run_ackOpaque 0 2, run_ackOpaque 1 2, run_ackOpaque 2 2, run_ackOpaque 3 2, run_ackOpaque 0 3, run_ackOpaque 1 3, run_ackOpaque 2 3, run_ackOpaque 3 3] =
      [_root_.ackOpaque 0 0, _root_.ackOpaque 1 0, _root_.ackOpaque 2 0, _root_.ackOpaque 3 0, _root_.ackOpaque 0 1, _root_.ackOpaque 1 1, _root_.ackOpaque 2 1, _root_.ackOpaque 3 1, _root_.ackOpaque 0 2, _root_.ackOpaque 1 2, _root_.ackOpaque 2 2, _root_.ackOpaque 3 2, _root_.ackOpaque 0 3, _root_.ackOpaque 1 3, _root_.ackOpaque 2 3, _root_.ackOpaque 3 3] := by native_decide

end AutoCheckRankFlakinessAckOpaqueArg
