/-
The verification condition of every recursion of `SnapshotsPBOPure.CaseJacobs`, generated by the front end.

`Term.Descends measure body δ γ ρ` says that the body consults its self-reference only at arguments of strictly smaller measure.  From it, `LakeJs.Descends` derives that the `stuck` branch is never taken and that the recursion satisfies the ordinary unrolling equation — so this file is the statement that the measure the front end read off Lean's `termination_by` (or off the structure of the recursion subject) is *right*, checked on the emitted term rather than on the Lean source it came from.

Each proof is one call of `descent_auto`, which assembles the derivation from the rules of `LakeJs.DescentVC` and closes the arithmetic each self call leaves.
-/

import SnapshotsPBOPure.CaseJacobsProgram

open LakeJs LakeJs.Ty LakeJs.Expr LakeJs.Expr.Ops ProgramSnapshotsPBOPureCaseJacobs

-- the statements mention whole emitted bodies, and the tactic runs the interpreter over them, so both are well past the default budget
set_option maxHeartbeats 2000000

namespace DescendsSnapshotsPBOPureCaseJacobs

/-- **The verification condition of `renderExpr`**: every self call of `bd_renderExpr` is made at arguments of strictly smaller measure — the measure written out here is the one `tm_renderExpr` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm_renderExpr_descends (δ : GEnv sig_renderExpr.decls) :
    Term.Descends (Sg := sig_renderExpr) (Γ := []) (Ρ := []) (ps := [(Ty.recTaggedUnion (.payloadFirst ⟨(RTy.self 0), [(RTy.self 0)]⟩ [(RTy.self 0), (RTy.self 0)] [[(RTy.self 0)], []]))]) (τ := Ty.string) (k := 1)
      (.cons (Term.structSize (♯0)) .nil)
      bd_renderExpr δ .nil .nil := by
  descent_auto as

end DescendsSnapshotsPBOPureCaseJacobs
