/-
The verification condition of every recursion of `SnapshotsPBOPure.CaseLeafTco`, generated by the front end.

`Term.Descends measure body δ γ ρ` says that the body consults its self-reference only at arguments of strictly smaller measure.  From it, `LakeJs.Descends` derives that the `stuck` branch is never taken and that the recursion satisfies the ordinary unrolling equation — so this file is the statement that the measure the front end read off Lean's `termination_by` (or off the structure of the recursion subject) is *right*, checked on the emitted term rather than on the Lean source it came from.

Each proof is one call of `descent_auto`, which assembles the derivation from the rules of `LakeJs.DescentVC` and closes the arithmetic each self call leaves.
-/

import SnapshotsPBOPure.CaseLeafTcoProgram

open LakeJs LakeJs.Ty LakeJs.Expr LakeJs.Expr.Ops ProgramSnapshotsPBOPureCaseLeafTco

-- the statements mention whole emitted bodies, and the tactic runs the interpreter over them, so both are well past the default budget
set_option maxHeartbeats 2000000

namespace DescendsSnapshotsPBOPureCaseLeafTco

/-- **The verification condition of `LakeJs.CoreModels.arrayAppendFrom @ Int`**: every self call of `bd_LakeJs_CoreModels_arrayAppendFrom___Int` is made at arguments of strictly smaller measure — the measure written out here is the one `tm_LakeJs_CoreModels_arrayAppendFrom___Int` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm_LakeJs_CoreModels_arrayAppendFrom___Int_descends (δ : GEnv sig_LakeJs_CoreModels_arrayAppendFrom___Int.decls) :
    Term.Descends (Sg := sig_LakeJs_CoreModels_arrayAppendFrom___Int) (Γ := []) (Ρ := []) (ps := [(Ty.array Ty.int), (Ty.array Ty.int), Ty.nat]) (τ := (Ty.array Ty.int)) (k := 1)
      (.cons (natSub (arrLen (♯1)) (♯2)) .nil)
      bd_LakeJs_CoreModels_arrayAppendFrom___Int δ .nil .nil := by
  descent_auto as

/-- **The verification condition of `test1Fuel`**: every self call of `bd_test1Fuel` is made at arguments of strictly smaller measure — the measure written out here is the one `tm_test1Fuel` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm_test1Fuel_descends (δ : GEnv sig_test1Fuel.decls) :
    Term.Descends (Sg := sig_test1Fuel) (Γ := []) (Ρ := []) (ps := [Ty.nat, Ty.bool, (Ty.array Ty.int)]) (τ := (Ty.array Ty.int)) (k := 1)
      (.cons (♯0) .nil)
      bd_test1Fuel δ .nil .nil := by
  descent_auto as

end DescendsSnapshotsPBOPureCaseLeafTco
