/-
The verification condition of every recursion of `SnapshotsPBOPure.RecursionSchemes01`, generated by the front end.

`Term.Descends measure body δ γ ρ` says that the body consults its self-reference only at arguments of strictly smaller measure.  From it, `LakeJs.Descends` derives that the `stuck` branch is never taken and that the recursion satisfies the ordinary unrolling equation — so this file is the statement that the measure the front end read off Lean's `termination_by` (or off the structure of the recursion subject) is *right*, checked on the emitted term rather than on the Lean source it came from.

Each proof is one call of `descent_auto`, which assembles the derivation from the rules of `LakeJs.DescentVC` and closes the arithmetic each self call leaves.
-/

import SnapshotsPBOPure.RecursionSchemes01Program

open LakeJs LakeJs.Ty LakeJs.Expr LakeJs.Expr.Ops ProgramSnapshotsPBOPureRecursionSchemes01

-- the statements mention whole emitted bodies, and the tactic runs the interpreter over them, so both are well past the default budget
set_option maxHeartbeats 2000000

namespace DescendsSnapshotsPBOPureRecursionSchemes01

/-- **The verification condition of `cata @ Int & cataMap @ Int (clique)`**: every self call of `bd_cata___Int___cataMap___Int__clique_` is made at arguments of strictly smaller measure — the measure written out here is the one `tm_cata___Int___cataMap___Int__clique_` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm_cata___Int___cataMap___Int__clique__descends (δ : GEnv sig_cata___Int___cataMap___Int__clique_.decls) :
    Term.Descends (Sg := sig_cata___Int___cataMap___Int__clique_) (Γ := []) (Ρ := []) (ps := [Ty.nat, (Ty.fn (Ty.taggedUnion (.payloadFirst ⟨Ty.int, []⟩ [Ty.int, Ty.int] [[Ty.int, Ty.int]])) Ty.int), (Ty.recTaggedUnion (.payloadFirst ⟨(RTy.prim .int), []⟩ [(RTy.self 0), (RTy.self 0)] [[(RTy.self 0), (RTy.self 0)]])), (Ty.fn (Ty.taggedUnion (.payloadFirst ⟨Ty.int, []⟩ [Ty.int, Ty.int] [[Ty.int, Ty.int]])) Ty.int), (Ty.recTaggedUnion (.payloadFirst ⟨(RTy.prim .int), []⟩ [(RTy.self 0), (RTy.self 0)] [[(RTy.self 0), (RTy.self 0)]]))]) (τ := (Ty.taggedUnion (.payloadFirst ⟨Ty.int, []⟩ [(Ty.taggedUnion (.payloadFirst ⟨Ty.int, []⟩ [Ty.int, Ty.int] [[Ty.int, Ty.int]]))] []))) (k := 2)
      (.cons (Term.ite (natEq (♯0) (Term.natL 0)) (Term.structSize (♯2)) (Term.structSize (♯4))) (.cons (natSub (Term.natL 1) (♯0)) .nil))
      bd_cata___Int___cataMap___Int__clique_ δ .nil .nil := by
  descent_auto as

end DescendsSnapshotsPBOPureRecursionSchemes01
