/-
Differential checks for `SnapshotsPBOPure.Tco06`, generated by the front end.

Every declaration below was translated into a `Term`, which is terminating by construction; what these checks add is that it computes the *same function* as the Lean declaration it came from.  A recursion whose measure fails to descend at a self call answers `stuck`, so a measure the front end read wrongly shows up here as a disagreement rather than as a silent wrong answer later.
-/

import SnapshotsPBOPure.Tco06Program
import SnapshotsPBOPure.Tco06

open LakeJs LakeJs.Expr ProgramSnapshotsPBOPureTco06

namespace AutoCheckSnapshotsPBOPureTco06

/-- `f`, as the emitted term computes it. -/
def run_f (a0 : Nat) (a1 : Int) (a2 : Int) : Int :=
  Program.run prog_f___g__clique_ tm_f a0 a1 a2

/-- The emitted term and `f` agree on the sample. -/
theorem f_agrees :
    [run_f 0 (-1) (-1), run_f 1 (-1) (-1), run_f 2 (-1) (-1), run_f 0 0 (-1), run_f 1 0 (-1), run_f 2 0 (-1), run_f 0 2 (-1), run_f 1 2 (-1), run_f 2 2 (-1), run_f 0 (-1) 0, run_f 1 (-1) 0, run_f 2 (-1) 0, run_f 0 0 0, run_f 1 0 0, run_f 2 0 0, run_f 0 2 0, run_f 1 2 0, run_f 2 2 0, run_f 0 (-1) 2, run_f 1 (-1) 2, run_f 2 (-1) 2, run_f 0 0 2, run_f 1 0 2, run_f 2 0 2, run_f 0 2 2, run_f 1 2 2, run_f 2 2 2] =
      [_root_.f 0 (-1) (-1), _root_.f 1 (-1) (-1), _root_.f 2 (-1) (-1), _root_.f 0 0 (-1), _root_.f 1 0 (-1), _root_.f 2 0 (-1), _root_.f 0 2 (-1), _root_.f 1 2 (-1), _root_.f 2 2 (-1), _root_.f 0 (-1) 0, _root_.f 1 (-1) 0, _root_.f 2 (-1) 0, _root_.f 0 0 0, _root_.f 1 0 0, _root_.f 2 0 0, _root_.f 0 2 0, _root_.f 1 2 0, _root_.f 2 2 0, _root_.f 0 (-1) 2, _root_.f 1 (-1) 2, _root_.f 2 (-1) 2, _root_.f 0 0 2, _root_.f 1 0 2, _root_.f 2 0 2, _root_.f 0 2 2, _root_.f 1 2 2, _root_.f 2 2 2] := by native_decide

/-- `g`, as the emitted term computes it. -/
def run_g (a0 : Nat) (a1 : Int) : Int :=
  Program.run prog_f tm_g a0 a1

/-- The emitted term and `g` agree on the sample. -/
theorem g_agrees :
    [run_g 0 (-2), run_g 1 (-2), run_g 2 (-2), run_g 3 (-2), run_g 0 0, run_g 1 0, run_g 2 0, run_g 3 0, run_g 0 3, run_g 1 3, run_g 2 3, run_g 3 3] =
      [_root_.g 0 (-2), _root_.g 1 (-2), _root_.g 2 (-2), _root_.g 3 (-2), _root_.g 0 0, _root_.g 1 0, _root_.g 2 0, _root_.g 3 0, _root_.g 0 3, _root_.g 1 3, _root_.g 2 3, _root_.g 3 3] := by native_decide

end AutoCheckSnapshotsPBOPureTco06
