/-
Differential checks for `SnapshotsPBOPure.Tco03`, generated by the front end.

Every declaration below was translated into a `Term`, which is terminating by construction; what these checks add is that it computes the *same function* as the Lean declaration it came from.  A recursion whose measure fails to descend at a self call answers `stuck`, so a measure the front end read wrongly shows up here as a disagreement rather than as a silent wrong answer later.
-/

import SnapshotsPBOPure.Tco03Program
import SnapshotsPBOPure.Tco03

open LakeJs LakeJs.Expr ProgramSnapshotsPBOPureTco03

namespace AutoCheckSnapshotsPBOPureTco03

/-- `go`, as the emitted term computes it. -/
def run_go (a0 : Nat) : Nat :=
  Program.run prog_go___k__clique_ tm_go a0

/-- The emitted term and `go` agree on the sample. -/
theorem go_agrees :
    [run_go 0, run_go 1, run_go 2, run_go 3, run_go 4, run_go 5, run_go 6, run_go 9] =
      [_root_.go 0, _root_.go 1, _root_.go 2, _root_.go 3, _root_.go 4, _root_.go 5, _root_.go 6, _root_.go 9] := by native_decide

end AutoCheckSnapshotsPBOPureTco03
