/-
Differential checks for `SnapshotsPBOPure.Tco01`, generated by the front end.

Every declaration below was translated into a `Term`, which is terminating by construction; what these checks add is that it computes the *same function* as the Lean declaration it came from.  A recursion whose measure fails to descend at a self call answers `stuck`, so a measure the front end read wrongly shows up here as a disagreement rather than as a silent wrong answer later.
-/

import SnapshotsPBOPure.Tco01Program
import SnapshotsPBOPure.Tco01

open LakeJs LakeJs.Expr ProgramSnapshotsPBOPureTco01

namespace AutoCheckSnapshotsPBOPureTco01

/-- `test`, as the emitted term computes it. -/
def run_test (a0 : Nat) : Nat :=
  Program.run Program.nil tm_test a0

/-- The emitted term and `test` agree on the sample. -/
theorem test_agrees :
    [run_test 0, run_test 1, run_test 2, run_test 3, run_test 4, run_test 5, run_test 6, run_test 9] =
      [_root_.test 0, _root_.test 1, _root_.test 2, _root_.test 3, _root_.test 4, _root_.test 5, _root_.test 6, _root_.test 9] := by native_decide

end AutoCheckSnapshotsPBOPureTco01
