/-
Differential checks for `SnapshotsMy.AssignSteps`, generated by the front end.

Every declaration below was translated into a `Term`, which is terminating by construction; what these checks add is that it computes the *same function* as the Lean declaration it came from.  A recursion whose measure fails to descend at a self call answers `stuck`, so a measure the front end read wrongly shows up here as a disagreement rather than as a silent wrong answer later.
-/

import SnapshotsMy.AssignStepsProgram
import SnapshotsMy.AssignSteps

open LakeJs LakeJs.Expr ProgramSnapshotsMyAssignSteps

namespace AutoCheckSnapshotsMyAssignSteps

/-- `test1`, as the emitted term computes it. -/
def run_test1 (a0 : Nat) (a1 : Nat) (a2 : Nat) : Nat :=
  Program.run Program.nil tm_test1 a0 a1 a2

/-- The emitted term and `test1` agree on the sample. -/
theorem test1_agrees :
    [run_test1 0 0 0, run_test1 1 0 0, run_test1 2 0 0, run_test1 0 1 0, run_test1 1 1 0, run_test1 2 1 0, run_test1 0 2 0, run_test1 1 2 0, run_test1 2 2 0, run_test1 0 0 1, run_test1 1 0 1, run_test1 2 0 1, run_test1 0 1 1, run_test1 1 1 1, run_test1 2 1 1, run_test1 0 2 1, run_test1 1 2 1, run_test1 2 2 1, run_test1 0 0 2, run_test1 1 0 2, run_test1 2 0 2, run_test1 0 1 2, run_test1 1 1 2, run_test1 2 1 2, run_test1 0 2 2, run_test1 1 2 2, run_test1 2 2 2] =
      [_root_.test1 0 0 0, _root_.test1 1 0 0, _root_.test1 2 0 0, _root_.test1 0 1 0, _root_.test1 1 1 0, _root_.test1 2 1 0, _root_.test1 0 2 0, _root_.test1 1 2 0, _root_.test1 2 2 0, _root_.test1 0 0 1, _root_.test1 1 0 1, _root_.test1 2 0 1, _root_.test1 0 1 1, _root_.test1 1 1 1, _root_.test1 2 1 1, _root_.test1 0 2 1, _root_.test1 1 2 1, _root_.test1 2 2 1, _root_.test1 0 0 2, _root_.test1 1 0 2, _root_.test1 2 0 2, _root_.test1 0 1 2, _root_.test1 1 1 2, _root_.test1 2 1 2, _root_.test1 0 2 2, _root_.test1 1 2 2, _root_.test1 2 2 2] := by native_decide

/-- `test4`, as the emitted term computes it. -/
def run_test4 (a0 : Nat) (a1 : Nat) (a2 : Nat) : Nat :=
  Program.run prog_test2 tm_test4 a0 a1 a2

/-- The emitted term and `test4` agree on the sample. -/
theorem test4_agrees :
    [run_test4 0 0 0, run_test4 1 0 0, run_test4 2 0 0, run_test4 0 1 0, run_test4 1 1 0, run_test4 2 1 0, run_test4 0 2 0, run_test4 1 2 0, run_test4 2 2 0, run_test4 0 0 1, run_test4 1 0 1, run_test4 2 0 1, run_test4 0 1 1, run_test4 1 1 1, run_test4 2 1 1, run_test4 0 2 1, run_test4 1 2 1, run_test4 2 2 1, run_test4 0 0 2, run_test4 1 0 2, run_test4 2 0 2, run_test4 0 1 2, run_test4 1 1 2, run_test4 2 1 2, run_test4 0 2 2, run_test4 1 2 2, run_test4 2 2 2] =
      [_root_.test4 0 0 0, _root_.test4 1 0 0, _root_.test4 2 0 0, _root_.test4 0 1 0, _root_.test4 1 1 0, _root_.test4 2 1 0, _root_.test4 0 2 0, _root_.test4 1 2 0, _root_.test4 2 2 0, _root_.test4 0 0 1, _root_.test4 1 0 1, _root_.test4 2 0 1, _root_.test4 0 1 1, _root_.test4 1 1 1, _root_.test4 2 1 1, _root_.test4 0 2 1, _root_.test4 1 2 1, _root_.test4 2 2 1, _root_.test4 0 0 2, _root_.test4 1 0 2, _root_.test4 2 0 2, _root_.test4 0 1 2, _root_.test4 1 1 2, _root_.test4 2 1 2, _root_.test4 0 2 2, _root_.test4 1 2 2, _root_.test4 2 2 2] := by native_decide

/-- `Nat.gcd`, as the emitted term computes it. -/
def run_Nat_gcd (a0 : Nat) (a1 : Nat) : Nat :=
  Program.run prog_test4 tm_Nat_gcd a0 a1

/-- The emitted term and `Nat.gcd` agree on the sample. -/
theorem Nat_gcd_agrees :
    [run_Nat_gcd 0 0, run_Nat_gcd 1 0, run_Nat_gcd 2 0, run_Nat_gcd 3 0, run_Nat_gcd 0 1, run_Nat_gcd 1 1, run_Nat_gcd 2 1, run_Nat_gcd 3 1, run_Nat_gcd 0 2, run_Nat_gcd 1 2, run_Nat_gcd 2 2, run_Nat_gcd 3 2, run_Nat_gcd 0 3, run_Nat_gcd 1 3, run_Nat_gcd 2 3, run_Nat_gcd 3 3] =
      [_root_.Nat.gcd 0 0, _root_.Nat.gcd 1 0, _root_.Nat.gcd 2 0, _root_.Nat.gcd 3 0, _root_.Nat.gcd 0 1, _root_.Nat.gcd 1 1, _root_.Nat.gcd 2 1, _root_.Nat.gcd 3 1, _root_.Nat.gcd 0 2, _root_.Nat.gcd 1 2, _root_.Nat.gcd 2 2, _root_.Nat.gcd 3 2, _root_.Nat.gcd 0 3, _root_.Nat.gcd 1 3, _root_.Nat.gcd 2 3, _root_.Nat.gcd 3 3] := by native_decide

/-- `test3`, as the emitted term computes it. -/
def run_test3 (a0 : Nat) (a1 : Nat) (a2 : Nat) : Nat :=
  Program.run prog_Nat_gcd tm_test3 a0 a1 a2

/-- The emitted term and `test3` agree on the sample. -/
theorem test3_agrees :
    [run_test3 0 0 0, run_test3 1 0 0, run_test3 2 0 0, run_test3 0 1 0, run_test3 1 1 0, run_test3 2 1 0, run_test3 0 2 0, run_test3 1 2 0, run_test3 2 2 0, run_test3 0 0 1, run_test3 1 0 1, run_test3 2 0 1, run_test3 0 1 1, run_test3 1 1 1, run_test3 2 1 1, run_test3 0 2 1, run_test3 1 2 1, run_test3 2 2 1, run_test3 0 0 2, run_test3 1 0 2, run_test3 2 0 2, run_test3 0 1 2, run_test3 1 1 2, run_test3 2 1 2, run_test3 0 2 2, run_test3 1 2 2, run_test3 2 2 2] =
      [_root_.test3 0 0 0, _root_.test3 1 0 0, _root_.test3 2 0 0, _root_.test3 0 1 0, _root_.test3 1 1 0, _root_.test3 2 1 0, _root_.test3 0 2 0, _root_.test3 1 2 0, _root_.test3 2 2 0, _root_.test3 0 0 1, _root_.test3 1 0 1, _root_.test3 2 0 1, _root_.test3 0 1 1, _root_.test3 1 1 1, _root_.test3 2 1 1, _root_.test3 0 2 1, _root_.test3 1 2 1, _root_.test3 2 2 1, _root_.test3 0 0 2, _root_.test3 1 0 2, _root_.test3 2 0 2, _root_.test3 0 1 2, _root_.test3 1 1 2, _root_.test3 2 1 2, _root_.test3 0 2 2, _root_.test3 1 2 2, _root_.test3 2 2 2] := by native_decide

end AutoCheckSnapshotsMyAssignSteps
