/-
The verification condition of every recursion of `SnapshotsMy.AssignSteps`, generated by the front end.

`Term.Descends measure body δ γ ρ` says that the body consults its self-reference only at arguments of strictly smaller measure.  From it, `LakeJs.Descends` derives that the `stuck` branch is never taken and that the recursion satisfies the ordinary unrolling equation — so this file is the statement that the measure the front end read off Lean's `termination_by` (or off the structure of the recursion subject) is *right*, checked on the emitted term rather than on the Lean source it came from.

Each proof is one call of `descent_auto`, which assembles the derivation from the rules of `LakeJs.DescentVC` and closes the arithmetic each self call leaves.
-/

import SnapshotsMy.AssignStepsProgram

open LakeJs LakeJs.Ty LakeJs.Expr LakeJs.Expr.Ops ProgramSnapshotsMyAssignSteps

-- the statements mention whole emitted bodies, and the tactic runs the interpreter over them, so both are well past the default budget
set_option maxHeartbeats 2000000

namespace DescendsSnapshotsMyAssignSteps

/-- **The verification condition of `test1`**: every self call of `bd_test1` is made at arguments of strictly smaller measure — the measure written out here is the one `tm_test1` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm_test1_descends (δ : GEnv sig_test1.decls) :
    Term.Descends (Sg := sig_test1) (Γ := []) (Ρ := []) (ps := [Ty.nat, Ty.nat, Ty.nat]) (τ := Ty.nat) (k := 1)
      (.cons (♯0) .nil)
      bd_test1 δ .nil .nil := by
  descent_auto as

/-- **The verification condition of `test2`**: every self call of `bd_test2` is made at arguments of strictly smaller measure — the measure written out here is the one `tm_test2` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm_test2_descends (δ : GEnv sig_test2.decls) :
    Term.Descends (Sg := sig_test2) (Γ := []) (Ρ := []) (ps := [Ty.nat, Ty.nat, Ty.nat, Ty.nat]) (τ := Ty.nat) (k := 1)
      (.cons (♯0) .nil)
      bd_test2 δ .nil .nil := by
  descent_auto as

/-- **The verification condition of `test4`**: every self call of `bd_test4` is made at arguments of strictly smaller measure — the measure written out here is the one `tm_test4` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm_test4_descends (δ : GEnv sig_test4.decls) :
    Term.Descends (Sg := sig_test4) (Γ := []) (Ρ := []) (ps := [Ty.nat, Ty.nat, Ty.nat]) (τ := Ty.nat) (k := 1)
      (.cons (♯0) .nil)
      bd_test4 δ .nil .nil := by
  descent_auto as

/-- **The verification condition of `Nat.gcd`**: every self call of `bd_Nat_gcd` is made at arguments of strictly smaller measure — the measure written out here is the one `tm_Nat_gcd` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm_Nat_gcd_descends (δ : GEnv sig_Nat_gcd.decls) :
    Term.Descends (Sg := sig_Nat_gcd) (Γ := []) (Ρ := []) (ps := [Ty.nat, Ty.nat]) (τ := Ty.nat) (k := 1)
      (.cons (♯0) .nil)
      bd_Nat_gcd δ .nil .nil := by
  descent_auto as

/-- **The verification condition of `test3`**: every self call of `bd_test3` is made at arguments of strictly smaller measure — the measure written out here is the one `tm_test3` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm_test3_descends (δ : GEnv sig_test3.decls) :
    Term.Descends (Sg := sig_test3) (Γ := []) (Ρ := []) (ps := [Ty.nat, Ty.nat, Ty.nat]) (τ := Ty.nat) (k := 1)
      (.cons (♯0) .nil)
      bd_test3 δ .nil .nil := by
  descent_auto as

end DescendsSnapshotsMyAssignSteps
