/-
Differential checks for `SnapshotsMy.GcdEntry`, generated by the front end.

Every declaration below was translated into a `Term`, which is terminating by construction; what these checks add is that it computes the *same function* as the Lean declaration it came from.  A recursion whose measure fails to descend at a self call answers `stuck`, so a measure the front end read wrongly shows up here as a disagreement rather than as a silent wrong answer later.
-/

import SnapshotsMy.GcdEntryProgram
import SnapshotsMy.GcdEntry

open LakeJs LakeJs.Expr ProgramSnapshotsMyGcdEntry

namespace AutoCheckSnapshotsMyGcdEntry

/-- `Nat.gcd`, as the emitted term computes it. -/
def run_Nat_gcd (a0 : Nat) (a1 : Nat) : Nat :=
  Program.run Program.nil tm_Nat_gcd a0 a1

/-- The emitted term and `Nat.gcd` agree on the sample. -/
theorem Nat_gcd_agrees :
    [run_Nat_gcd 0 0, run_Nat_gcd 1 0, run_Nat_gcd 2 0, run_Nat_gcd 3 0, run_Nat_gcd 0 1, run_Nat_gcd 1 1, run_Nat_gcd 2 1, run_Nat_gcd 3 1, run_Nat_gcd 0 2, run_Nat_gcd 1 2, run_Nat_gcd 2 2, run_Nat_gcd 3 2, run_Nat_gcd 0 3, run_Nat_gcd 1 3, run_Nat_gcd 2 3, run_Nat_gcd 3 3] =
      [_root_.Nat.gcd 0 0, _root_.Nat.gcd 1 0, _root_.Nat.gcd 2 0, _root_.Nat.gcd 3 0, _root_.Nat.gcd 0 1, _root_.Nat.gcd 1 1, _root_.Nat.gcd 2 1, _root_.Nat.gcd 3 1, _root_.Nat.gcd 0 2, _root_.Nat.gcd 1 2, _root_.Nat.gcd 2 2, _root_.Nat.gcd 3 2, _root_.Nat.gcd 0 3, _root_.Nat.gcd 1 3, _root_.Nat.gcd 2 3, _root_.Nat.gcd 3 3] := by native_decide

/-- `gcd2`, as the emitted term computes it. -/
def run_gcd2 (a0 : Nat) (a1 : Nat) : Nat :=
  Program.run prog_Nat_gcd tm_gcd2 a0 a1

/-- The emitted term and `gcd2` agree on the sample. -/
theorem gcd2_agrees :
    [run_gcd2 0 0, run_gcd2 1 0, run_gcd2 2 0, run_gcd2 3 0, run_gcd2 0 1, run_gcd2 1 1, run_gcd2 2 1, run_gcd2 3 1, run_gcd2 0 2, run_gcd2 1 2, run_gcd2 2 2, run_gcd2 3 2, run_gcd2 0 3, run_gcd2 1 3, run_gcd2 2 3, run_gcd2 3 3] =
      [_root_.gcd2 0 0, _root_.gcd2 1 0, _root_.gcd2 2 0, _root_.gcd2 3 0, _root_.gcd2 0 1, _root_.gcd2 1 1, _root_.gcd2 2 1, _root_.gcd2 3 1, _root_.gcd2 0 2, _root_.gcd2 1 2, _root_.gcd2 2 2, _root_.gcd2 3 2, _root_.gcd2 0 3, _root_.gcd2 1 3, _root_.gcd2 2 3, _root_.gcd2 3 3] := by native_decide

end AutoCheckSnapshotsMyGcdEntry
