/-
The verification condition of every recursion of `SnapshotsMy.MutualTail`, generated by the front end.

`Term.Descends measure body δ γ ρ` says that the body consults its self-reference only at arguments of strictly smaller measure.  From it, `LakeJs.Descends` derives that the `stuck` branch is never taken and that the recursion satisfies the ordinary unrolling equation — so this file is the statement that the measure the front end read off Lean's `termination_by` (or off the structure of the recursion subject) is *right*, checked on the emitted term rather than on the Lean source it came from.

Each proof is one call of `descent_auto`, which assembles the derivation from the rules of `LakeJs.DescentVC` and closes the arithmetic each self call leaves.
-/

import SnapshotsMy.MutualTailProgram

open LakeJs LakeJs.Ty LakeJs.Expr LakeJs.Expr.Ops ProgramSnapshotsMyMutualTail

-- the statements mention whole emitted bodies, and the tactic runs the interpreter over them, so both are well past the default budget
set_option maxHeartbeats 2000000

namespace DescendsSnapshotsMyMutualTail

/-- **The verification condition of `test1 & test2 (clique)`**: every self call of `bd_test1___test2__clique_` is made at arguments of strictly smaller measure — the measure written out here is the one `tm_test1___test2__clique_` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm_test1___test2__clique__descends (δ : GEnv sig_test1___test2__clique_.decls) :
    Term.Descends (Sg := sig_test1___test2__clique_) (Γ := []) (Ρ := []) (ps := [Ty.nat, Ty.nat, Ty.nat]) (τ := Ty.bool) (k := 2)
      (.cons (Term.ite (natEq (♯0) (Term.natL 0)) (♯1) (♯2)) (.cons (natSub (Term.natL 1) (♯0)) .nil))
      bd_test1___test2__clique_ δ .nil .nil := by
  descent_auto as

/-- **The verification condition of `test3 & test4 & test5 (clique)`**: every self call of `bd_test3___test4___test5__clique_` is made at arguments of strictly smaller measure — the measure written out here is the one `tm_test3___test4___test5__clique_` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm_test3___test4___test5__clique__descends (δ : GEnv sig_test3___test4___test5__clique_.decls) :
    Term.Descends (Sg := sig_test3___test4___test5__clique_) (Γ := []) (Ρ := []) (ps := [Ty.nat, Ty.nat, Ty.nat, Ty.nat, Ty.nat, Ty.nat, Ty.nat, Ty.nat]) (τ := Ty.nat) (k := 2)
      (.cons (Term.ite (natEq (♯0) (Term.natL 0)) (♯1) (Term.ite (natEq (♯0) (Term.natL 1)) (♯3) (♯6))) (.cons (natSub (Term.natL 2) (♯0)) .nil))
      bd_test3___test4___test5__clique_ δ .nil .nil := by
  descent_auto as

end DescendsSnapshotsMyMutualTail
