/-
Differential checks for `SnapshotsMy.MutualSlots`, generated by the front end.

Every declaration below was translated into a `Term`, which is terminating by construction; what these checks add is that it computes the *same function* as the Lean declaration it came from.  A recursion whose measure fails to descend at a self call answers `stuck`, so a measure the front end read wrongly shows up here as a disagreement rather than as a silent wrong answer later.
-/

import SnapshotsMy.MutualSlotsProgram
import SnapshotsMy.MutualSlots

open LakeJs LakeJs.Expr ProgramSnapshotsMyMutualSlots

namespace AutoCheckSnapshotsMyMutualSlots

/-- `walkNat`, as the emitted term computes it. -/
def run_walkNat (a0 : Nat) (a1 : Nat) : Nat :=
  Program.run prog_walkStr tm_walkNat a0 a1

/-- The emitted term and `walkNat` agree on the sample. -/
theorem walkNat_agrees :
    [run_walkNat 0 0, run_walkNat 1 0, run_walkNat 2 0, run_walkNat 3 0, run_walkNat 0 1, run_walkNat 1 1, run_walkNat 2 1, run_walkNat 3 1, run_walkNat 0 2, run_walkNat 1 2, run_walkNat 2 2, run_walkNat 3 2, run_walkNat 0 3, run_walkNat 1 3, run_walkNat 2 3, run_walkNat 3 3] =
      [_root_.walkNat 0 0, _root_.walkNat 1 0, _root_.walkNat 2 0, _root_.walkNat 3 0, _root_.walkNat 0 1, _root_.walkNat 1 1, _root_.walkNat 2 1, _root_.walkNat 3 1, _root_.walkNat 0 2, _root_.walkNat 1 2, _root_.walkNat 2 2, _root_.walkNat 3 2, _root_.walkNat 0 3, _root_.walkNat 1 3, _root_.walkNat 2 3, _root_.walkNat 3 3] := by native_decide

end AutoCheckSnapshotsMyMutualSlots
