/-
The verification condition of every recursion of `SnapshotsMy.ScalarRepl`, generated by the front end.

`Term.Descends measure body δ γ ρ` says that the body consults its self-reference only at arguments of strictly smaller measure.  From it, `LakeJs.Descends` derives that the `stuck` branch is never taken and that the recursion satisfies the ordinary unrolling equation — so this file is the statement that the measure the front end read off Lean's `termination_by` (or off the structure of the recursion subject) is *right*, checked on the emitted term rather than on the Lean source it came from.

Each proof is one call of `descent_auto`, which assembles the derivation from the rules of `LakeJs.DescentVC` and closes the arithmetic each self call leaves.
-/

import SnapshotsMy.ScalarReplProgram

open LakeJs LakeJs.Ty LakeJs.Expr LakeJs.Expr.Ops ProgramSnapshotsMyScalarRepl

-- the statements mention whole emitted bodies, and the tactic runs the interpreter over them, so both are well past the default budget
set_option maxHeartbeats 2000000

namespace DescendsSnapshotsMyScalarRepl

/-- **The verification condition of `_private.Init.Data.Range.Basic.0.Std.Legacy.Range.forIn'.loop._at_.test1.spec_0`**: every self call of `bd__private_Init_Data_Range_Basic_0_Std_Legacy_Range_forIn__loop__at__test1_spec_0` is made at arguments of strictly smaller measure — the measure written out here is the one `tm__private_Init_Data_Range_Basic_0_Std_Legacy_Range_forIn__loop__at__test1_spec_0` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm__private_Init_Data_Range_Basic_0_Std_Legacy_Range_forIn__loop__at__test1_spec_0_descends (δ : GEnv sig__private_Init_Data_Range_Basic_0_Std_Legacy_Range_forIn__loop__at__test1_spec_0.decls) :
    Term.Descends (Sg := sig__private_Init_Data_Range_Basic_0_Std_Legacy_Range_forIn__loop__at__test1_spec_0) (Γ := []) (Ρ := []) (ps := [(Ty.record ⟨Ty.nat, Ty.nat, [Ty.nat]⟩), Ty.nat, Ty.nat]) (τ := Ty.nat) (k := 1)
      (.cons (natSub (Term.proj (♯0) 0 1 (by rfl) (by rfl)) (♯2)) .nil)
      bd__private_Init_Data_Range_Basic_0_Std_Legacy_Range_forIn__loop__at__test1_spec_0 δ .nil .nil := by
  descent_auto as

/-- **The verification condition of `_private.SnapshotsMy.ScalarRepl.0.clampSum`**: every self call of `bd__private_SnapshotsMy_ScalarRepl_0_clampSum` is made at arguments of strictly smaller measure — the measure written out here is the one `tm__private_SnapshotsMy_ScalarRepl_0_clampSum` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm__private_SnapshotsMy_ScalarRepl_0_clampSum_descends (δ : GEnv sig__private_SnapshotsMy_ScalarRepl_0_clampSum.decls) :
    Term.Descends (Sg := sig__private_SnapshotsMy_ScalarRepl_0_clampSum) (Γ := []) (Ρ := []) (ps := [(Ty.record ⟨Ty.nat, Ty.nat, []⟩), Ty.nat, Ty.nat]) (τ := Ty.nat) (k := 1)
      (.cons (♯1) .nil)
      bd__private_SnapshotsMy_ScalarRepl_0_clampSum δ .nil .nil := by
  descent_auto as

/-- **The verification condition of `_private.Init.Data.Range.Basic.0.Std.Legacy.Range.forIn'.loop._at_.test2.spec_0`**: every self call of `bd__private_Init_Data_Range_Basic_0_Std_Legacy_Range_forIn__loop__at__test2_spec_0` is made at arguments of strictly smaller measure — the measure written out here is the one `tm__private_Init_Data_Range_Basic_0_Std_Legacy_Range_forIn__loop__at__test2_spec_0` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm__private_Init_Data_Range_Basic_0_Std_Legacy_Range_forIn__loop__at__test2_spec_0_descends (δ : GEnv sig__private_Init_Data_Range_Basic_0_Std_Legacy_Range_forIn__loop__at__test2_spec_0.decls) :
    Term.Descends (Sg := sig__private_Init_Data_Range_Basic_0_Std_Legacy_Range_forIn__loop__at__test2_spec_0) (Γ := []) (Ρ := []) (ps := [Ty.nat, Ty.nat, (Ty.record ⟨Ty.nat, Ty.nat, [Ty.nat]⟩), Ty.nat, Ty.nat]) (τ := Ty.nat) (k := 1)
      (.cons (natSub (Term.proj (♯2) 0 1 (by rfl) (by rfl)) (♯4)) .nil)
      bd__private_Init_Data_Range_Basic_0_Std_Legacy_Range_forIn__loop__at__test2_spec_0 δ .nil .nil := by
  descent_auto as

end DescendsSnapshotsMyScalarRepl
