/-
Differential checks for `SnapshotsMy.ScalarRepl`, generated by the front end.

Every declaration below was translated into a `Term`, which is terminating by construction; what these checks add is that it computes the *same function* as the Lean declaration it came from.  A recursion whose measure fails to descend at a self call answers `stuck`, so a measure the front end read wrongly shows up here as a disagreement rather than as a silent wrong answer later.
-/

import SnapshotsMy.ScalarReplProgram
import SnapshotsMy.ScalarRepl

open LakeJs LakeJs.Expr ProgramSnapshotsMyScalarRepl

namespace AutoCheckSnapshotsMyScalarRepl

/-- `test1`, as the emitted term computes it. -/
def run_test1 (a0 : Nat) : Nat :=
  Program.run prog__private_SnapshotsMy_ScalarRepl_0_clampSum tm_test1 a0

/-- The emitted term and `test1` agree on the sample. -/
theorem test1_agrees :
    [run_test1 0, run_test1 1, run_test1 2, run_test1 3, run_test1 4, run_test1 5, run_test1 6, run_test1 9] =
      [_root_.test1 0, _root_.test1 1, _root_.test1 2, _root_.test1 3, _root_.test1 4, _root_.test1 5, _root_.test1 6, _root_.test1 9] := by native_decide

/-- `test3`, as the emitted term computes it. -/
def run_test3 (a0 : Nat) (a1 : Nat) : Nat :=
  Program.run prog_test1 tm_test3 a0 a1

/-- The emitted term and `test3` agree on the sample. -/
theorem test3_agrees :
    [run_test3 0 0, run_test3 1 0, run_test3 2 0, run_test3 3 0, run_test3 0 1, run_test3 1 1, run_test3 2 1, run_test3 3 1, run_test3 0 2, run_test3 1 2, run_test3 2 2, run_test3 3 2, run_test3 0 3, run_test3 1 3, run_test3 2 3, run_test3 3 3] =
      [_root_.test3 0 0, _root_.test3 1 0, _root_.test3 2 0, _root_.test3 3 0, _root_.test3 0 1, _root_.test3 1 1, _root_.test3 2 1, _root_.test3 3 1, _root_.test3 0 2, _root_.test3 1 2, _root_.test3 2 2, _root_.test3 3 2, _root_.test3 0 3, _root_.test3 1 3, _root_.test3 2 3, _root_.test3 3 3] := by native_decide

/-- `test5`, as the emitted term computes it. -/
def run_test5 (a0 : Nat) (a1 : Nat) : Nat :=
  Program.run prog_test4 tm_test5 a0 a1

/-- The emitted term and `test5` agree on the sample. -/
theorem test5_agrees :
    [run_test5 0 0, run_test5 1 0, run_test5 2 0, run_test5 3 0, run_test5 0 1, run_test5 1 1, run_test5 2 1, run_test5 3 1, run_test5 0 2, run_test5 1 2, run_test5 2 2, run_test5 3 2, run_test5 0 3, run_test5 1 3, run_test5 2 3, run_test5 3 3] =
      [_root_.test5 0 0, _root_.test5 1 0, _root_.test5 2 0, _root_.test5 3 0, _root_.test5 0 1, _root_.test5 1 1, _root_.test5 2 1, _root_.test5 3 1, _root_.test5 0 2, _root_.test5 1 2, _root_.test5 2 2, _root_.test5 3 2, _root_.test5 0 3, _root_.test5 1 3, _root_.test5 2 3, _root_.test5 3 3] := by native_decide

/-- `test6`, as the emitted term computes it. -/
def run_test6 (a0 : Nat) : Nat :=
  Program.run prog_test5 tm_test6 a0

/-- The emitted term and `test6` agree on the sample. -/
theorem test6_agrees :
    [run_test6 0, run_test6 1, run_test6 2, run_test6 3, run_test6 4, run_test6 5, run_test6 6, run_test6 9] =
      [_root_.test6 0, _root_.test6 1, _root_.test6 2, _root_.test6 3, _root_.test6 4, _root_.test6 5, _root_.test6 6, _root_.test6 9] := by native_decide

/-- `test2`, as the emitted term computes it. -/
def run_test2 (a0 : Nat) : Nat :=
  Program.run prog__private_Init_Data_Range_Basic_0_Std_Legacy_Range_forIn__loop__at__test2_spec_0 tm_test2 a0

/-- The emitted term and `test2` agree on the sample. -/
theorem test2_agrees :
    [run_test2 0, run_test2 1, run_test2 2, run_test2 3, run_test2 4, run_test2 5, run_test2 6, run_test2 9] =
      [_root_.test2 0, _root_.test2 1, _root_.test2 2, _root_.test2 3, _root_.test2 4, _root_.test2 5, _root_.test2 6, _root_.test2 9] := by native_decide

end AutoCheckSnapshotsMyScalarRepl
