/-
Differential checks for `SnapshotsMy.Tco09`, generated by the front end.

Every declaration below was translated into a `Term`, which is terminating by construction; what these checks add is that it computes the *same function* as the Lean declaration it came from.  A recursion whose measure fails to descend at a self call answers `stuck`, so a measure the front end read wrongly shows up here as a disagreement rather than as a silent wrong answer later.
-/

import SnapshotsMy.Tco09Program
import SnapshotsMy.Tco09

open LakeJs LakeJs.Expr ProgramSnapshotsMyTco09

namespace AutoCheckSnapshotsMyTco09

/-- `ackRev`, as the emitted term computes it. -/
def run_ackRev (a0 : Nat) (a1 : Nat) : Nat :=
  Program.run Program.nil tm_ackRev a0 a1

/-- The emitted term and `ackRev` agree on the sample. -/
theorem ackRev_agrees :
    [run_ackRev 0 0, run_ackRev 1 0, run_ackRev 2 0, run_ackRev 3 0, run_ackRev 0 1, run_ackRev 1 1, run_ackRev 2 1, run_ackRev 3 1, run_ackRev 0 2, run_ackRev 1 2, run_ackRev 2 2, run_ackRev 3 2, run_ackRev 0 3, run_ackRev 1 3, run_ackRev 2 3, run_ackRev 3 3] =
      [_root_.ackRev 0 0, _root_.ackRev 1 0, _root_.ackRev 2 0, _root_.ackRev 3 0, _root_.ackRev 0 1, _root_.ackRev 1 1, _root_.ackRev 2 1, _root_.ackRev 3 1, _root_.ackRev 0 2, _root_.ackRev 1 2, _root_.ackRev 2 2, _root_.ackRev 3 2, _root_.ackRev 0 3, _root_.ackRev 1 3, _root_.ackRev 2 3, _root_.ackRev 3 3] := by native_decide

/-- `diagonal`, as the emitted term computes it. -/
def run_diagonal (a0 : Nat) (a1 : Nat) : Nat :=
  Program.run prog_ackRev tm_diagonal a0 a1

/-- The emitted term and `diagonal` agree on the sample. -/
theorem diagonal_agrees :
    [run_diagonal 0 0, run_diagonal 1 0, run_diagonal 2 0, run_diagonal 3 0, run_diagonal 0 1, run_diagonal 1 1, run_diagonal 2 1, run_diagonal 3 1, run_diagonal 0 2, run_diagonal 1 2, run_diagonal 2 2, run_diagonal 3 2, run_diagonal 0 3, run_diagonal 1 3, run_diagonal 2 3, run_diagonal 3 3] =
      [_root_.diagonal 0 0, _root_.diagonal 1 0, _root_.diagonal 2 0, _root_.diagonal 3 0, _root_.diagonal 0 1, _root_.diagonal 1 1, _root_.diagonal 2 1, _root_.diagonal 3 1, _root_.diagonal 0 2, _root_.diagonal 1 2, _root_.diagonal 2 2, _root_.diagonal 3 2, _root_.diagonal 0 3, _root_.diagonal 1 3, _root_.diagonal 2 3, _root_.diagonal 3 3] := by native_decide

/-- `hyper`, as the emitted term computes it. -/
def run_hyper (a0 : Nat) (a1 : Nat) (a2 : Nat) : Nat :=
  Program.run prog_diagonal tm_hyper a0 a1 a2

/-- The emitted term and `hyper` agree on the sample. -/
theorem hyper_agrees :
    [run_hyper 0 0 0, run_hyper 1 0 0, run_hyper 2 0 0, run_hyper 0 1 0, run_hyper 1 1 0, run_hyper 2 1 0, run_hyper 0 2 0, run_hyper 1 2 0, run_hyper 2 2 0, run_hyper 0 0 1, run_hyper 1 0 1, run_hyper 2 0 1, run_hyper 0 1 1, run_hyper 1 1 1, run_hyper 2 1 1, run_hyper 0 2 1, run_hyper 1 2 1, run_hyper 2 2 1, run_hyper 0 0 2, run_hyper 1 0 2, run_hyper 2 0 2, run_hyper 0 1 2, run_hyper 1 1 2, run_hyper 2 1 2, run_hyper 0 2 2, run_hyper 1 2 2, run_hyper 2 2 2] =
      [_root_.hyper 0 0 0, _root_.hyper 1 0 0, _root_.hyper 2 0 0, _root_.hyper 0 1 0, _root_.hyper 1 1 0, _root_.hyper 2 1 0, _root_.hyper 0 2 0, _root_.hyper 1 2 0, _root_.hyper 2 2 0, _root_.hyper 0 0 1, _root_.hyper 1 0 1, _root_.hyper 2 0 1, _root_.hyper 0 1 1, _root_.hyper 1 1 1, _root_.hyper 2 1 1, _root_.hyper 0 2 1, _root_.hyper 1 2 1, _root_.hyper 2 2 1, _root_.hyper 0 0 2, _root_.hyper 1 0 2, _root_.hyper 2 0 2, _root_.hyper 0 1 2, _root_.hyper 1 1 2, _root_.hyper 2 1 2, _root_.hyper 0 2 2, _root_.hyper 1 2 2, _root_.hyper 2 2 2] := by native_decide

/-- `Mc91`, as the emitted term computes it. -/
def run_Mc91 (a0 : Nat) : Nat :=
  Program.run prog_Mc91_M tm_Mc91 a0

/-- The emitted term and `Mc91` agree on the sample. -/
theorem Mc91_agrees :
    [run_Mc91 0, run_Mc91 1, run_Mc91 2, run_Mc91 3, run_Mc91 4, run_Mc91 5, run_Mc91 6, run_Mc91 9] =
      [_root_.Mc91 0, _root_.Mc91 1, _root_.Mc91 2, _root_.Mc91 3, _root_.Mc91 4, _root_.Mc91 5, _root_.Mc91 6, _root_.Mc91 9] := by native_decide

end AutoCheckSnapshotsMyTco09
