/-
The verification condition of every recursion of `SnapshotsMy.Tco09`, generated by the front end.

`Term.Descends measure body δ γ ρ` says that the body consults its self-reference only at arguments of strictly smaller measure.  From it, `LakeJs.Descends` derives that the `stuck` branch is never taken and that the recursion satisfies the ordinary unrolling equation — so this file is the statement that the measure the front end read off Lean's `termination_by` (or off the structure of the recursion subject) is *right*, checked on the emitted term rather than on the Lean source it came from.

Each proof is one call of `descent_auto`, which assembles the derivation from the rules of `LakeJs.DescentVC` and closes the arithmetic each self call leaves.
-/

import SnapshotsMy.Tco09Program

open LakeJs LakeJs.Ty LakeJs.Expr LakeJs.Expr.Ops ProgramSnapshotsMyTco09

-- the statements mention whole emitted bodies, and the tactic runs the interpreter over them, so both are well past the default budget
set_option maxHeartbeats 2000000

namespace DescendsSnapshotsMyTco09

/-- **The verification condition of `ackRev`**: every self call of `bd_ackRev` is made at arguments of strictly smaller measure — the measure written out here is the one `tm_ackRev` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm_ackRev_descends (δ : GEnv sig_ackRev.decls) :
    Term.Descends (Sg := sig_ackRev) (Γ := []) (Ρ := []) (ps := [Ty.nat, Ty.nat]) (τ := Ty.nat) (k := 2)
      (.cons (♯1) (.cons (♯0) .nil))
      bd_ackRev δ .nil .nil := by
  descent_auto as

/-- **The verification condition of `diagonal`**: every self call of `bd_diagonal` is made at arguments of strictly smaller measure — the measure written out here is the one `tm_diagonal` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm_diagonal_descends (δ : GEnv sig_diagonal.decls) :
    Term.Descends (Sg := sig_diagonal) (Γ := []) (Ρ := []) (ps := [Ty.nat, Ty.nat]) (τ := Ty.nat) (k := 2)
      (.cons (natAdd (♯0) (♯1)) (.cons (♯0) .nil))
      bd_diagonal δ .nil .nil := by
  descent_auto as

/-- **The verification condition of `hyper`**: every self call of `bd_hyper` is made at arguments of strictly smaller measure — the measure written out here is the one `tm_hyper` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm_hyper_descends (δ : GEnv sig_hyper.decls) :
    Term.Descends (Sg := sig_hyper) (Γ := []) (Ρ := []) (ps := [Ty.nat, Ty.nat, Ty.nat]) (τ := Ty.nat) (k := 2)
      (.cons (♯0) (.cons (♯2) .nil))
      bd_hyper δ .nil .nil := by
  descent_auto as

/-- **The verification condition of `Mc91.M`**: every self call of `bd_Mc91_M` is made at arguments of strictly smaller measure — the measure written out here is the one `tm_Mc91_M` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm_Mc91_M_descends (δ : GEnv sig_Mc91_M.decls) :
    Term.Descends (Sg := sig_Mc91_M) (Γ := []) (Ρ := []) (ps := [Ty.nat]) (τ := Ty.nat) (k := 1)
      (.cons (natSub (Term.natL 101) (♯0)) .nil)
      bd_Mc91_M δ .nil .nil := by
  descent_auto as

end DescendsSnapshotsMyTco09
