/-
Differential checks for `SnapshotsMy.Tco08`, generated by the front end.

Every declaration below was translated into a `Term`, which is terminating by construction; what these checks add is that it computes the *same function* as the Lean declaration it came from.  A recursion whose measure fails to descend at a self call answers `stuck`, so a measure the front end read wrongly shows up here as a disagreement rather than as a silent wrong answer later.
-/

import SnapshotsMy.Tco08Program
import SnapshotsMy.Tco08

open LakeJs LakeJs.Expr ProgramSnapshotsMyTco08

namespace AutoCheckSnapshotsMyTco08

/-- `ack`, as the emitted term computes it. -/
def run_ack (a0 : Nat) (a1 : Nat) : Nat :=
  Program.run Program.nil tm_ack a0 a1

/-- The emitted term and `ack` agree on the sample. -/
theorem ack_agrees :
    [run_ack 0 0, run_ack 1 0, run_ack 2 0, run_ack 3 0, run_ack 0 1, run_ack 1 1, run_ack 2 1, run_ack 3 1, run_ack 0 2, run_ack 1 2, run_ack 2 2, run_ack 3 2, run_ack 0 3, run_ack 1 3, run_ack 2 3, run_ack 3 3] =
      [_root_.ack 0 0, _root_.ack 1 0, _root_.ack 2 0, _root_.ack 3 0, _root_.ack 0 1, _root_.ack 1 1, _root_.ack 2 1, _root_.ack 3 1, _root_.ack 0 2, _root_.ack 1 2, _root_.ack 2 2, _root_.ack 3 2, _root_.ack 0 3, _root_.ack 1 3, _root_.ack 2 3, _root_.ack 3 3] := by native_decide

end AutoCheckSnapshotsMyTco08
