/-
The verification condition of every recursion of `SnapshotsMy.Tco07`, generated by the front end.

`Term.Descends measure body δ γ ρ` says that the body consults its self-reference only at arguments of strictly smaller measure.  From it, `LakeJs.Descends` derives that the `stuck` branch is never taken and that the recursion satisfies the ordinary unrolling equation — so this file is the statement that the measure the front end read off Lean's `termination_by` (or off the structure of the recursion subject) is *right*, checked on the emitted term rather than on the Lean source it came from.

Each proof is one call of `descent_auto`, which assembles the derivation from the rules of `LakeJs.DescentVC` and closes the arithmetic each self call leaves.
-/

import SnapshotsMy.Tco07Program

open LakeJs LakeJs.Ty LakeJs.Expr LakeJs.Expr.Ops ProgramSnapshotsMyTco07

-- the statements mention whole emitted bodies, and the tactic runs the interpreter over them, so both are well past the default budget
set_option maxHeartbeats 2000000

namespace DescendsSnapshotsMyTco07

/-- **The verification condition of `boom`**: every self call of `bd_boom` is made at arguments of strictly smaller measure — the measure written out here is the one `tm_boom` carries — so its `stuck` branch is unreachable and the recursion satisfies the ordinary unrolling equation. -/
theorem tm_boom_descends (δ : GEnv sig_boom.decls) :
    Term.Descends (Sg := sig_boom) (Γ := []) (Ρ := []) (ps := [Ty.nat]) (τ := Ty.nat) (k := 1)
      (.cons (♯0) .nil)
      bd_boom δ .nil .nil := by
  descent_auto as

end DescendsSnapshotsMyTco07
