#!/usr/bin/env python3
"""Generate `LakeJs/FrontEndPrimExterns.lean` from the catalogue.

`LakeJs/LeanInitPureExterns.lean` lists the pure `@[extern]` functions of Lean's `Init`.
The families whose argument and result types are all terminal -- `LeanInitPureExtern1OnlyPrim`,
`LeanInitPureExtern2OnlyPrim`, `LeanInitPureExtern3OnlyPrim` and `LeanInitPureExtern5` --
are exactly the ones a call of a scalar runtime function goes to, and the constructor name
of each of them *is* the C symbol Lean's `@[extern]` attribute names.  So the front end can
look a call up by the C name the attribute gives it, and this table is that lookup, read off
the catalogue itself rather than written out by hand.

Run from the project root:

    python3 scripts/gen-prim-extern-table.py
"""

import re
import sys

SRC = "LakeJs/LeanInitPureExterns.lean"
OUT = "LakeJs/FrontEndPrimExterns.lean"

# The terminal types the front end has an `STy` for.  `usize` and `isize` are Lean
# abbreviations for `uint64` and `int64`, so they are the same type of the language.
TYPES = {
    "bool": ".bool",
    "nat": ".nat",
    "int": ".int",
    "string": ".string",
    "char": ".char",
    "uint8": "(.scalar .uint8)",
    "uint16": "(.scalar .uint16)",
    "uint32": "(.scalar .uint32)",
    "uint64": "(.scalar .uint64)",
    "usize": "(.scalar .uint64)",
    "int8": "(.scalar .int8)",
    "int16": "(.scalar .int16)",
    "int32": "(.scalar .int32)",
    "int64": "(.scalar .int64)",
    "isize": "(.scalar .int64)",
    "float": "(.scalar .float)",
    "float32": "(.scalar .float32)",
}

FAMILIES = {
    "LeanInitPureExtern1OnlyPrim": ("prim1Op", 1),
    "LeanInitPureExtern2OnlyPrim": ("prim2Op", 2),
    "LeanInitPureExtern3OnlyPrim": ("prim3Op", 3),
    "LeanInitPureExtern5": ("prim5Op", 5),
}

LINE = re.compile(r"^\s*\|\s*(\w+)\s*:\s*(LeanInitPureExtern\w+)\s+(.*?)\s*$")


def main() -> int:
    rows = []
    with open(SRC) as f:
        for line in f:
            if line.lstrip().startswith("-- "):
                continue
            m = LINE.match(line)
            if not m:
                continue
            name, family, rest = m.groups()
            if family not in FAMILIES:
                continue
            helper, arity = FAMILIES[family]
            toks = rest.split()
            if len(toks) != arity + 1:
                continue  # a type the parser does not read, such as `(bitvec 32)`
            if any(t not in TYPES for t in toks):
                continue
            args = ", ".join(TYPES[t] for t in toks[:-1])
            ret = TYPES[toks[-1]]
            rows.append((name, helper, args, ret))

    rows.sort()
    width = max(len(n) for n, _, _, _ in rows) + 2
    body = "\n".join(
        "  , \u27e8{n}, \"({h} .{name})\", [{args}], {ret}\u27e9".format(
            n=('"%s"' % name).ljust(width), h=helper, name=name, args=args, ret=ret
        )
        for name, helper, args, ret in rows
    )
    body = "  [" + body[3:] if body.startswith("  , ") else "  [" + body
    text = f'''import LakeJs.FrontEndTy

/-!
# The scalar functions of the runtime, by the C symbol that names them

Lean's `@[extern "lean_uint32_add"]` says which function of the runtime a declaration is
implemented by, and the constructors of the terminal families of
`LakeJs.LeanInitPureExterns` carry exactly those symbols.  This table pairs them up: for
each such constructor, the helper of `LakeJs.Expr.Ops` that applies it and the types of
its arguments and of its result, as the front end's `STy`.

So a call of a declaration that has no Lean body becomes a call of the runtime whenever
the C symbol of its `@[extern]` attribute is a row here, and the types of the row are the
ones the catalogue gives it — nothing about the call is guessed at.

**This file is generated by `scripts/gen-prim-extern-table.py` from
`LakeJs/LeanInitPureExterns.lean`.  Do not edit it by hand.**
-/

namespace LakeJs.FrontEnd

/-- A function of the runtime between terminal types: the C symbol Lean's `@[extern]`
    attribute names, the helper of `LakeJs.Expr.Ops` that applies it, and its type. -/
structure PrimExtern where
  /-- The C symbol, which is also the name of the catalogue constructor. -/
  cname : String
  /-- The helper of `LakeJs.Expr.Ops` that builds the call. -/
  helper : String
  /-- The types of its arguments. -/
  argTys : List STy
  /-- The type of its result. -/
  ret : STy

/-- Every scalar function of the catalogue, by the C symbol that names it. -/
def primExternTable : List PrimExtern :=
{body}
  ]

/-- The row of the runtime function a C symbol names, if the catalogue has one whose
    types are types of the front end. -/
def primExternOf? (cname : String) : Option PrimExtern :=
  primExternTable.find? (·.cname == cname)

end LakeJs.FrontEnd
'''
    with open(OUT, "w") as f:
        f.write(text)
    print(f"{OUT}: {len(rows)} runtime functions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
