#!/usr/bin/env python3
"""Generate `LakeJs/ExternsMeta.lean` and `LakeJs/ExternTable.lean` from `LakeJs/LeanPureExtern.lean`.

`LakeJs/LeanPureExtern.lean` is the hand-written catalogue of the functions Lean implements
with `@[extern]`, one constructor per function, each carrying the `Ty` of the function.
Every comment line above a constructor holds, in its third column, the *Lean* name of
the function the constructor stands for.

Two things are derived from that, mechanically, because they must not drift apart from
the catalogue:

* `LakeJs/ExternsMeta.lean` — the catalogue name and the arity of every constructor,
  which is what the printer needs to emit a saturated call;
* `LakeJs/ExternTable.lean` — the map from the Lean name to the constructor, which is
  what the translation needs to recognise a call to one of them.

Run it with `python3 scripts/gen-externs-meta.py` from the root of the project.
"""

import re
import sys

SRC = "LakeJs/LeanPureExtern.lean"
META = "LakeJs/ExternsMeta.lean"
TABLE = "LakeJs/ExternTable.lean"


def count_list_items(s: str) -> int:
    s = s.strip()
    if not s:
        return 0
    depth = 0
    count = 1
    for c in s:
        if c in "([":
            depth += 1
        elif c in ")]":
            depth -= 1
        elif c == "," and depth == 0:
            count += 1
    return count


def parse():
    lines = open(SRC).read().split("\n")
    out = []
    for i, l in enumerate(lines):
        m = re.match(r"^  \| (\w+)\s*:\s*(.*)$", l)
        if not m:
            continue
        name, sig = m.group(1), m.group(2)
        cols = [c.strip() for c in lines[i - 1].split("|")]
        lean_name = cols[3] if len(cols) > 4 else ""
        nty = sig.count("(α : Ty)") + sig.count("(β : Ty)")
        m_args = re.search(r"LeanPureExtern\s*\[(.*?)\]", sig)
        assert m_args, (name, sig)
        args_str = m_args.group(1).strip()
        arity = count_list_items(args_str)
        out.append((name, nty, arity, lean_name))
    return out


def main():
    cons = parse()
    if not cons:
        sys.exit("no constructors found in " + SRC)

    def pat(name, nty):
        return "." + name + ("" if nty == 0 else " " + " ".join(["_"] * nty))

    with open(META, "w") as f:
        f.write(
            """module

public import LakeJs.LeanPureExtern
public import LakeJs.Ty

@[expose] public section

namespace LakeJs.ExternsMeta

open LakeJs.LeanPureExtern
open LakeJs.Ty

/-!
# What the printer needs to know about an extern

Generated by `scripts/gen-externs-meta.py` from `LakeJs/LeanPureExtern.lean`; do not edit by
hand.  `LeanPureExtern.cName` is the name of the runtime function a call prints as, and
`LeanPureExtern.arity` is how many arguments that function takes — the number of items in
the parameter list the constructor is typed at.
-/

/-- The name the runtime prelude gives this extern: Lean's own symbol for it, which is
    what the constructor of `LeanPureExtern` is named after. -/
def LeanPureExtern.cName : ∀ {args : List Ty} {ret : Ty}, LeanPureExtern args ret → String
"""
        )
        for name, nty, _arity, _lean in cons:
            f.write('  | _, _, %s => "%s"\n' % (pat(name, nty), name))
        f.write(
            """
/-- How many arguments the runtime function takes.  A call with exactly this many
    arguments prints as one JavaScript call; anything else prints as the curried
    wrapper, so the two cannot disagree. -/
def LeanPureExtern.arity : ∀ {args : List Ty} {ret : Ty}, LeanPureExtern args ret → Nat
"""
        )
        for name, nty, arity, _lean in cons:
            f.write("  | _, _, %s => %d\n" % (pat(name, nty), arity))
        f.write("\nend LakeJs.ExternsMeta\n")

    seen = {}
    rows = []
    for name, nty, _arity, lean in cons:
        if not lean or lean in seen:
            continue
        seen[lean] = name
        rows.append((lean, name, nty))

    with open(TABLE, "w") as f:
        f.write(
            """module

public import Lean
public import Std.Data.HashMap
public import LakeJs.ExternsMeta
public import LakeJs.LeanPureExtern
public import LakeJs.Ty

@[expose] public section

namespace LakeJs.ExternTable

open Lean
open LakeJs.ExternsMeta
open LakeJs.LeanPureExtern
open LakeJs.Ty

/-!
# From a Lean name to the extern that implements it

Generated by `scripts/gen-externs-meta.py` from `LakeJs/LeanPureExtern.lean`; do not edit by
hand.  Each row is the Lean function named in the catalogue's comment, and the
constructor of `LeanPureExtern` that stands for it.  A polymorphic extern is a function of the
type arguments of the call, which the translation supplies from the call it is looking
at; a monomorphic one ignores them.

The rows are keyed by the *text* of the Lean name rather than by a name literal, so that
the catalogue may name a function this version of Lean does not have (or names
privately) without the table failing to build.
-/

/-- Every extern of the catalogue, keyed by the name of the Lean function it
    implements. -/
def externTable : Std.HashMap String (Ty → Ty → Σ (args : List Ty) (ret : Ty), LeanPureExtern args ret) :=
  Std.HashMap.ofList
"""
        )
        sep = "    [ "
        for lean, name, nty in rows:
            args = "" if nty == 0 else (" α" if nty == 1 else " α β")
            binder = "fun _ _ =>" if nty == 0 else ("fun α _ =>" if nty == 1 else "fun α β =>")
            f.write('%s("%s", %s ⟨_, _, .%s%s⟩)\n' % (sep, lean, binder, name, args))
            sep = "    , "
        f.write("    ]\n")
        f.write(
            """
/-- The extern that implements this Lean function, if the catalogue has one.  `α` and
    `β` are the type arguments of the call. -/
def externFor? (n : Name) (α β : Ty) : Option (Σ (args : List Ty) (ret : Ty), LeanPureExtern args ret) :=
  (externTable[n.toString]?).map fun f => f α β

end LakeJs.ExternTable
"""
        )

    print("%s: %d constructors" % (META, len(cons)))
    print("%s: %d Lean names" % (TABLE, len(rows)))


if __name__ == "__main__":
    main()
