#!/usr/bin/env python3
"""Write the Lean programs that print what each export of the `PrimOp*Configurable`
snapshots answers.

One program per snapshot module (the snapshots declare the same names, so they cannot
be imported together), under `scripts/expectations/`.  Each imports its module and
evaluates every export: a constant as it stands, a function at the arguments listed
here, and prints the answers as JSON.  `scripts/regen-primop-expectations.sh` runs them
and writes `scripts/expectations/<Module>.json`, which the Node suites of the generated
JavaScript read — so the expected answers are Lean's own and nothing is written twice.

    python3 scripts/gen-primop-expectations.py
    scripts/regen-primop-expectations.sh
"""

import os

UNSIGNED = [("1", "1"), ("7", "3"), ("255", "16"), ("5", "0"), ("1023", "2")]
NATARGS = [("10", "3"), ("0", "5"), ("7", "7"), ("5", "0"), ("1023", "2")]
SIGNED = [("7", "3"), ("-7", "3"), ("-8", "-3"), ("5", "0"), ("1023", "2")]

# the arguments the narrow fixed-width types are exercised at: an argument outside the
# range of the type would be wrapped by Lean and *not* by the generated JavaScript,
# which holds such a value as the plain number it is, so every one of these fits
UNSIGNED8 = [("1", "1"), ("7", "3"), ("255", "16"), ("5", "0"), ("200", "2")]
SIGNED8 = [("7", "3"), ("-7", "3"), ("-8", "-3"), ("5", "0"), ("100", "2")]

# the namespaces of the snapshots, the argument pairs each is exercised at, and the
# arguments of its unary operation (`None` where it has none)
NAMESPACES = [
    ("TestUInt64", UNSIGNED, ["1", "255", "0"]),
    ("TestUSize", UNSIGNED, ["1", "255", "0"]),
    ("TestNat", NATARGS, None),
    ("TestInt64", SIGNED, ["1", "-1", "0"]),
    ("TestISize", SIGNED, ["1", "-1", "0"]),
    ("TestInt", SIGNED, ["1", "-1", "0"]),
]

# the namespaces of the `*NonConfigurable` snapshots: the types no knob can change,
# which are held as JavaScript numbers whatever the configuration says
NONCONF_NAMESPACES = [
    ("TestUInt8", UNSIGNED8, ["1", "255", "0"]),
    ("TestUInt16", UNSIGNED, ["1", "255", "0"]),
    ("TestUInt32", UNSIGNED, ["1", "255", "0"]),
    ("TestInt8", SIGNED8, ["1", "-1", "0"]),
    ("TestInt16", SIGNED, ["1", "-1", "0"]),
    ("TestInt32", SIGNED, ["1", "-1", "0"]),
]

# the namespaces of the `PrimOpBitVec*Configurable` snapshots: `BitVec 32` and
# `BitVec 64`, the widths `bitvecRepr` decides (a narrower bit vector is a JavaScript
# number whatever the configuration says)
BITVEC_NAMESPACES = [
    ("TestBitVec32", UNSIGNED, ["1", "255", "0"]),
    ("TestBitVec64", UNSIGNED, ["1", "255", "0"]),
]

BINOPS_01 = ["add", "sub", "eq", "ne", "lt", "gt", "le", "ge", "mul", "div"]
BINOPS_BIT01 = ["land", "lor", "shiftLeft", "shiftRight", "xor"]


def calls_01(namespaces=None):
    out = []
    for ns, args, unary in namespaces or NAMESPACES:
        for op in BINOPS_01:
            for a, b in args:
                out.append((f"{ns}_{op}", [a, b], f"{ns}.{op} ({a}) ({b})"))
        if unary is not None:
            for a in unary:
                out.append((f"{ns}_neg", [a], f"{ns}.neg ({a})"))
    return out


def calls_bit01(namespaces=None):
    out = []
    for ns, args, unary in namespaces or NAMESPACES:
        if ns == "TestInt":
            # `PrimOpIntBit01Configurable` gives `Int` only the complement
            for a in unary:
                out.append((f"{ns}_complement", [a], f"{ns}.complement ({a})"))
            continue
        for op in BINOPS_BIT01:
            for a, b in args:
                out.append((f"{ns}_{op}", [a, b], f"{ns}.{op} ({a}) ({b})"))
        if unary is not None:
            for a in unary:
                out.append((f"{ns}_complement", [a], f"{ns}.complement ({a})"))
    return out


def values_02(namespaces=None):
    out = []
    for ns, _, _ in namespaces or NAMESPACES:
        tests = list(range(1, 11)) + ([] if ns == "TestNat" else [11])
        for i in tests:
            out.append((f"{ns}_test{i}", f"{ns}.test{i}"))
    return out


def values_03(namespaces=None):
    return [
        (f"{ns}_test{i}", f"{ns}.test{i}")
        for ns, _, _ in namespaces or NAMESPACES
        for i in (1, 2, 3)
    ]


def calls_03(namespaces=None):
    # `test4` of each namespace takes one argument
    return [
        (f"{ns}_test4", ["3"], f"{ns}.test4 (3)") for ns, _, _ in namespaces or NAMESPACES
    ]


def values_bit02(namespaces=None):
    ops = ["land", "lor", "shiftLeft", "shiftRight", "xor", "complement"]
    out = []
    for ns, _, _ in namespaces or NAMESPACES:
        if ns == "TestInt":
            out.append((f"{ns}_complement", f"{ns}.complement"))
            continue
        for op in ops:
            if op == "complement" and ns == "TestNat":
                continue
            out.append((f"{ns}_{op}", f"{ns}.{op}"))
    return out


PREAMBLE = '''-- Generated by `scripts/gen-primop-expectations.py`; do not edit by hand.
--
-- Prints, as JSON, what every export of `SnapshotsPBOPure/{module}.lean` answers in
-- Lean: a constant as it stands, a function at the arguments the generator lists.  The
-- Node suites of the generated JavaScript read the result and check the module against
-- it — a configurable module has two of them (`-num.js` and `-bigint.js`) and a
-- non-configurable module one — so the expected answers are Lean's own and no answer is
-- written down by hand.
--
--     scripts/regen-primop-expectations.sh
import SnapshotsPBOPure.{module}

/-- How an answer is written down: the same rendering the Node suites compute from the
    JavaScript value, so that the two can be compared as strings. -/
class Render (α : Type) where
  render : α → String

export Render (render)

instance : Render Nat := ⟨toString⟩
instance : Render UInt8 := ⟨fun a => toString a.toNat⟩
instance : Render UInt16 := ⟨fun a => toString a.toNat⟩
instance : Render UInt32 := ⟨fun a => toString a.toNat⟩
instance : Render Int8 := ⟨fun a => toString a.toInt⟩
instance : Render Int16 := ⟨fun a => toString a.toInt⟩
instance : Render Int32 := ⟨fun a => toString a.toInt⟩
instance : Render Int := ⟨toString⟩
instance : Render Bool := ⟨toString⟩
instance : Render UInt64 := ⟨fun a => toString a.toNat⟩
instance : Render USize := ⟨fun a => toString a.toNat⟩
instance : Render Int64 := ⟨fun a => toString a.toInt⟩
instance : Render ISize := ⟨fun a => toString a.toInt⟩
instance {w : Nat} : Render (BitVec w) := ⟨fun a => toString a.toNat⟩
instance [Render α] : Render (Array α) :=
  ⟨fun xs => "[" ++ String.intercalate "," (xs.toList.map render) ++ "]"⟩

private def quote (s : String) : String := "\\"" ++ s ++ "\\""

/-- One call of an exported function, and what Lean answers. -/
private structure Call where
  fn : String
  args : List String
  expected : String

/-- One exported constant, and what Lean answers. -/
private structure Value where
  name : String
  expected : String

private def Call.toJson (c : Call) : String :=
  "{\\"fn\\": " ++ quote c.fn ++ ", \\"args\\": [" ++
    String.intercalate ", " (c.args.map quote) ++ "], \\"expected\\": " ++
    quote c.expected ++ "}"

private def Value.toJson (v : Value) : String :=
  "{\\"name\\": " ++ quote v.name ++ ", \\"expected\\": " ++ quote v.expected ++ "}"

private def calls : List Call :=
[
{calls}
]

private def values : List Value :=
[
{values}
]

def main : IO Unit := do
  IO.println "{{"
  IO.println ("  \\"calls\\": [" ++
    (if calls.isEmpty then "],"
     else "\\n" ++ String.intercalate ",\\n" (calls.map fun c => "    " ++ c.toJson) ++
       "\\n  ],"))
  IO.println ("  \\"values\\": [" ++
    (if values.isEmpty then "]"
     else "\\n" ++ String.intercalate ",\\n" (values.map fun v => "    " ++ v.toJson) ++
       "\\n  ]"))
  IO.println "}}"
'''


def render_calls(calls):
    return ",\n".join(
        '  ⟨"{}", [{}], render ({})⟩'.format(
            name, ", ".join('"' + a + '"' for a in args), expr
        )
        for name, args, expr in calls
    )


def render_values(values):
    return ",\n".join(f'  ⟨"{name}", render ({expr})⟩' for name, expr in values)


MODULES = {
    "PrimOpInt01Configurable": (calls_01(), []),
    "PrimOpInt02Configurable": ([], values_02()),
    "PrimOpInt03Configurable": (calls_03(), values_03()),
    "PrimOpIntBit01Configurable": (calls_bit01(), []),
    "PrimOpIntBit02Configurable": ([], values_bit02()),
    "PrimOpBitVec01Configurable": (calls_01(BITVEC_NAMESPACES), []),
    "PrimOpBitVec02Configurable": (calls_bit01(BITVEC_NAMESPACES), []),
    "PrimOpInt01NonConfigurable": (calls_01(NONCONF_NAMESPACES), []),
    "PrimOpInt02NonConfigurable": ([], values_02(NONCONF_NAMESPACES)),
    "PrimOpInt03NonConfigurable": (
        calls_03(NONCONF_NAMESPACES),
        values_03(NONCONF_NAMESPACES),
    ),
    "PrimOpIntBit01NonConfigurable": (calls_bit01(NONCONF_NAMESPACES), []),
    "PrimOpIntBit02NonConfigurable": ([], values_bit02(NONCONF_NAMESPACES)),
}


def main():
    os.makedirs("scripts/expectations", exist_ok=True)
    for module, (calls, values) in MODULES.items():
        body = (
            PREAMBLE.replace("{module}", module)
            .replace("{calls}", render_calls(calls))
            .replace("{values}", render_values(values))
            .replace("{{", "{")
            .replace("}}", "}")
        )
        with open(f"scripts/expectations/{module}.lean", "w") as f:
            f.write(body)


if __name__ == "__main__":
    main()
