#!/usr/bin/env python3
"""Generate `LakeJs/ExternsMeta.lean` and `LakeJs/ExternTable.lean` from `LakeJs/Externs.lean`.

`LakeJs/Externs.lean` is the hand-written catalogue of the functions Lean implements
with `@[extern]`, one constructor per function, each carrying the `Ty` of the function.
Every comment line above a constructor holds, in its third column, the *Lean* name of
the function the constructor stands for.

Two things are derived from that, mechanically, because they must not drift apart from
the catalogue:

* `LakeJs/ExternsMeta.lean` — the catalogue name and the arity of every constructor,
  which is what the printer needs to emit a saturated call;
* `LakeJs/ExternTable.lean` — the map from the Lean name to the constructor, which is
  what the translation needs to recognise a call to one of them.

Run it with `python3 scripts/gen-externs-meta.py` from the root of the project.
"""

import re
import sys

SRC = "LakeJs/Externs.lean"
META = "LakeJs/ExternsMeta.lean"
TABLE = "LakeJs/ExternTable.lean"


def top_level_arrows(s: str) -> int:
    depth = 0
    n = 0
    i = 0
    while i < len(s):
        c = s[i]
        if c in "([":
            depth += 1
        elif c in ")]":
            depth -= 1
        elif c == "\u21d2" and depth == 0:
            n += 1
        i += 1
    return n


def parse():
    lines = open(SRC).read().split("\n")
    out = []
    for i, l in enumerate(lines):
        m = re.match(r"^  \| (\w+)\s*:\s*(.*)$", l)
        if not m:
            continue
        name, sig = m.group(1), m.group(2)
        cols = [c.strip() for c in lines[i - 1].split("|")]
        lean_name = cols[3] if len(cols) > 4 else ""
        nty = sig.count("(\u03b1 : Ty)") + sig.count("(\u03b2 : Ty)")
        body = sig.split("Externs", 1)[1].strip()
        # strip the outermost parentheses of the type index
        assert body.startswith("(") and body.endswith(")"), (name, body)
        inner = body[1:-1]
        arity = top_level_arrows(inner)
        if inner.strip().startswith(".nullary"):
            arity += 1
        out.append((name, nty, arity, lean_name))
    return out


def main():
    cons = parse()
    if not cons:
        sys.exit("no constructors found in " + SRC)

    def pat(name, nty):
        return "." + name + ("" if nty == 0 else " " + " ".join(["_"] * nty))

    with open(META, "w") as f:
        f.write(
            """module
public import LakeJs.Externs
@[expose] public section

/-!
# What the printer needs to know about an extern

Generated by `scripts/gen-externs-meta.py` from `LakeJs/Externs.lean`; do not edit by
hand.  `Externs.cName` is the name of the runtime function a call prints as, and
`Externs.arity` is how many arguments that function takes — the number of arrows in the
type the catalogue gives the constructor, which is *not* the same as the number of
arrows in the `Ty` the constructor is applied at, since a type argument may itself be a
function type.
-/

/-- The name the runtime prelude gives this extern: Lean's own symbol for it, which is
    what the constructor of `Externs` is named after. -/
def Externs.cName : \u2200 {\u03c4 : Ty}, Externs \u03c4 \u2192 String
"""
        )
        for name, nty, _arity, _lean in cons:
            f.write('  | _, %s => "%s"\n' % (pat(name, nty), name))
        f.write(
            """
/-- How many arguments the runtime function takes.  A call with exactly this many
    arguments prints as one JavaScript call; anything else prints as the curried
    wrapper, so the two cannot disagree. -/
def Externs.arity : \u2200 {\u03c4 : Ty}, Externs \u03c4 \u2192 Nat
"""
        )
        for name, nty, arity, _lean in cons:
            f.write("  | _, %s => %d\n" % (pat(name, nty), arity))
        f.write("\nend\n")

    seen = {}
    rows = []
    for name, nty, _arity, lean in cons:
        if not lean or lean in seen:
            continue
        seen[lean] = name
        rows.append((lean, name, nty))

    with open(TABLE, "w") as f:
        f.write(
            """import Lean
import Std.Data.HashMap
import LakeJs.ExternsMeta

/-!
# From a Lean name to the extern that implements it

Generated by `scripts/gen-externs-meta.py` from `LakeJs/Externs.lean`; do not edit by
hand.  Each row is the Lean function named in the catalogue's comment, and the
constructor of `Externs` that stands for it.  A polymorphic extern is a function of the
type arguments of the call, which the translation supplies from the call it is looking
at; a monomorphic one ignores them.

The rows are keyed by the *text* of the Lean name rather than by a name literal, so that
the catalogue may name a function this version of Lean does not have (or names
privately) without the table failing to build.
-/

namespace LakeJs

open Lean

/-- Every extern of the catalogue, keyed by the name of the Lean function it
    implements. -/
def externTable : Std.HashMap String (Ty \u2192 Ty \u2192 \u03a3 \u03c4 : Ty, Externs \u03c4) :=
  Std.HashMap.ofList
"""
        )
        sep = "    [ "
        for lean, name, nty in rows:
            args = "" if nty == 0 else (" \u03b1" if nty == 1 else " \u03b1 \u03b2")
            binder = "fun _ _ =>" if nty == 0 else ("fun \u03b1 _ =>" if nty == 1 else "fun \u03b1 \u03b2 =>")
            f.write('%s("%s", %s \u27e8_, .%s%s\u27e9)\n' % (sep, lean, binder, name, args))
            sep = "    , "
        f.write("    ]\n")
        f.write(
            """
/-- The extern that implements this Lean function, if the catalogue has one.  `\u03b1` and
    `\u03b2` are the type arguments of the call. -/
def externFor? (n : Name) (\u03b1 \u03b2 : Ty) : Option (\u03a3 \u03c4 : Ty, Externs \u03c4) :=
  (externTable[n.toString]?).map fun f => f \u03b1 \u03b2

end LakeJs
"""
        )

    print("%s: %d constructors" % (META, len(cons)))
    print("%s: %d Lean names" % (TABLE, len(rows)))


main()
